<?php 
use App\Models\Produtos;
use Libraries\Sessao;

$Produtos = new Produtos;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresa) ? count($empresa) : 0);
$qtdM = (is_array($movimentacoes) ? count($movimentacoes) : 0);

$qtdC = (is_array($clientes) ? count($clientes) : 0);

$motivos = array(
    0 => '---',
    1 =>'COMPRA',
    2 =>'VENDA',
    3 =>'AJUSTE',
    4 =>'DEVOLUÇÃO CLIENTE',
    5=>'DEVOLUÇÃO FORNECEDOR',
    6=>'PERDA',
    7=>'OUTROS'
);
$qtdMotivos = (is_array($motivos) ? count($motivos) : 0);
?>

<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>movimentacoes/listar">
                                <h3 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box"></i> Listagem de <span class="text-success"> Movimentação De Produtos</span></h3></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="col-12 row">
                    <div class="col-4 text-center">
                        <div class="card-body">
                            <h5 class="card-title">ESTOQUE ATUAL</h5>
                            <p class="card-text">Verifique o estoque atual dos seus produtos</p>
                            <a href="<?= DIRPAGE ?>estoques/produtos_atual" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>    
                    <div class="col-8 mx-auto text-bg-success text-center">
                        <div class="card-body">
                            <h5 class="card-title">SELECIONE O ESTOQUE</h5>
                            <p class="card-text">
                                <select class="form-select" id="buscar_produtos" name="EST_COD">     
                                    <option value="0" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == 0)? 'selected' : '' ?>>---</option>                     
                                    <?php 
                                    for ($i=0; $i < $qtd; $i++) { if ($estoques[$i]['EST_STATUS'] == 1) { ?>
                                        <option value="<?= $estoques[$i]['EST_COD'] ?>" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == $estoques[$i]['EST_COD'])? 'selected' : '' ?>><?= $estoques[$i]['EST_DESCRICAO'] ?></option>
                                    <?php } } ?>
                                </select>
                            </p>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                    <div class="col-12 mx-auto text-center m-1">
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>movimentacoes/movimentacao"><i class="bi bi-arrow-left"></i> VOLTAR AOS MOVI</a>
                    </div>
            </section>
            <section class="bg-light text-dark">
                <section class="container py-1">
                    <hr>
                    <div id="resposta2" class="fs-4 text-center"></div>
                    <?= Sessao::alert('OK'); ?>
                    <?= Sessao::alert('ERRO'); ?>
                </section>
           
                <div class="container mx-auto col-12 px-2 py-2 row ">
                    
                    <div class="col-12 mx-auto text-center m-1">
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                    </div>
                <?php if($qtdM != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">ESTOQUE</th>
                            <th class="text-dark">CÓDIGO</th>
                            <th class="text-dark">PRODUTO</th>
                            <th class="text-dark">DATA</th>
                            <th class="text-dark">ENTRADA</th>
                            <th class="text-dark">SAÍDA</th>
                            <th class="text-dark">MOTIVO</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Ações</th>
                        </thead>
                        <tbody>
                            <?php $b = 1; for ($i=0; $i < $qtdM; $i++) { 
                                 $data = new DateTime($movimentacoes[$i]['MOV_DT_MOVIMENTACAO']);
                                
                            if($movimentacoes[$i]['MOV_STATUS'] != 0){ 
                            ?>
                            <tr class="<?= ($movimentacoes[$i]['MOV_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['EST_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['PRO_COD']; ?></td>
                                <td class="text-center align-middle">
                                    <?php $produto = $Produtos->setCodEmpresa($movimentacoes[$i]['EMP_COD'])->setCodEstoque($movimentacoes[$i]['EST_COD'])->setCodigo($movimentacoes[$i]['PRO_COD'])->listar(0);
                                    echo $produto['PRO_NOME'];
                                    ?>
                                </td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <?= ($movimentacoes[$i]['MOV_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span></td><td></td>' : '<td></td><td class="text-center align-middle"><span class="text-danger">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span>'; ?></td>
                                <td class="text-center align-middle">
                                    <?php for ($m=0; $m < $qtdMotivos; $m++) { ?>
                                        <?= (isset($movimentacoes[$i]['MOV_MOTIVO']) &  $movimentacoes[$i]['MOV_MOTIVO']  == $m)? $motivos[$m]: '' ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center align-middle"><?= ($movimentacoes[$i]['MOV_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
                                    <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="" data-codigo="<?= $movimentacoes[$i]['MOV_COD']; ?>" data-produto="<?= $movimentacoes[$i]['PRO_COD']; ?>" data-nome="<?= $produto['PRO_NOME']; ?>" data-estoque="<?= $movimentacoes[$i]['EST_COD']; ?>"  data-status="<?= $movimentacoes[$i]['MOV_STATUS']; ?>" title="Deseja excluir?" ><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                        <?php }else { ?>
                            <tr class="<?= ($_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['EST_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['PRO_COD']; ?></td>
                                <td class="text-center align-middle">
                                    <?php $produto = $Produtos->setCodEmpresa($movimentacoes[$i]['EMP_COD'])->setCodEstoque($movimentacoes[$i]['EST_COD'])->setCodigo($movimentacoes[$i]['PRO_COD'])->listar(0);
                                    echo $produto['PRO_NOME'];
                                    ?>
                                </td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <?= ($movimentacoes[$i]['MOV_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span></td><td></td>' : '<td></td><td class="text-center align-middle"><span class="text-danger">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span>'; ?></td>
                                <td class="text-center align-middle">
                                    <?php for ($m=0; $m < $qtdMotivos; $m++) { ?>
                                        <?= (isset($movimentacoes[$i]['MOV_MOTIVO']) &  $movimentacoes[$i]['MOV_MOTIVO']  == $m)? $motivos[$m]: '' ?>
                                    <?php } ?>
                                </td>
                                <td class="text-center align-middle"><?= ($movimentacoes[$i]['MOV_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
        
                                </td>
                            </tr>
                            <?php } ?>
                        <?php  $b++; } ?>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">NENHUMA MOVIMENTAÇÃO DE PRODUTOS</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header mx-auto text-center text-uppercase">
                    Deseja <b>Reverter a movimentação</b> deste Produto?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma reversão deste registro?</p>
                    <span id="PRO_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="MOV_STATUS" name="MOV_STATUS" value="" />
                    <input type="hidden" id="MOV_COD" name="MOV_COD" value="" />
                    <input type="hidden" id="PRO_COD" name="PRO_COD" value="" />
                    <input type="hidden" id="EST_COD2" name="EST_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <input type="hidden" id="USU_COD" name="USU_COD" value="<?= $_SESSION['USU_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        
        $("#buscar_produtos").change(function(){
            var EST_COD = $(this).find('option:selected').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;
            carregarProdutos(EST_COD, EMP_COD,"#produtos");
        });
        
        function carregarProdutos(EST_COD, EMP_COD,selecionado="#produtos"){
            $.post('<?= DIRPAGE; ?>movimentacoes/listar_produtos', {PRODUTOS_ESTOQUE: true,EMP_COD: EMP_COD,EST_COD:EST_COD,cache: false}, function(retorno) {
                
                dados = JSON.parse(retorno);
                
                $(selecionado).find('option').remove().end();
                $(selecionado).append($('<option>', {
                    value: 0,
                    text: '---'
                }));
                //console.log(dados);
                document.getElementById("EST_COD").value ='';
                document.getElementById("EST_COD").value = EST_COD;

                for(var i=0;dados.length>i;i++){
                    if(dados[i].PRO_STATUS == 1){
                        $(selecionado).append($('<option>', {
                            value: dados[i].PRO_COD,
                            text: dados[i].PRO_NOME
                        }));
                    }
                    //console.log(dados[i].PRO_NOME);
                    //console.log(codificarHtml(dados[i].PRO_NOME));
                }
                function codificarHtml(texto){
                    var htmlCodigo = { 
                                '&aacute;' : {'code' : 'á'},
                                '&Aacute;' : {'code' : 'Á'},
                                '&atilde;' : {'code' : 'ã'},
                                '&Atilde;' : {'code' : 'Ã'},
                                '&agrave;' : {'code' : 'à'},
                                '&Agrave;' : {'code' : 'À'},                       
                                '&eacute;' : {'code' : 'é'},
                                '&Eacute;' : {'code' : 'É'},
                                '&iacute;' : {'code' : 'í'},
                                '&Iacute;' : {'code' : 'Í'},
                                '&oacute;' : {'code' : 'ó'},
                                '&Oacute;' : {'code ': 'Ó'}, 
                                '&otilde;' : {'code' : 'õ'},
                                '&Otilde;' : {'code' : 'Õ'},
                                '&uacute;' : {'code' : 'ú'},
                                '&Uacute;' : {'code' : 'Ú'},
                                '&ccedil;' : {'code' : 'ç'},
                                '&Ccedil;' : {'code' : 'Ç'}                      };
                    var acentos = ['á', 'Á', 'ã', 'Ã', 'à', 'À', 'é', 'É', 'í', 'Í', 'ó', 'Ó', 'õ', 'Õ', 'ú', 'Ú', 'ç', 'Ç'];
                    
                    for(var i=0; i<acentos.length; i++){
                        if(htmlCodigo [acentos[i]] != undefined){
                            texto = texto.replaceAll(acentos[i], htmlCodigo[acentos[i]].code );
                        }
                    }
                    return texto;
                }
    
            });
        }
        $("#produtos").change(function(){

            var PRO_COD = $(this).find('option:selected').val();
            var EST_COD = $('#EST_COD').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;

            $.post('<?= DIRPAGE; ?>movimentacoes/listar_produto', {PRODUTOS: true,EMP_COD: EMP_COD,EST_COD:EST_COD,PRO_COD: PRO_COD}, function(retorno) {
                db = JSON.parse(retorno);
                $('#PRO_QUANTIDADE').html(db.PRO_QUANTIDADE);
            });
        });
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var estoque = button.data('estoque');
                var produto = button.data('produto'); 
                var modal = $(this);
                modal.find('#MOV_COD').val(codigo);
                modal.find('#PRO_COD').val(produto);
                modal.find('#EST_COD2').val(estoque);
                modal.find('#MOV_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#PRO_NOME').html(nome);

                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja reverter a movimentação?');
                }else{
                    //modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    //modal.find('#title').html('Deseja ativar a movimentação?');
                }
            });
        });
        $("#sts").click(function(){
            var PRO_COD = $('#PRO_COD').val();
            var EMP_COD = $('#EMP_COD').val();
            var USU_COD = $('#USU_COD').val();
            var EST_COD = $('#EST_COD2').val();
            var MOV_COD = $('#sts').val();
            var MOV_STATUS = $('#MOV_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>movimentacoes/reverter_movimentacao', {
                PRO_COD: PRO_COD,
                EXCLUIR_MOVIMENTACAO_PRODUTO: true,
                EMP_COD:EMP_COD,
                EST_COD:EST_COD,
                MOV_COD:MOV_COD, 
                USU_COD:USU_COD,
                MOV_STATUS: MOV_STATUS
            }, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta2').addClass('alert alert-success');
                }else{
                    $('#resposta2').addClass('alert alert-warning');
                }
                $('#resposta2').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>movimentacoes/"+EMP_COD+"/"+EST_COD}, 500);
            });

        });

    </script>
</body>

</html>    