<?php 
use App\Models\Produtos;
use Libraries\Sessao;

$Produtos = new Produtos;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresa) ? count($empresa) : 0);
$qtdM = (is_array($movimentacoes) ? count($movimentacoes) : 0);
$qtdF = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
$qtdCA = (is_array($caixas) ? count($caixas) : 0);
$qtdEstoque = 0;
for ($i=0; $i < $qtd; $i++) { if ($estoques[$i]['EST_STATUS'] == 1) {$qtdEstoque++; }}
$qtdClientes = (is_array($clientes) ? count($clientes) : 0);

$motivos_entrada = array(
    1 =>'COMPRA',
    2 =>'DEVOLUÇÃO DO CLIENTE',
    3 =>'OUTROS'
);
$motivos_saida = array(
    1 =>'VENDA',
    2 =>'DEVOLUÇÃO AO FORNECEDOR',
    3 =>'PERDA',
    4 =>'OUTROS'
);
$motivos = array(
    0 => '---',
    1 =>'ENTRADA-COMPRA',
    2 =>'SAÍDA-VENDA',
    3 =>'ENTRADA-DEVOLUÇÃO DO CLIENTE',
    4 =>'SAÍDA-DEVOLUÇÃO AO FORNECEDOR',
    5 =>'SAÍDA-PERDA',
    6 =>'ENTRADA.SAÍDA-OUTROS'
);
$qtdMotivos = (is_array($motivos) ? count($motivos) : 0);
$qtdMotEntrada = (is_array($motivos_entrada) ? count($motivos_entrada) : 0);
$qtdMotSaida = (is_array($motivos_saida) ? count($motivos_saida) : 0);
$contagem = 1;
?>
<style>

.hidden {
  display: none; }
</style>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3 <?= $modulo[0]['MOD_COR'] ?> ">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>movimentacoes/listar">
                                <h3 class="fs-2 fw-bolder text-uppercase text-white"><?= $modulo[0]['MOD_ICON'] ?> <i class="bi bi-arrow-down-up"></i> Listagem de <span class="text-dark"> Movimentação De Produtos</span></h3></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            
            <section class="container bg-light mx-auto py-2">
                
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>

        </div>
    </div>
    <script type="text/javascript">
 </script>
</body>

</html>    