<?php 
use App\Models\Produtos;
use Libraries\Sessao;

$Produtos = new Produtos;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresa) ? count($empresa) : 0);
$qtdM = (is_array($movimentacoes) ? count($movimentacoes) : 0);
$qtdF = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
$qtdCA = (is_array($caixas) ? count($caixas) : 0);
$qtdEstoque = 0;
for ($i=0; $i <= $qtd; $i++) { if ($estoques[$i]['EST_STATUS'] == 1) {$qtdEstoque++; }}
$qtdClientes = (is_array($clientes) ? count($clientes) : 0);

$motivos_entrada = array(
    1 =>'COMPRA',
    2 =>'DEVOLUÇÃO DO CLIENTE',
    3 =>'OUTROS'
);
$motivos_saida = array(
    1 =>'VENDA',
    2 =>'DEVOLUÇÃO AO FORNECEDOR',
    3 =>'PERDA',
    4 =>'OUTROS'
);
$motivos = array(
    0 => '---',
    1 => 'ENTRADA-COMPRA',
    2 => 'SAÍDA-PRODUÇÃO',
    3 => 'SAÍDA-PERDA',
    4 => 'SAÍDA-DEVOLUÇÃO AO FORNECEDOR',
    5 => 'ENTRADA-DEVOLUÇÃO DO CLIENTE',
    6 => 'ENTRADA.SAÍDA-OUTROS'
);
$qtdMotivos = (is_array($motivos) ? count($motivos) : 0);
$qtdMotEntrada = (is_array($motivos_entrada) ? count($motivos_entrada) : 0);
$qtdMotSaida = (is_array($motivos_saida) ? count($motivos_saida) : 0);
$contagem = 1;
?>
<style>

.hidden {
  display: none; }
</style>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3 <?= $modulo[0]['MOD_COR'] ?> ">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>movimentacoes">
                                <h3 class="fs-2 fw-bolder text-uppercase text-white"><?= $modulo[0]['MOD_ICON'] ?> <i class="bi bi-arrow-down-up"></i> Movimentação De <span class="text-dark">Estoque</span></h3></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            
            <section class="container bg-light mx-auto py-2">
                <div class="col-12 row">
                    <div class="col-6 mx-auto  text-center <?= $modulo[0]['MOD_COR'] ?>">
                        <div class="card-body">
                            <h5 class="card-title">ESTOQUE ATUAL</h5>
                            <p class="card-text">Verifique o estoque atual dos seus produtos</p>
                            <a href="<?= DIRPAGE ?>estoques/produtos_atual" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>    
                    <div class="col-6 mx-auto  text-center">
                        <div class="card-body">
                            <h5 class="card-title">LISTAR MOVIMENTAÇÃO DE ESTOQUES</h5>
                            <p class="card-text">Veja as entradas e saídas de produtos</p>
                            <a href="<?= DIRPAGE ?>movimentacoes/listar" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    
                    <div class="col-12 mx-auto text-center m-1">
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                    </div>
                    <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                    <section class="container py-1">
                        <hr>
                        <div id="resposta2" class="fs-4 text-center"></div>
                        <?= Sessao::alert('OK'); ?>
                        <?= Sessao::alert('ERRO'); ?>
                    </section>
                    <hr class="my-4 text-dark">
                    <h5 class="card-title text-center"><i class="bi bi-box2-fill"></i> MOVIMENTAÇÃO DO PRODUTO</h5>
                    <div class="container col-12 px-1 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3" action="<?= DIRPAGE ?>movimentacoes/<?= ($_SESSION['USU_NIVEL'] >= 11)? 'registrar': 'cadastrar'; ?>" method="POST">
                            <div class="col-12 mx-auto <?= $modulo[0]['MOD_COR'] ?> text-center">
                                <div class="card-body">
                                    <h5 class="card-title">SELECIONE O ESTOQUE</h5>
                                    <p class="card-text">
                                        <select class="form-select" id="buscar_produtos" name="EST_COD">    
                                        <?php if ($qtdEstoque >= 2) {  ?>
                                            <option value="0" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == 0)? 'selected' : '' ?>>---</option>                  
                                        <?php } ?>
                                        <?php 
                                            for ($i=0; $i < $qtdEstoque; $i++) { if ($estoques[$i]['EST_STATUS'] == 1) { ?>
                                                <option value="<?= $estoques[$i]['EST_COD'] ?>" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == $estoques[$i]['EST_COD'])? 'selected' : '' ?>><?= $estoques[$i]['EST_DESCRICAO'] ?></option>
                                        <?php } } ?>
                                        </select>
                                    </p>
                                </div>
                            </div>
                            <div class="col-12 row mt-3">   
                                <div class="col-4 form-floating mb-2">
                                    <input type="date" name="MOV_DT_MOVIMENTACAO" class="form-control form-control-lg" value="<?= isset($_POST['MOV_DT_MOVIMENTACAO']) ? $_POST['MOV_DT_MOVIMENTACAO'] : date('Y-m-d') ?>">
                                    <label class="form-label">DATA</label>
                                </div>
                                <div class="col-3 form-floating mb-2">
                                    <select class="form-select" id="tipo" name="MOV_TIPO">
                                        <option value="0" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 0)? 'selected' : '' ?>>---</option>
                                        <option value="1" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 1)? 'selected' : '' ?>>ENTRADA</option>
                                        <option value="2" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 2)? 'selected' : '' ?>>SAÍDA</option>
                                    </select>
                                    <label class="form-label">TIPO</label>
                                </div>
                                <div class="col-5 form-floating mb-2 ">
                                    <select class="form-select" name="MOV_MOTIVO">
                                        <?php for ($e=0; $e < $qtdMotivos; $e++) { ?>
                                            <option value="<?= $e ?>" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == $e)? 'selected' : '' ?>><?= $motivos[$e] ?></option>
                                        <?php } ?>
                                    </select>
                                    <label class="form-label">MOTIVO</label>
                                </div>
                                <div class="col-8 form-floating mb-2" id="retorno">
                                    <select class="form-select form-control-lg" id="produtos" name="PRO_COD">   
                                        <option value="0">SELECIONE UM ESTOQUE</option>
                                    </select>
                                    <label class="form-label">SELECIONE O PRODUTO</label>
                                </div>
                                <?php if($_SESSION['USU_NIVEL'] >= 1){ ?>
                                    <div class="col-4 mx-auto form-floating mb-3" @keydown.enter.stop>
                                        <div class="input-group input-group-lg">
                                            <div class="form-floating">
                                                <input type="number" class="form-control maiusculo" id="MOV_QUANTIDADE" name="MOV_QUANTIDADE" min="0" value="<?= isset($_POST['MOV_QUANTIDADE']) ? $_POST['MOV_QUANTIDADE'] : ''; ?>">
                                                <label class="px-2" for="MOV_QUANTIDADE">QUANTIDADE</label>
                                            </div>
                                            <button type="button" class="btn text-uppercase <?= $modulo[0]['MOD_COR'] ?>" id="adicionar"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                <?php }else { ?>
                                    <div class="col-4 mx-auto form-floating mb-3" @keydown.enter.stop>
                                        <div class="form-floating">
                                            <input type="number" class="form-control maiusculo" id="MOV_QUANTIDADE" name="MOV_QUANTIDADE" min="0" value="<?= isset($_POST['MOV_QUANTIDADE']) ? $_POST['MOV_QUANTIDADE'] : ''; ?>">
                                            <label class="px-2" for="MOV_QUANTIDADE">QUANTIDADE</label>
                                        </div>
                                    </div>                                        
                                <?php } ?>
                                <div class="col-12 mx-auto fs-4 mb-2 text-center">
                                    <label class="px-2" for="2">QUANTIDADE ATUAL</label>
                                    <b class="text-dark"><br><span id="PRO_QUANTIDADE">0</span></b>
                                </div>
                                <section class="container py-1">
                                    <div id="resposta3" class="fs-4 text-center"></div>
                                    <?= Sessao::alert('OK'); ?>
                                    <?= Sessao::alert('ERRO'); ?>
                                </section>
                                <div class="col-12 mx-auto row mb-2">
                                <?php if($_SESSION['USU_NIVEL'] >= 11){ ?>
                                    <div id="CLI" class="col-5 mx-auto form-floating mb-3">
                                        <div class="input-group input-group-lg">
                                            <div class="form-floating">
                                                <select id="cliente" class="form-select" name="CLI_COD"> 
                                                <option value="0" <?= (isset($_POST['CLI_COD']) &&  $_POST['CLI_COD']  == 0)? 'selected' : '' ?>>CONSUMIDOR FINAL</option>
                                                <?php for ($i=0; $i < $qtdClientes; $i++) { ?>
                                                    <option value="<?= $clientes[$i]['CLI_COD'] ?>" <?= (isset($_POST['CLI_COD']) &&  $_POST['CLI_COD']  == $i)? 'selected' : '' ?>><?= $clientes[$i]['CLI_NOME'] ?></option>
                                                <?php } ?>
                                                </select>
                                                <label class="form-label">CLIENTE</label>
                                            </div>
                                            <button type="button" class="btn <?= $modulo[0]['MOD_COR'] ?>" data-bs-toggle="modal" data-bs-target="#novo_cliente" ><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                    <div id="CXA" class="col-3 mx-auto form-floating mb-3">
                                        <select id="cliente" class="form-select" name="CXA_COD">
                                            <?php for ($i=0; $i < $qtdCA; $i++) { ?>
                                                <option value="<?= $caixas[$i]['CXA_COD'] ?>" <?= (isset($_POST['CXA_COD']) &&  $_POST['CXA_COD']  == $i)? 'selected' : '' ?>><?= $caixas[$i]['CXA_DESCRICAO'] ?></option>
                                            <?php } ?>
                                        </select>
                                        <label class="form-label">CAIXA</label>
                                    </div>
                                    <div id="FPG" class="col-4 mx-auto form-floating mb-3">
                                        <select  class="form-select" name="FPG_COD"> 
                                        <?php for ($i=0; $i < $qtdF; $i++) { if ($formas_pagamentos[$i]['FPG_STATUS'] == 1) { ?>
                                            <option value="<?= $i ?>" <?= (isset($_POST['FPG_COD']) &&  $_POST['FPG_COD']  == $i)? 'selected' : '' ?>><?= ($formas_pagamentos[$i]['FPG_TIPO'] == 1)? 'À VISTA' : 'À PRAZO'; ?> - <?= $formas_pagamentos[$i]['FPG_DESCRICAO'] ?></option>
                                        <?php } } ?>
                                        </select>
                                        <label class="form-label">FORMA DE PAGAMENTO</label>
                                    </div>
                                    <div class="col-12 mx-auto form-floating mb-2">
                                        <table id="table"  class="table table-bordered">
                                            <thead>
                                                <tr class="text-center <?= $modulo[0]['MOD_COR'] ?>"><th colspan="6" class="text-white">ITENS</th></tr>
                                                <tr class="text-center">
                                                    <th>#</th>
                                                    <th>DESCRIÇÃO</th>
                                                    <th>QTD</th>
                                                    <th>VALOR UNIT.</th>
                                                    <th>SUB TOTAL</th>
                                                    <th>AÇÃO</th>
                                                </tr>
                                            </thead>
                                            <tbody id="itens" class="text-center"></tbody>
                                            <tfooter id="total" class="text-center">
                                                <tr id="INFO" class="">
                                                    <td></td>
                                                    <td class="text-center">
                                                        <label class="form-label">QTD ITENS</label>
                                                        <input type="text" id="QTD" class="form-control text-center" name='QTD' value="0">
                                                    </td>
                                                    <td colspan="2" class="text-center">
                                                        <label class="form-label">SUBTOTAL</label>
                                                        <input type="text" id="VEN_VALOR_SUBTOTAL" class="form-control text-center" name='VEN_VALOR_SUBTOTAL' value="0.00">
                                                    </td>
                                                    <td class="text-center">
                                                        <label class="form-label">DESCONTO %</label>
                                                        <input type="number" id="PRO_DESCONTO" class="form-control text-center" min="0" maxn="100" value="0">
                                                        <input type="text" id="VEN_VALOR_DESCONTO" class="form-control text-center hidden" name='VEN_VALOR_DESCONTO' value="0">
                                                    </td>
                                                    <td colspan="2" class="text-center bg-1">
                                                        <label class="form-label fw-bold">TOTAL</label>
                                                        <input type="text" id="VEN_VALOR_TOTAL" class="form-control text-center" name='VEN_VALOR_TOTAL' value="0">
                                                    </td>
                                                </tr>
                                            </tfooter>
                                        </table>
                                    </div>
                                <?php } ?>
                                    <div class="col-12 mx-auto form-floating mb-4">
                                        <label for="address2" class="form-label">DESCRIÇÃO/OBS.</label>
                                        <textarea type="text" style="height:100px;" class="form-control  maiusculo" name="MOV_DESCRICAO"><?= isset($_POST['MOV_DESCRICAO'])? $_POST['MOV_DESCRICAO']  : '' ?></textarea>
                                    </div>
                                </div>
                                <div class="col-12 row mx-auto mt-1">
                                    <input type="hidden" class="form-control" id="EST_COD" name="EST_COD" value="">
                                    <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                    <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                    <a class="col-6 btn btn-lg text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-ban"></i> Cancelar</a>
                                    <button class="col-6 btn btn-lg text-uppercase <?= $modulo[0]['MOD_COR'] ?>" name="CADASTRAR_NOVA_MOVIMENTACAO_ESTOQUE" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                                </div>
                            </div>
                        </form>
                    </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            
            <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
            <div class="modal fade" id="novo_cliente" tabindex="-1" aria-labelledby="novo_cliente" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title text-center mx-auto fs-5" id="novo_cliente">NOVO CLIENTE</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form class="p-1 border text-uppercase rounded-3 " id="formulario_novo_cliente">
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-5 form-floating mb-2">
                                        <select class="form-select" name="CLI_TIPO">
                                            <option value="0" <?= (isset($_POST['CLI_TIPO']) &&  $_POST['CLI_TIPO']  == "0")? 'selected' : '' ?>>---</option>
                                            <option value="PF"<?= (isset($_POST['CLI_TIPO']) &&  $_POST['CLI_TIPO']  == "PF")? 'selected' : '' ?>>PESSOA FÍSICA</option>
                                            <option value="PJ" <?= (isset($_POST['CLI_TIPO']) &&  $_POST['CLI_TIPO']  == "PJ")? 'selected' : '' ?>>PESSOA JURÍDICA</option>
                                        </select>
                                        <label class="form-label">TIPO</label>
                                    </div>
                                    <div class="col-7 form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="1" name="CLI_NOME" placeholder="Informe seu nome" value="<?= isset($_POST['CLI_NOME']) ? $_POST['CLI_NOME'] :''; ?>">
                                        <label class="form-label" for="1">NOME(*)</label>
                                    </div>    
                                    <div class="col-12 form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="2" name="CLI_SOBRENOME" placeholder="Informe seu nome" value="<?= isset($_POST['CLI_SOBRENOME']) ? $_POST['CLI_SOBRENOME'] : ''; ?>">
                                        <label class="form-label" for="2">SOBRENOME(*)</label>
                                    </div> 
                                    <div class="col-12 mb-2">
                                        <div class="form-floating mb-3">
                                            <input type="text" id="FOR_TEL_1" name="CLI_TEL_1" onkeyup="handlePhone(event)" class="form-control form-control-lg" value="<?= isset($_POST['CLI_TEL_1']) ? $_POST['CLI_TEL_1'] : '' ?>">
                                            <label class="form-label">TEL./CEL. 1 (WHATSAPP) (opcional)</label>
                                        </div>
                                    </div>
                                   
                                    <div class="col-12 mb-3">
                                        <div class="form-floating mb-3">
                                            <input type="text" name="CLI_REGISTRO" onfocus="javascript: retirarFormatacao(this);" onblur="javascript: formatarCampo(this);" maxlength="14" class="form-control" value="<?= isset($_POST['CLI_REGISTRO']) ? $_POST['CLI_REGISTRO'] : '' ?>">
                                            <label for="registro">CPF/CNPJ(*)</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer mx-auto">
                                <button type="button" class="btn btn-lg text-uppercase  btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="CADASTRAR_NOVO_CLIENTE" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="btn btn-lg text-uppercase btn-success" id="btn_cadastrar_cliente"  type="submit" name=""><i class="fa fa-save"></i> Cadastrar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
        var keyStop = {
                8: ":not(input:text, textarea, input:file, input:password)", // stop backspace = back
                13: "input:text, input:password", // stop enter = submit 

                end: null
            };
            $(document).bind("keydown", function(event){
                var selector = keyStop[event.which];

                if(selector !== undefined && $(event.target).is(selector)) {
                    event.preventDefault(); //stop event
                }
                return true;
            });
        });

        const tipo = document.querySelector("#tipo");
        
        tipo.addEventListener("change", function() {
        
            var checar = tipo.value;
            
            if (checar == 1) {
               // $('#SAIDA').addClass('hidden');
                //$('#SAIDA').addClass('disable');
                //$('#ENTRADA').removeClass('hidden');
                $('#CLI').addClass('hidden');
                $('#CXA').addClass('hidden');
                $('#FPG').addClass('hidden');
                $('#INFO').addClass('hidden');
               // $('#SAIDA').hide();
                //$("#ENTRADA").show();
            } else {
                //$('#SAIDA').removeClass('hidden');
                //$('#ENTRADA').addClass('hidden');
                //$('#ENTRADA').addClass('disable');
                $('#CLI').removeClass('hidden');
                $('#CXA').removeClass('hidden');
                $('#FPG').removeClass('hidden');
                $('#INFO').removeClass('hidden');
               // $('#ENTRADA').hide();
               // $("#SAIDA").show();
            }
        });
       

        <?php $op = ($qtdEstoque == 1)? 'ready' : 'change'; ?> 
        $("#buscar_produtos").<?= $op ?>(function(){
            var EST_COD = $(this).find('option:selected').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;
            carregarProdutos(EST_COD, EMP_COD,"#produtos");
        });
        
        function carregarProdutos(EST_COD, EMP_COD,selecionado="#produtos"){
            $.post('<?= DIRPAGE; ?>movimentacoes/listar_produtos', {PRODUTOS_ESTOQUE: true,EMP_COD: EMP_COD,EST_COD:EST_COD,cache: false}, function(retorno) {
                
                dados = JSON.parse(retorno);
                
                $(selecionado).find('option').remove().end();
                $(selecionado).append($('<option>', {
                    value: 0,
                    text: '---'
                }));
                //console.log(dados);
                document.getElementById("EST_COD").value ='';
                document.getElementById("EST_COD").value = EST_COD;

                for(var i=0;dados.length>i;i++){
                    if(dados[i].PRO_STATUS == 1){
                        $(selecionado).append($('<option>', {
                            value: dados[i].PRO_COD,
                            text: 'CÓDIGO: '+dados[i].PRO_CODIGO+' - '+dados[i].PRO_NOME
                        }));
                    }
                    //console.log(dados[i].PRO_NOME);
                    //console.log(codificarHtml(dados[i].PRO_NOME));
                }
                function codificarHtml(texto){
                    var htmlCodigo = { 
                                '&aacute;' : {'code' : 'á'},
                                '&Aacute;' : {'code' : 'Á'},
                                '&atilde;' : {'code' : 'ã'},
                                '&Atilde;' : {'code' : 'Ã'},
                                '&agrave;' : {'code' : 'à'},
                                '&Agrave;' : {'code' : 'À'},                       
                                '&eacute;' : {'code' : 'é'},
                                '&Eacute;' : {'code' : 'É'},
                                '&iacute;' : {'code' : 'í'},
                                '&Iacute;' : {'code' : 'Í'},
                                '&oacute;' : {'code' : 'ó'},
                                '&Oacute;' : {'code ': 'Ó'}, 
                                '&otilde;' : {'code' : 'õ'},
                                '&Otilde;' : {'code' : 'Õ'},
                                '&uacute;' : {'code' : 'ú'},
                                '&Uacute;' : {'code' : 'Ú'},
                                '&ccedil;' : {'code' : 'ç'},
                                '&Ccedil;' : {'code' : 'Ç'}                      };
                    var acentos = ['á', 'Á', 'ã', 'Ã', 'à', 'À', 'é', 'É', 'í', 'Í', 'ó', 'Ó', 'õ', 'Õ', 'ú', 'Ú', 'ç', 'Ç'];
                    
                    for(var i=0; i<acentos.length; i++){
                        if(htmlCodigo [acentos[i]] != undefined){
                            texto = texto.replaceAll(acentos[i], htmlCodigo[acentos[i]].code );
                        }
                    }
                    return texto;
                }
    
            });
        }
        

        $("#produtos").change(function(){

            var PRO_COD = $(this).find('option:selected').val();
            var EST_COD = $('#EST_COD').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;
            
            $.post('<?= DIRPAGE; ?>movimentacoes/listar_produto', {PRODUTOS: true,EMP_COD: EMP_COD,EST_COD:EST_COD,PRO_COD: PRO_COD}, function(retorno) {
                var db = JSON.parse(retorno);
                $('#PRO_QUANTIDADE').html(db.PRO_QUANTIDADE);
            });
        });
        

        $("#adicionar").click(function(e){
            e.preventDefault();
            var PRO_COD2 = $("#produtos").find('option:selected').val();
            var EMP_COD2 = <?php echo $_SESSION['EMP_COD']; ?>;
            var EST_COD2 = $('#EST_COD').val();
           
            $("#itens").hide();
            $.post('<?= DIRPAGE; ?>movimentacoes/listar_produto', {PRODUTOS: true,EMP_COD: EMP_COD2,EST_COD:EST_COD2,PRO_COD: PRO_COD2}, function(retorno2) {
                resposta = JSON.parse(retorno2);
                //$("#total").val(0);
                $("#itens").show();
                addCampos2(resposta);
                $("#total").hide();
            });
        });
        var subtotal = 0;
        var qtdeCampos = <?= $contagem; ?>;
        var quantidade = 0;
        function addCampos2(resposta) {
            var objPai = document.getElementById("itens");
            //Criando o elemento DIV;
            var objFilho = document.createElement("tr");
            //Definindo atributos ao objFilho:
            objFilho.setAttribute("id", "filho" + qtdeCampos);
          
            //Inserindo o elemento no pai:
            objPai.appendChild(objFilho);
            //Escrevendo algo no filho recém-criado:
            var quantidade = Number(document.getElementById('QTD').value);
            document.getElementById('QTD').value = '';
            
            var MOV_QUANTIDADE = Number(document.getElementById('MOV_QUANTIDADE').value);
            //console.log(MOV_QUANTIDADE);
            objFilho.setAttribute("data-quantidade",MOV_QUANTIDADE);

            if (MOV_QUANTIDADE >= 1) {

                var subtotal = 0;
                subtotal = (resposta.PRO_PRECO_VENDA*MOV_QUANTIDADE).toFixed(2);
                document.getElementById('QTD').value = Number(quantidade + MOV_QUANTIDADE);
                objFilho.setAttribute("data-subtotal",subtotal);

                var n1 = Number(document.getElementById('VEN_VALOR_SUBTOTAL').value);
                var n2 = Number(subtotal);
                document.getElementById('VEN_VALOR_SUBTOTAL').value = (n1 + n2).toFixed(2);   

                document.getElementById("filho" + qtdeCampos).innerHTML = "<td class='align-middle mx-auto'>" + qtdeCampos + "</td>"+
                "<td class='align-middle mx-auto'>"+resposta.PRO_NOME+"</td>"+
                "<td class='align-middle mx-auto'>"+MOV_QUANTIDADE+"</td>"+
                "<td class='align-middle mx-auto'>"+resposta.PRO_PRECO_VENDA+"</td>"+
                "<td class='align-middle mx-auto'>"+subtotal+"</td>"+
                "<td class='align-middle mx-auto'><input type='hidden' id='mov" + qtdeCampos + "' name='MOV_QUANTIDADE[]' value='" + MOV_QUANTIDADE + "'></input>"+
                "<input type='hidden' id='campo" + qtdeCampos + "' name='PRO_COD[]' value='" + resposta.PRO_COD + "'></input>"+
                "<input type='hidden' id='preco" + qtdeCampos + "' name='PRO_PRECO_VENDA[]' value='" + resposta.PRO_PRECO_VENDA + "'></input>"+
                "<button type='button' class='col btn btn-danger' title='APAGAR DA LISTA' onClick='removerCampo(" + qtdeCampos + ")' value=''><i class='fa fa-trash'></i></button></td>";
                
                var PRO_DESCONTO =  $("#PRO_DESCONTO").val();
                if(PRO_DESCONTO !=="" || PRO_DESCONTO !== null){
                    
                    PRO_DESCONTO = parseFloat(PRO_DESCONTO/100);
                    var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                    VEN_VL_SUBTOTAL = parseFloat(VEN_VL_SUBTOTAL);
                    var novo = parseFloat(VEN_VL_SUBTOTAL - (VEN_VL_SUBTOTAL * PRO_DESCONTO)).toFixed(2);
                    $("#VEN_VALOR_TOTAL").val('');
                    $("#VEN_VALOR_TOTAL").val(novo); 
                    $("#VEN_VALOR_DESCONTO").val('');
                    var desconto = (VEN_VL_SUBTOTAL * PRO_DESCONTO);
                    $("#VEN_VALOR_DESCONTO").val(desconto); 
                }else{
                    var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                    $("#VEN_VALOR_TOTAL").val(VEN_VL_SUBTOTAL); 
                    $("#VEN_VALOR_DESCONTO").val('');
                    $("#VEN_VALOR_DESCONTO").val(0);
                }

                $("#total").show();
                $("#MOV_QUANTIDADE").val('');
                qtdeCampos++;

            } else {
                $('#resposta2').addClass('alert alert-warning');
                $('#resposta2').html('INFORME A QUANTIDADE DO PRODUTO');
                setTimeout(function () {
                        $('#resposta2').hide();
                }, 3000);
                
            }
            
        }

        function removerCampo(id, qtdeCampos) {
            var objPai = document.getElementById("itens");
            var objFilho = document.getElementById("filho" + id);
            
            $("#total").hide();
            
            var qtd = objFilho.getAttribute('data-quantidade');
            var sb = objFilho.getAttribute('data-subtotal');

            var quantidade = Number(document.getElementById('QTD').value);
            document.getElementById('QTD').value = (quantidade - qtd);

            var subtotal = document.getElementById('VEN_VALOR_SUBTOTAL').value;
            document.getElementById('VEN_VALOR_SUBTOTAL').value = (subtotal - sb).toFixed(2);
            
            var PRO_DESCONTO =  $("#PRO_DESCONTO").val();
            if(PRO_DESCONTO !=="" || PRO_DESCONTO !== null){
                PRO_DESCONTO = parseFloat(PRO_DESCONTO/100);
                var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                VEN_VL_SUBTOTAL = parseFloat(VEN_VL_SUBTOTAL);
                var novo = parseFloat(VEN_VL_SUBTOTAL - (VEN_VL_SUBTOTAL * PRO_DESCONTO)).toFixed(2);
                $("#VEN_VALOR_TOTAL").val('');
                $("#VEN_VALOR_TOTAL").val(novo); 
                $("#VEN_VALOR_DESCONTO").val('');
                var desconto = (VEN_VL_SUBTOTAL * PRO_DESCONTO);
                $("#VEN_VALOR_DESCONTO").val(desconto); 
            }else{
                var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                $("#VEN_VALOR_TOTAL").val(VEN_VL_SUBTOTAL); 
                $("#VEN_VALOR_DESCONTO").val('');
                $("#VEN_VALOR_DESCONTO").val(0);
            }
            $("#total").show();

            var qtdeCampos = qtdeCampos;
            qtdeCampos--;
            //Removendo o DIV com id específico do nó-pai:
            var removido = objPai.removeChild(objFilho);
        }

        $("#PRO_DESCONTO").change(function(){
            var PRO_DESCONTO =  $(this).val();
            if(PRO_DESCONTO !=="" || PRO_DESCONTO !== null){
                PRO_DESCONTO = parseFloat(PRO_DESCONTO/100);
                var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                VEN_VL_SUBTOTAL = parseFloat(VEN_VL_SUBTOTAL);
                var novo = parseFloat(VEN_VL_SUBTOTAL - (VEN_VL_SUBTOTAL * PRO_DESCONTO)).toFixed(2);
                $("#VEN_VALOR_TOTAL").val('');
                $("#VEN_VALOR_TOTAL").val(novo); 
                $("#VEN_VALOR_DESCONTO").val('');
                var desconto = (VEN_VL_SUBTOTAL * PRO_DESCONTO);
                $("#VEN_VALOR_DESCONTO").val(desconto); 
            }else{
                var VEN_VL_SUBTOTAL = $("#VEN_VALOR_SUBTOTAL").val();
                $("#VEN_VALOR_TOTAL").val(VEN_VL_SUBTOTAL); 
                $("#VEN_VALOR_DESCONTO").val('');
                $("#VEN_VALOR_DESCONTO").val(0);
            }
        });
    </script>
    <script type="text/javascript">
        const novo_cliente = new bootstrap.Modal(document.getElementById("novo_cliente"));
        const formulario_novo_cliente = document.getElementById("formulario_novo_cliente");
        const btn_cadastrar_cliente = document.getElementById("btn_cadastrar_cliente");
        if (formulario_novo_cliente) {
            formulario_novo_cliente.addEventListener("submit", async (e)=> {
                e.preventDefault();
                
                const dadosForm = new FormData(formulario_novo_cliente);

               
                btn_cadastrar_cliente.innerText="Salvando...";

                const dados = await fetch("<?= DIRPAGE; ?>clientes/cadastro_simples",{
                    method:"POST",
                    body: dadosForm
                });
                const resp = await dados.json();
               // console.log(resp);

                if (resp['COD'] !== 'ERRO') {
                    
                    $('#resposta3').addClass('alert alert-success');

                    btn_cadastrar_cliente.innerText="Cadastrar";

                    const pai = document.getElementById("cliente");
                    //Criando o elemento DIV;
                    const cliente = document.createElement("option");

                    cliente.text = resp['CLI_NOME'];
                    cliente.value = resp['CLI_COD'];
                    cliente.setAttribute("selected","select");
                    pai.appendChild(cliente);

                    formulario_novo_cliente.reset();
                }else{
                    $('#resposta3').addClass('alert alert-warning');
                }

                setTimeout(function () {
                     $('#novo_cliente').modal('hide');
                }, 1100);

                $('#resposta3').html(resp['MENSAGEM']);

                setTimeout(function () {
                        $('#resposta3').hide();
                }, 900);
              
            });
        }
    </script>
     <script>
        function formatarCampo(campoTexto) {
        if (campoTexto.value.length <= 11) {
            campoTexto.value = mascaraCpf(campoTexto.value);
        } else {
            campoTexto.value = mascaraCnpj(campoTexto.value);
        }
        }
        function retirarFormatacao(campoTexto) {
            campoTexto.value = campoTexto.value.replace(/(\.|\/|\-)/g,"");
        }
        function mascaraCpf(valor) {
            return valor.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/g,"\$1.\$2.\$3\-\$4");
        }
        function mascaraCnpj(valor) {
            return valor.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/g,"\$1.\$2.\$3\/\$4\-\$5");
        }

      //  $(document).ready(function() {
            //$('#produtos').select2();
            //$('#produtos').defaults.reset();
      //  });
    </script>
</body>

</html>    
