<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($cargos_salarios) ? count($cargos_salarios) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>cargos_salarios">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="fa fa-handshake"></i> Gerenciar <span class="text-success">Seus Cargos e Salários</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light text-dark">
                <div class="container mx-auto col-12 px-2 py-2 row ">
                    <div class="card bg-success mx-auto text-center col-12 py-1 mb-2">
                        <div class="card-body text-white">
                            <h5 class="card-title">CARGOS E SALÁRIOS</h5>
                            <p class="card-text">Cadastre seus cargos e salários</p>
                            <a href="<?= DIRPAGE ?>cargos_salarios/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>
                    <?php
                    if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">TIPO</th>
                            <th class="text-dark">NÍVEL</th>
                            <th class="text-dark">GARGO</th>
                            <th class="text-dark">SALÁRIO</th>
                            <th class="text-dark">COMISSÃO</th>
                            <th class="text-dark">STATUS</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">AÇÕES</th><?php } ?> 
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) { ?>
                            <tr class="<?= ($cargos_salarios[$i]['CGS_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= ($cargos_salarios[$i]['CGS_TIPO'] != '0')? (($cargos_salarios[$i]['CGS_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?></td>
                                <td class="text-center align-middle"><?= $cargos_salarios[$i]['CGS_NIVEL']; ?></td>
                                <td class="text-center align-middle"><?= $cargos_salarios[$i]['CGS_NOME']; ?></td>
                                <td class="text-center align-middle"><?= number_format($cargos_salarios[$i]['CGS_SALARIO'],2,',','.'); ?></td>
                                <td class="text-center align-middle"><?= $cargos_salarios[$i]['CGS_COMISSAO']; ?>%</td>
                                <td class="text-center align-middle"><?= ($cargos_salarios[$i]['CGS_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                    <td class="text-center align-middle">
                                        <?php if($cargos_salarios[$i]['CGS_STATUS'] == 0){ ?>
                                        <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $cargos_salarios[$i]['CGS_COD']; ?>" data-nome="<?= $cargos_salarios[$i]['CGS_NOME']; ?>"  data-status="<?= $cargos_salarios[$i]['CGS_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-circle-check"></i></button>
                                        <?php }else { ?>
                                        <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'cargos_salarios/alteracao/'.$cargos_salarios[$i]['EMP_COD'].'/'.$cargos_salarios[$i]['CGS_COD']; ?>" title="Deseja Alterar?"><i class="fa fa-edit"></i></a>
                                        <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Desativar cargo" data-codigo="<?= $cargos_salarios[$i]['CGS_COD']; ?>" data-nome="<?= $cargos_salarios[$i]['CGS_NOME']; ?>" data-status="<?= $cargos_salarios[$i]['CGS_STATUS']; ?>"  title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                        <?php } ?> 
                                    </td>
                                <?php } ?> 
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM GARGO/SALÁRIO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="CGS_STATUS" name="CGS_STATUS" value="" />
                    <input type="hidden" id="CODIGO" name="CGS_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#CODIGO').val(codigo);
                modal.find('#CGS_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#NOME').html(nome);
                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Cargo/Salário?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Cargo/Salário?');
                }
            });
        });
        $("#sts").click(function(){
            var CGS_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var CGS_STATUS = $('#CGS_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>cargos_salarios/status', {CGS_COD: CGS_COD,STATUS_CARGO: true,EMP_COD: EMP_COD,CGS_STATUS: CGS_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>cargos_salarios"}, 100);
            });

        });
    </script>
</body>
</html>