<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtdEmpresas = (is_array($empresas) ? count($empresas) : 0);
?>
<body>
    <div class="d-flex" id="wrapper">
    <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 row col-xl-9 col-xxl-9">
                                <img src="<?= DIRIMG ?>lctec2.png" class="col-4 img-fluid" style="width: 150px; height: auto;" alt="..."> 
                                <div class="col-8 my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> Painel <span class="text-success">LC/TEC</span>
                                        </h5>
                                    </a>
                                    <div class="col-12 my-1 px-4 mx-auto">
                                        <a type="button" class="btn btn-sm btn-success"  href="<?= DIRPAGE; ?>tarefas" title="Nova Tarefa"><i class="bi bi-bookmarks"></i> + TAREFA</a>
                                        <a type="button" class="btn btn-sm btn-dark"  href="<?= DIRPAGE; ?>avisos" title="Novo Aviso"><i class="bi bi-bell"></i> + AVISO</a>
                                    </div>
                                </div>
                            </div>
                           
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                        <hr>
                    </section>
                    <section class="container col-12 mx-auto px-3">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-8 col-md-6 col-lg-6 mx-auto m-1">
                            <div class="col-12 row text-center text-lg-start opacity-50">
                                <h2 class="fs-5 col-12 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                                <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p></h2>
                            </div>
                            <div class="col-12 row mx-auto">
                                <ul class="list-group">
                                    <li class="list-group-item bg-success  text-center text-white" aria-current="true">EMPRESAS ATIVAS</li>
                                    <?php for ($i=0; $i < $qtdEmpresas; $i++) {  $data = new DateTime($empresas[$i]['EMP_DT_FUNDACAO']); ?>
                                        <a href="<?= DIRPAGE ?>lctec/empresas/<?= $empresas[$i]['EMP_COD'] ?>" class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 text-center justify-content-between">
                                                <h5 class="mb-1 text-center "><?= $empresas[$i]['EMP_NOME_FANTASIA'] ?></h5>
                                                <small class="text-body-secondary"><?= $data->format('d/m/Y'); ?></small>
                                            </div>
                                            <p class="mb-1">
                                                <?= $empresas[$i]['EMP_REGULAMENTACAO'] ?>
                                                <small class="text-body-secondary"><?= ($empresas[$i]['EMP_STATUS'] == 1)? '<span class="badge bg-success">ATIVADA</span>' : 'DESATIVADA'; ?></small>
                                            </p>
                                        </a>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                        <div class="row col-4 col-md-6 col-lg-6 mx-auto">
                            <?php include_once 'app/Views/admin/inc/calendario.phtml'; ?> 
                        </div>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>