<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
?>
<body>
    <div class="d-flex" id="wrapper">
    <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> Painel <span class="text-success">LC/TEC</span>
                                        </h5>
                                    </a>
                                    <div class="col-12 my-1 px-4 mx-auto">
                                        <a type="button" class="btn btn-sm btn-success"  href="<?= DIRPAGE; ?>tarefas" title="Nova Tarefa"><i class="bi bi-bookmarks"></i> + TAREFA</a>
                                        <a type="button" class="btn btn-sm btn-dark"  href="<?= DIRPAGE; ?>avisos" title="Novo Aviso"><i class="bi bi-bell"></i> + AVISO</a>
                                    </div>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-3">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-8 col-md-6 col-lg-6 mx-auto m-1">
                            <div class="col-12 row text-center text-lg-start opacity-50">
                                <h2 class="fs-5 col-12 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                                <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p></h2>
                            </div>
                        
                        </div>
                        <div class="row col-4 col-md-6 col-lg-6 mx-auto">
                            <?php include_once 'app/Views/admin/inc/calendario.phtml'; ?> 
                        </div>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>