<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
//dump($estoques);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>cadastros/estoques">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Estoques</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light text-dark">
                <div class="container mx-auto col-12 px-2 py-2 row ">
                    <div class="card bg-success mx-auto text-center col-12 py-2 mb-2">
                        <div class="card-body text-white">
                            <h5 class="card-title">ESTOQUES</h5>
                            <p class="card-text">Cadastre/Altere os dados dos seus estoques</p>
                            <a href="<?= DIRPAGE ?>cadastros/cadastro_estoques" class="btn btn-dark">NOVO ESTOQUE</a>
                        </div>
                    </div>
                    <?php
                    if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Nome</th>
                            <th class="text-dark">Empresa</th>
                            <th class="text-dark">Criação</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Setor</th>
                            <th class="text-dark">Classificação</th>
                            <th class="text-dark">Status</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) { $data = new DateTime($estoques[$i]['EST_DT_CADASTRO']);?>
                            <tr class="<?= ($estoques[$i]['EST_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $estoques[$i]['EST_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $estoques[$i]['EMP_NOME_FANTASIA']; ?></td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <td class="text-center align-middle"><?= $estoques[$i]['EST_TIPO']; ?></td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($estoques[$i]['SET_COD'] != 0 $estoques[$i]['SET_COD'] != '') {
                                        for ($c = 0; $c < $qtdS; $c++) { 
                                            if ($setores[$c]['SET_COD'] == $estoques[$i]['SET_COD']) { ?>
                                            <?= $setores[$c]['SET_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($estoques[$i]['CLA_COD'] != 0 or $estoques[$i]['CLA_COD'] != '') {
                                        for ($c = 0; $c < $qtdCL; $c++) { 
                                            if ($classificacoes[$c]['CLA_COD'] == $estoques[$i]['CLA_COD']) { ?>
                                            <?= $classificacoes[$c]['CLA_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle"><?= ($estoques[$i]['EST_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                <td class="text-center align-middle">
                                    <?php if($estoques[$i]['EST_STATUS'] == 0){ ?>
                                        <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $estoques[$i]['EST_COD']; ?>" data-nome="<?= $estoques[$i]['EST_DESCRICAO']; ?>" data-status="<?= $estoques[$i]['EST_STATUS']; ?>"  title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                    <?php }else { ?>
                                    <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'cadastros/alteracao_estoques/'.$estoques[$i]['EMP_COD'].'/'.$estoques[$i]['EST_COD']; ?>" title="Alterar estoque da empresa"><i class="fa fa-edit"></i></a>
                                    <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $estoques[$i]['EST_COD']; ?>" data-nome="<?= $estoques[$i]['EST_DESCRICAO']; ?>"  data-status="<?= $estoques[$i]['EST_STATUS']; ?>"  title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                    <?php } ?>
                                </td>
                                <?php } ?>
                            </tr>
                        <?php $b++; } ?> 
                        </tbody>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM  NENHUM ESTOQUE CRIADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="EST_DESCRICAO" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="EST_COD" name="EST_COD" value="" />
                    <input type="hidden" id="EST_STATUS" name="EST_STATUS" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""><i class="fa fa-ban"></i> CONFIRMAR</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#EST_COD').val(codigo);
                modal.find('#EST_STATUS').val(status);
                modal.find('#EST_DESCRICAO').html(nome);
                modal.find('#sts').val(codigo);
                
                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Estoque?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Estoque?');
                }
            });
        });
        $("#sts").click(function(){
            var EST_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var EST_STATUS = $('#EST_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>estoques/status', {EST_COD: EST_COD,STATUS_ESTOQUE: true,EMP_COD: EMP_COD,EST_STATUS:EST_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>estoques"}, 100);
            });

        });
    </script>
</body>
</html>