<?php 
use Libraries\Sessao;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtdME = (is_array($modulos) ? count($modulos) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
$qtdU = (is_array($usuarios) ? count($usuarios) : 0);

?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec/usuarios">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">USUÁRIOS DAS EMPRESAS</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <hr>

                    <div class="row col-12 mx-auto m-1">
                        <?php 
                        //dump($usuarios);
                        if ($qtdU == 0) {
                            for ($i=0; $i < $qtdE; $i++) {  
                            $data = new DateTime($empresas[$i]['EMP_DT_FUNDACAO']); ?>
                            <a href="<?= DIRPAGE ?>lctec/usuarios/<?= $empresas[$i]['EMP_COD'] ?>" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 text-center justify-content-between">
                                    <h5 class="mb-1 text-center "><?= $empresas[$i]['EMP_NOME_FANTASIA'] ?></h5>
                                    <small class="text-body-secondary"><?= $data->format('d/m/Y'); ?></small>
                                </div>
                                <p class="mb-1">
                                    <?= $empresas[$i]['EMP_REGULAMENTACAO'] ?>
                                    <small class="text-body-secondary"><?= ($empresas[$i]['EMP_STATUS'] == 1)? '<span class="badge bg-success">ATIVADA</span>' : 'DESATIVADA'; ?></small>
                                </p>
                            </a>
                        <?php } 
                        }else{ for ($i=0; $i < $qtdU; $i++) {   ?>
                        

                        <?php } } ?>
                    </div>

                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                     
                </script>
            </div>
        </div>
    </div>
</body>
</html>