<?php 
use Libraries\Sessao;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtdME = (is_array($modulos) ? count($modulos) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
$qtdU = (is_array($usuarios) ? count($usuarios) : 0);

?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec/usuarios">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">USUÁRIOS DAS EMPRESAS</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <hr>

                    <div class="row col-12 mx-auto m-1">
                        <?php 
                        //dump($usuarios);
                        if ($qtdU == 0) {
                            for ($i=0; $i < $qtdE; $i++) {  
                            $data = new DateTime($empresas[$i]['EMP_DT_FUNDACAO']); ?>
                            <a href="<?= DIRPAGE ?>lctec/usuarios/<?= $empresas[$i]['EMP_COD'] ?>" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 text-center justify-content-between">
                                    <h5 class="mb-1 text-center "><?= $empresas[$i]['EMP_NOME_FANTASIA'] ?></h5>
                                    <small class="text-body-secondary"><?= $data->format('d/m/Y'); ?></small>
                                </div>
                                <p class="mb-1">
                                    <?= $empresas[$i]['EMP_REGULAMENTACAO'] ?>
                                    <small class="text-body-secondary"><?= ($empresas[$i]['EMP_STATUS'] == 1)? '<span class="badge bg-success">ATIVADA</span>' : 'DESATIVADA'; ?></small>
                                </p>
                            </a>
                        <?php } 
                        }else{ $b = 1; for ($i=0; $i < $qtdU; $i++) {   ?>
                         <table class="table table-striped table-bordered">
                            <thead class="text-center text-uppercase">
                                <th class="text-dark">#</th>
                                <th class="text-dark">Nome</th>
                                <th class="text-dark">Email</th>
                                <th class="text-dark">Nível</th>
                                <th class="text-dark">Status</th>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                            </thead>
                            <tbody>
                            <?php
                                $b = 1;
                                for ($i= 0; $i < $qtd; $i++) { ?>
                                <tr class="<?= ($usuarios[$i]['USU_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                    <td class="text-center align-middle"><?= $b; ?></td>
                                    <td class="text-center align-middle"><?= $usuarios[$i]['USU_NOME'].' '.$usuarios[$i]['USU_SOBRENOME']; ?></td>
                                    <td class="text-center align-middle"><?= $usuarios[$i]['USU_EMAIL']; ?></td>
                                    <td class="text-center align-middle"><?= $usuarios[$i]['USU_NIVEL']; ?></td>
                                    <td class="text-center align-middle"><?= ($usuarios[$i]['USU_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                    <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                    <td class="text-center align-middle">
                                        <?php if($usuarios[$i]['USU_STATUS'] == 0){ ?>
                                            <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $usuarios[$i]['USU_COD']; ?>" data-nome="<?= $usuarios[$i]['USU_NOME']; ?>" data-status="<?= $usuarios[$i]['USU_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                        <?php }else { ?>
                                            <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'usuarios/alteracao/'.$usuarios[$i]['EMP_COD'].'/'.$usuarios[$i]['USU_COD']; ?>" title="Alterar usuário"><i class="fa fa-edit"></i></a>
                                            <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $usuarios[$i]['USU_COD']; ?>" data-nome="<?= $usuarios[$i]['USU_NOME']; ?>" data-status="<?= $usuarios[$i]['USU_STATUS']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                        <?php } ?>
                                    </td>
                                    <?php } ?>
                                </tr>
                            <?php $b++; } ?>
                            </tbody>
                        </table>
                        <?php } } ?>
                    </div>

                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                     
                </script>
            </div>
        </div>
    </div>
</body>
</html>