<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($avisos) ? count($avisos) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>avisos">
                                    <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Avisos</span></h5>
                                </a>
                                <div class="col-12 my-1 px-4 mx-auto">
                                    <a type="button" class="btn btn-sm btn-dark"  href="<?= DIRPAGE; ?>avisos" title="Novo Aviso"><i class="bi bi-bell"></i> + AVISOS</a>
                                </div>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
            <?php if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">TIPO</th>
                            <th class="text-dark">DESCRIÇÃO</th>
                            <th class="text-dark">STATUS</th>
                            <th class="text-dark">Ações</th>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) {  ?>
                            <tr class="<?= ($avisos[$i]['AVS_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle">
                                    <?= $b.' '; ?>
                                </td>
                                <td class="text-center align-middle"><?= $avisos[$i]['AVS_TIPO']; ?></td>
                                <td class="text-center align-middle"><?= $avisos[$i]['AVS_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= ($avisos[$i]['AVS_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
                                    <div class="form-check mx-auto">
                                        <input class="form-check-input" type="checkbox" id="AVS_COD" value="<?= $avisos[$i]['AVS_COD']; ?>" data-status="<?= $avisos[$i]['AVS_STATUS']; ?>" title="Marcar como lido?">
                                    </div>
                                    
                                </td>
                            </tr>
                            <?php $b++; } ?>
                        </tbody>
                    </table>
                <?php }else { ?>
                        <h4 class="text-center text-success fs-4">NENHUM AVISO CADASTRADO</h4>
                    <?php } ?>
            </section>
        </div>
        <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="statusMsg" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div id="title" class="modal-header text-center text-uppercase">
                        Excluir
                    </div>
                    <div class="modal-body text-center">
                        <p class="text-center text-uppercase mx-auto">Excluir mensagem?</p>
                    </div>
                    <div class="modal-footer">
                        <input type="hidden" id="AVS_STATUS" name="AVS_STATUS" value="" />
                        <input type="hidden" id="AVS_COD" name="AVS_COD" value="" />
                        <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= isset($avisos[0]['EMP_COD']) ? $avisos[0]['EMP_COD'] : 0; ?>" />
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                        <button id="sts" type="button" class="btn btn-dark" value=""></button>
                    </div>
                </div>
            </div>
        </div>     
        <script type="text/javascript">
                    $(document).ready(function() {
                        $('#status').on('show.bs.modal', function(event) {
                            var button = null;
                            var button = $(event.relatedTarget); // Button that triggered the modal
                            var codigo = null;
                            var codigo = button.data('codigo'); // Extract info from data-* attributes
                            var status = button.data('status');
                            var modal = $(this);
                            modal.find('#AVS_COD').val(codigo);
                            modal.find('#AVS_STATUS').val(status);
                            modal.find('#sts').val(codigo);

                            if (status === 1) {
                                modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                                modal.find('#title').html('Deseja Excluir?');
                            }else{
                                //modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                                //modal.find('#title').html('Deseja reativar o Produto?');
                            }
                        });
                    });
                    $("#sts").click(function(){
                        var AVS_COD = $('#sts').val();
                        var EMP_COD = $('#EMP_COD').val();
                        var AVS_STATUS = $('#AVS_STATUS').val();
                        setTimeout(function () {
                                $('#status').modal('hide');
                        }, 100);
                        $.post('<?= DIRPAGE; ?>avisos/excluir', {AVS_COD: AVS_COD,EXCLUIR_MENSAGEM: true,EMP_COD: EMP_COD,AVS_STATUS: AVS_STATUS}, function(retorno) {
                            var resposta = JSON.parse(retorno);
                            if (resposta['COD'] !== 'ERRO') {
                                $('#resposta').addClass('alert alert-success');
                            }else{
                                $('#resposta').addClass('alert alert-warning');
                            }
                            $('#resposta').html(resposta['MENSAGEM']);
                            setTimeout( () => { window.location.href="<?= DIRPAGE ?>avisos"}, 700);
                        });

                    });
                </script>
    </div>
</body>
</html>