<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;
session_start();
include_once 'inc/cabecalho.phtml'; 
$qtdE = (is_array($estoques) ? count($estoques) : 0);
$qtdME = (is_array($modulos_empresa) ? count($modulos_empresa) : 0);
$qtdU = (is_array($usuarios) ? count($usuarios) : 0);
$qtdP = (is_array($produtos) ? count($produtos) : 0);
$qtdMV = (is_array($movimentacoes) ? count($movimentacoes) : 0);
?><body>
    <style>
        #chart {
  max-width: 650px;
  margin: 35px auto;
}
        </style>
    <div class="d-flex" id="wrapper" style="font-family: WF Visual Sans Text,sans-serif;">
        <?php include_once 'inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation 
            #50DD98
        
        -->
            <?php include_once 'inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3" style="background-color: #40bf7b;">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="row col-lg-9 col-xl-9 col-xxl-9">
                                <div class="col-8 my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>admin/painel">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> Painel <span class="text-white">Administrativo</span>
                                        </h5>
                                    </a>
                                    <a class="text-decoration-none py-3" href="<?= DIRPAGE; ?>empresas"><span class="text-success"><?= ($_SESSION['EMP_COD'] != 0)? $empresa['EMP_NOME_FANTASIA'] : 'LC-<span class="text-success">TEC</span>'?></span></a>
                                </div>
                                <div class="col-4 mx-auto text-white">
                                    <div class="col-12 text-center text-lg-start opacity-100">
                                        <h1 class="display-5 text-center fw-bolder text-uppercase text-3 mb-1">LC-<span class="text-dark">TEC</span></h1>
                                        <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p>
                                    </div>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                        </div>
                    </section>
                     
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <?php if (isset($_SESSION['EMP_COD']) && $_SESSION['EMP_COD'] == 0) { ?>
                        <div class="row mx-auto m-4 ">
                            <div class="container col-12">
                                <div class="p-2 text-center text-white  bg-success rounded-3">
                                    <h1 class="text-emphasis opacity-75">CADASTRE A SUA EMPRESA</h1>
                                    <p class="lead fw-bold opacity-75">
                                    Para utilizar o sitema LC<span class="text-dark">-TECH</span> é necessário que você cadastre o sua <b class="text-dark">empresa/negócio</b><p> crie e utilize ao máximo dos recursos disponíveis</p></p>
                    
                                    <a href="<?= DIRPAGE ?>empresas/cadastro" class="col-auto btn btn-success text-uppercase">Clique aqui</a>
                                </div>
                            </div>
                            <!--<div class="col-4 text-center text-lg-start opacity-50">
                                <h1 class="display-5 text-center fw-bolder text-uppercase text-3 mb-2">LC-<span class="text-success">TEC</span></h1>
                                <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p>
                            </div>-->
                        </div>
                    <?php }else { ?>
                        <div class="row col-12 mx-auto m-1">
                            
                            <div class="col-12 row mx-auto">
                                <div class="col-6">
                                    <div id="chart"></div>
                                    
                                </div>
                                <?php include_once 'app/Views/admin/inc/calendario.phtml'; ?> 
                            </div>
                            <span class="text-uppercase"><?= Util::mesLowercase(date('n',$m))?>/<?= date('Y') ?></span>
                                    <hr>
                            <div class="col-12 text-uppercase display-6 row text-center mx-auto mb-3">    
                               
                                <div class="col-sm-4 rounded-2 border border-1">
                                    <div class="d-flex justify-content-center align-items-center p-4 bg-blue bg-opacity-10 rounded-3">
                                        <span class="display-6 lh-1 text-blue mb-0"><i class="fas fa-user-tie"></i></span>
                                        <div class="ms-4 h6 fw-normal mb-0">
                                            <div class="d-flex">
                                                <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="200" data-purecounter-delay="200" data-purecounter-duration="0"><?= $qtdU ?></h5>
                                                <span class="mb-0 h5">+</span>
                                            </div>
                                            <p class="mb-0">USUÁRIOS</p>
                                        </div>
                                    </div>
			                    </div>
                                <div class="col-sm-4 rounded-2 border border-1">
                                    <div class="d-flex justify-content-center align-items-center p-4 bg-blue bg-opacity-10 rounded-3">
                                        <span class="display-6 lh-1 text-blue mb-0"><i class="fas fa-user-tie"></i></span>
                                        <div class="ms-4 h6 fw-normal mb-0">
                                            <div class="d-flex">
                                                <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="200" data-purecounter-delay="200" data-purecounter-duration="0"><?= $qtdP ?></h5>
                                                <span class="mb-0 h5">+</span>
                                            </div>
                                            <p class="mb-0">PRODUTOS</p>
                                        </div>
                                    </div>
			                    </div>
                                <div class="col-sm-4 rounded-2 border border-1">
                                    <div class="d-flex justify-content-center align-items-center p-4 bg-blue bg-opacity-10 rounded-3">
                                        <span class="display-6 lh-1 text-blue mb-0"><i class="fas fa-user-tie"></i></span>
                                        <div class="ms-4 h6 fw-normal mb-0">
                                            <div class="d-flex">
                                                <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0" data-purecounter-end="200" data-purecounter-delay="200" data-purecounter-duration="0"><?= $qtdMV ?></h5>
                                                <span class="mb-0 h5">+</span>
                                            </div>
                                            <p class="mb-0">VENDAS</p>
                                        </div>
                                    </div>
			                    </div>
                            </div>
                            <hr>
                            <div class="row col-12 mt-2">
                                <?php if ($qtdME != 0) { 
                                    for ($i=0; $i < $qtdME; $i++) { ?>
                                    <?php if ($modulos_empresa[$i]['MOD_NOME'] == 'ESTOQUE') {
                                        if ($qtdE) { ?>
                                        <div class="col-4 mb-3 round-3">
                                            <div class="mx-auto rounded-2 text-<?= $modulos_empresa[$i]['MOD_COR']; ?>" >
                                                <a href="<?= DIRPAGE.$modulos_empresa[$i]['MOD_LINK']?>" class="link-light text-decoration-none">
                                                    <div class="card-header"><i class="bi bi-plus-square"></i> <?= $modulos_empresa[$i]['MOD_NOME']; ?></div>
                                                    <div class="card-body">
                                                        <h5 class="card-title text-uppercase">Módulo <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                                        <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    <?php }
                                    }else { ?>
                                    <div class="col-4 mb-3">
                                        <div class=" mx-auto rounded-2 text-<?= $modulos_empresa[$i]['MOD_COR']; ?>">
                                            <a href="<?= DIRPAGE.$modulos_empresa[$i]['MOD_LINK']?>" class="link-light text-decoration-none">
                                                <div class="card-header text-uppercase"><i class="bi bi-plus-square"></i> <?= $modulos_empresa[$i]['MOD_NOME']; ?></div>
                                                <div class="card-body">
                                                    <h5 class="card-title text-uppercase">Módulo <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                                    <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <?php } } ?>
                                    
                                    <?php } ?>
                                    <div class="col-12 mx-auto text-center mt-3">
                                        <a type="button" href="<?= DIRPAGE ?>modulo_empresa" title="Libere novos módulos para a sua empresa/negócio" class="btn text-center mt-2  btn-secondary">ATIVAR/DESATIVAR MÓDULOS</a>
                                    </div>
                                    <div class="card  mx-auto opacity-0 bg-orange m-1 py-3" style="max-width: 15rem;">
                                        <a href="#<?= DIRPAGE?>configuracoes" class="col-auto link-light text-decoration-none">
                                            <div class="card-header"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</div>
                                            <div class="card-body">
                                                <h5 class="card-title text-uppercase">Módulo configurações do sistema</h5>
                                                <p class="card-text"></p>
                                            </div>
                                        </a>
                                    </div>
                                    <hr class="my-4 text-dark">

                                    <!--
                                    <div class="opacity-25 card text-bg-warning mb-3" style="max-width: 18rem;">
                                    <div class="card-header">VENDAS</div>
                                    <div class="card-body">
                                        <h5 class="card-title">Módulo de Controle de Vendas</h5>
                                        <p class="card-text"></p>
                                    </div>
                                    </div>
                                    <div class="opacity-25 card text-bg-info mb-3" style="max-width: 18rem;">
                                    <div class="card-header">RECURSOS HUMANOS</div>
                                    <div class="card-body">
                                        <h5 class="card-title">Módulo de Recursos Humanos</h5>
                                        <p class="card-text"></p>
                                    </div>
                                    </div>
                                    -->
                                </div>
                            </div> 
                               <!--<div class="col-3 mx-auto m-4 mx-auto ml-3 border-start">
                                <div class="">
                                    <div class="card mx-auto bg-light" style="max-width: 15rem;">
                                        <div class="card-header"><i class="bi bi-question-square"></i> SUPORTE</div>
                                        <div class="card-body">
                                            <p class="card-text position-relative" style="max-height: 10rem;">
                                            <p class="card-title small">Fale conosco</p>
                                            <textarea class="form-control mb-4" name="SUP_TEXTO" id="SUP_TEXTO" width="100%;" rows="5rem;"></textarea>
                                            <button type="button" class="mt-5 position-absolute btn btn-outline-secondary fixed-bottom">ENVIAR</button>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div> -->
                        </div>
                    <?php } ?>
                </section>
                <?php include_once 'inc/rodape.phtml';?>
                <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
                <script>
                    var options = {
                chart: {
                    type: 'bar',
                    colors: ['#50DD98']
                },
                series: [{
                    name: 'estoque',
                    data: [35,50]
                }],
                xaxis: {
                    categories: [2023,2024]
                    }
                }

                var chart = new ApexCharts(document.querySelector("#chart"), options);

                chart.render();
                    </script>
            </div>
        </div>
    </div>
</body>
</html>