<?php include_once 'inc/cabecalho.phtml'; ?>
<style>
    .text-small {
  font-size: 0.9rem;
}

.messages-box,
.chat-box {
  height: 510px;
  overflow-y: scroll;
}

.rounded-lg {
  border-radius: 0.5rem;
}

input::placeholder {
  font-size: 0.9rem;
  color: #999;
}
</style>
<body>
<div class="d-flex" id="wrapper" style="font-family: WF Visual Sans Text,sans-serif;">
    <?php include_once 'inc/menu_lateral.phtml'; ?>
    <div id="page-content-wrapper">
        <?php include_once 'inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3" style="background-color: #40bf7b;">
            </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row rounded-lg overflow-hidden shadow">
                        <!-- Users box-->
                        <div class="col-5 px-0">
                        <div class="bg-white">

                            <div class="bg-gray px-4 py-2 bg-light">
                                <p class="h5 mb-0 py-1">Recente</p>
                            </div>

                            <div class="messages-box">
                                <div class="list-group rounded-0">
                                    <a class="list-group-item list-group-item-action bg-success text-white rounded-0">
                                    <div class="media"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                                        <div class="media-body ml-4">
                                            <div class="d-flex align-items-center justify-content-between mb-1">
                                                <h6 class="mb-0">SUPORTE</h6><small class="small font-weight-bold">LC-TEC</small>
                                            </div>
                                            <p class="font-italic mb-0 text-small">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p>
                                        </div>
                                    </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        </div>
                        <!-- Chat Box-->
                        <div class="col-7 px-0">
                        <div id="chat" class="px-4 py-5 chat-box bg-white">
                            <!-- Sender Message-->
                            <div class="media w-50 mb-3"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                                <div class="media-body ms-3">
                                    <div class="bg-light rounded py-2 px-3 mb-2">
                                    <p class="text-small mb-0 text-muted">Test which is a new approach all solutions</p>
                                    </div>
                                    <p class="small text-muted">12:00 PM | Aug 13</p>
                                </div>
                            </div>

                            <!-- Reciever Message-->
                            <div class="media w-50 ms-auto mb-3">
                                <div class="media-body">
                                    <div class="bg-success rounded py-2 px-3 mb-2">
                                    <p class="text-small mb-0 text-white">Test which is a new approach to have all solutions</p>
                                    </div>
                                    <p class="small text-muted">12:00 PM | Aug 13</p>
                                </div>
                            </div>

                            <!-- Sender Message-->
                            <div class="media w-50 mb-3"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                            <div class="media-body ms-3">
                                <div class="bg-light rounded py-2 px-3 mb-2">
                                <p class="text-small mb-0 text-muted">Test, which is a new approach to have</p>
                                </div>
                                <p class="small text-muted">12:00 PM | Aug 13</p>
                            </div>
                            </div>

                            <!-- Recebida Message-->
                            <div class="media w-50 ms-auto mb-3">
                            <div class="media-body">
                                <div class="bg-success rounded py-2 px-3 mb-2">
                                <p class="text-small mb-0 text-white">Apollo University, Delhi, India Test</p>
                                </div>
                                <p class="small text-muted">12:00 PM | Aug 13</p>
                            </div>
                            </div>

                            <!-- Enviada Message-->
                            <div class="media w-50 mb-3"><img src="https://bootstrapious.com/i/snippets/sn-chat/avatar.svg" alt="user" width="50" class="rounded-circle">
                            <div class="media-body me-3">
                                <div class="bg-light rounded py-2 px-3 mb-2">
                                <p class="text-small mb-0 text-muted">Test, which is a new approach</p>
                                </div>
                                <p class="small text-muted">12:00 PM | Aug 13</p>
                            </div>
                            </div>

                            <!-- Reciever Message-->
                            <div class="media w-50 ms-auto mb-3">
                            <div class="media-body">
                                <div class="bg-success rounded py-2 px-3 mb-2">
                                <p class="text-small mb-0 text-white">Apollo University, Delhi, India Test</p>
                                </div>
                                <p class="small text-muted">12:00 PM | Aug 13</p>
                            </div>
                            </div>

                        </div>

                        <!-- Typing area -->
                        <form id="MSG" action="#" class="bg-light">
                            <div class="input-group">
                            <input type="text" id="SUP_MENSAGEM" name="SUP_MENSAGEM" placeholder="Envie uma mensagem" aria-describedby="button-addon2" class="form-control rounded-0 border-0 py-4 bg-light">
                            <input type="hidden" class="form-control" id="EMP_COD" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                            <input type="hidden" class="form-control" id="USU_COD" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                            <div class="input-group-append">
                                <button id="button-addon2" type="submit" class="btn btn-link"> <i class="fa fa-paper-plane"></i></button>
                            </div>
                            </div>
                        </form>

                        </div>
                    </div>
                </section>
                <?php include_once 'inc/rodape.phtml';?>
        </div>
    </div>
    
</div>
<script type="text/javascript">
    $("#MSG").click(function(){
        var SUP_MENSAGEM = $('#SUP_MENSAGEM').val();
        var EMP_COD = $('#EMP_COD').val();
        var USU_COD = $('#USU_COD').val();
        //var PRO_STATUS = $('#PRO_STATUS').val();
        //setTimeout(function () {
              //  $('#status').modal('hide');
        //}, 100);
        $.post('<?= DIRPAGE; ?>suporte/cadastrar', {SUP_MENSAGEM: SUP_MENSAGEM,CADASTRAR_NOVA_MENSAGEM: true,EMP_COD: EMP_COD,USU_COD:USU_COD}, function(retorno) {
            var resposta = JSON.parse(retorno);
            console.log(resposta);
            //if (resposta['COD'] !== 'ERRO') {
             //   $('#resposta').addClass('alert alert-success');
            //}else{
                //$('#resposta').addClass('alert alert-warning');
           // }
           // $('#resposta').html(resposta['MENSAGEM']);
            //setTimeout( () => { window.location.href="<?php //= DIRPAGE ?>estoques/produtos/"+EMP_COD+"/"+EST_COD}, 100);
        });

    });
</script>
</body>
</html>