<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($enderecos) ? count($enderecos) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>enderecos">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Endereços</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light py-2">
                <div class="container px-2 py-2 mx-auto row ">
                    <?php if ($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Logadouro</th>
                            <th class="text-dark">Número</th>
                            <th class="text-dark">Bairro</th>
                            <th class="text-dark">Cidade</th>
                            <th class="text-dark">Status</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) { 
                        ?>
                            <tr class="">
                                <td class="text-center align-middle"><?= $b; ?></td>
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">NENHUMA EMPRESA/NEGÓCIO CADASTRADO(A)</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    
</body>
</html>