<?php 
use Libraries\Sessao;
use App\Models\Suporte;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($suporte_cliente) ? count($suporte_cliente) : 0);
$qtdE = (is_array($empresa_cliente) ? count($empresa_cliente) : 0);

$Sp = new Suporte;

//dump($empresa_cliente);
//dump($qtdE);
dump($suporte_cliente);
?>
<style>
    .text-small {
  font-size: 0.9rem;
}

.messages-box,
.chat-box {
  height: 510px;
  overflow-y: scroll;
}

.rounded-lg {
  border-radius: 0.5rem;
}

input::placeholder {
  font-size: 0.9rem;
  color: #999;
}
</style>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec/suporte">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> DETALHAR <span class="text-success">MENSAGEM PARA O SUPORTE</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="row col-12 mx-auto m-1">
                        <div class="row rounded-lg overflow-hidden shadow">
                            <!-- Users box-->
                            <div class="col-5 px-0">
                                <div class="bg-white">

                                    <div class="bg-gray px-4 py-2 bg-light">
                                        <a class="text-decoration-none" title="Atualizar" href="<?= DIRPAGE; ?>suporte/detalhar/<?= $empresa_cliente[0]['EMP_COD'] ?>">
                                            <h5 class="fs-3 fw-bolder text-uppercase text-dark mb-1">
                                                <i class="bi bi-arrow-clockwise"></i> Atualizar <span class="text-success">mensagens</span>
                                            </h5>
                                        </a>
                                    </div>

                                    <div class="messages-box">
                                        <div class="list-group rounded-0">
                                            <a class="list-group-item list-group-item-action bg-success text-white rounded-0">
                                            <div class="media">
    
                                                <div class="media-body ml-4">
                                                    <div class="d-flex align-items-center justify-content-between mb-1">
                                                        <h6 class="mb-0"><?= $empresa_cliente[0]['EMP_NOME_FANTASIA'] ?></h6><small class="small font-weight-bold">EMPRESA: <?= $empresa_cliente[0]['EMP_NOME_FANTASIA'] ?></small>
                                                    </div>
                                                    <p class="font-italic mb-0 text-small"></p>
                                                </div>
                                            </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-7 px-0">
                                <div id="chat" class="px-4 py-5 chat-box bg-white">
                                    <?php if ($qtd != 0) { 
                                        for ($i=0; $i < $qtd; $i++) { 
                                            $data = new DateTime($suporte_cliente[$i]['SUP_DT_CADASTRO']);  
                                                if ($suporte_cliente[$i]['USU_COD_DESTINATARIO'] == 0) {  ?>
                                                    <!-- Reciever Message-->
                                                    <?php 
                                                    if ($suporte_cliente[$i]['SUP_STATUS'] == 1) {
                                                        $dados = array(
                                                            'SUP_DT_ATUALIZACAO'=> date('Y-m-d H:i:s'),         
                                                            'SUP_STATUS'=> 2
                                                        );
                                                        $Sp->setCodEmpresa($suporte_cliente[$i]['EMP_COD'])->setCodigo($suporte_cliente[$i]['SUP_COD'])->alterar($dados,0); 
                                                        $status = '';
                                                    }else {
                                                        $status = 'opacity-50';
                                                        $checar = '<i class="bi bi-check-all"></i>';
                                                    }
                                                    ?>
                                                    <div class="media w-50 ms-auto mb-3 <?= $status ?>">
                                                        <div class="media-body">
                                                            <div class="bg-success rounded py-2 px-3 mb-2">
                                                                <p class="text-small mb-0 text-white"><?= $suporte_cliente[$i]['SUP_MENSAGEM'] ?> <?= $checar ?></p>
                                                            </div>
                                                            <p class="small text-muted"><?= (date('Y-m-d') == $data->format('Y-m-d')) ? '<b>Hoje</b> às '. $data->format('H:i') : ((date('Y-m-d', strtotime("-1 days")) == $data->format('Y-m-d')) ? 'Ontem às '. $data->format('H:i') : $data->format('d/m/Y H:i')); ?></p>
                                                        </div>
                                                    </div>
                                                   
                                                    
                                            <?php } else {  ?>
                                                    <!-- Sender Message-->
                                                    <?php 
                                                    if ($suporte_cliente[$i]['SUP_STATUS'] == 2) { 
                                                        $status = 'opacity-50';
                                                    }else {
                                                        $status = '';
                                                    }
                                                    ?>
                                                    <div class="media w-75 mb-3 <?= $status ?>">
                                                        <div class="media-body ms-3">
                                                            <div class="bg-light rounded py-2 px-3 mb-2">
                                                                <p class="text-small mb-0 text-muted"><?= $suporte_cliente[$i]['SUP_MENSAGEM'] ?>
                                                                <?php if ($suporte_cliente[$i]['SUP_STATUS'] == 1) {  ?>
                                                                    <button type="button" class="btn btn-outline-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Excluir" data-codigo="<?= $suporte_cliente[$i]['SUP_COD']; ?>" data-empresa="<?= $suporte_cliente[$i]['EMP_COD']; ?>"><i class="fa fa-trash"></i></button>
                                                                <?php } ?>
                                                                </p>
                                                            </div>
                                                            <p class="small text-muted"><?= (date('Y-m-d') == $data->format('Y-m-d')) ? '<b>Hoje</b> às '. $data->format('H:i') : ((date('Y-m-d', strtotime("-1 days")) == $data->format('Y-m-d')) ? 'Ontem às '. $data->format('H:i') : $data->format('d/m/Y H:i')); ?></p>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                            <?php } ?>
                                    <?php } ?>
                                    <input type="hidden" id="fim"/>
                                </div>
                                <div id="retorno"  class="text-center"></div>
                                <form id="MSG" action="#" method="post" class="bg-light">
                                    <div class="input-group">
                                        <input type="text" id="SUP_MENSAGEM" autofocus name="SUP_MENSAGEM" placeholder="Envie uma mensagem" aria-describedby="button-addon2" class="form-control rounded-0 border-0 py-2 bg-light">
                                        <input type="hidden" class="form-control" id="EMP_COD" name="EMP_COD" value="<?= isset($suporte_cliente[0]['EMP_COD']) ? $suporte_cliente[0]['EMP_COD'] : 0; ?>">
                                        <input type="hidden" class="form-control" id="USU_COD" name="USU_COD" value="0">
                                        <div class="input-group-append">
                                            <button  type="submit" class="btn btn-lg btn-link"> <i class="fa fa-paper-plane"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                     $("#MSG").submit(function(e){
                    e.preventDefault();
                    var SUP_MENSAGEM = $('#SUP_MENSAGEM').val();
                    if (SUP_MENSAGEM == "") {
                        $('#retorno').addClass('alert alert-warning');
                        $('#retorno').html('Escreva uma mensagem');
                        document.getElementById("fim").focus();
                        setTimeout( () => { 
                            $('#retorno').html('');
                            $('#retorno').removeClass('alert alert-warning')}, 1200);
                    } else {
                        var EMP_COD = $('#EMP_COD').val();
                        var USU_COD = $('#USU_COD').val();
                        var USU_COD_DESTINATARIO = <?= $suporte_cliente[0]['USU_COD'] ?>;
                        //setTimeout(function () {
                            //  $('#status').modal('hide');
                        //}, 100);
                        $.post('<?= DIRPAGE; ?>suporte/cadastrar', {SUP_MENSAGEM: SUP_MENSAGEM,CADASTRAR_NOVA_MENSAGEM: true,EMP_COD: EMP_COD,USU_COD:USU_COD,USU_COD_DESTINATARIO: USU_COD_DESTINATARIO}, function(retorno) {
                            var resposta = JSON.parse(retorno);
                            console.log(resposta);
                            if (resposta['COD'] !== 'ERRO') {
                                $('#retorno').addClass('alert alert-success');
                            }else{
                                $('#retorno').addClass('alert alert-warning');
                            }
                            $('#retorno').html(resposta['MENSAGEM']);
                            $('#SUP_MENSAGEM').val('');
                            document.getElementById("fim").focus();
                            //setTimeout( () => { window.location.href="<?php //= DIRPAGE ?>estoques/produtos/"+EMP_COD+"/"+EST_COD}, 100);
                        });
                    }
                    

                });
                    function getMessages(letter) {
                        var div = $("#chat");
                        div.scrollTop(div.prop('scrollHeight'));
                    }

                    $(function() {
                        setInterval(getMessages, 3500);
                    // getMessages();
                    });
                    setInterval(() =>  $("#SUP_MENSAGEM").focus(), 3000);
                </script>
            </div>
        </div>
    </div>
</body>
</html>