<?php 
use Libraries\Sessao;
use App\Models\Suporte;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($suporte) ? count($suporte) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
$Sp = new Suporte;

?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec/suporte">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">MENSAGENS PARA O SUPORTE</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="row col-10 mx-auto m-1">
                        <ul class="list-group">
                            <li class="list-group-item bg-success text-white" aria-current="true">MENSAGENS PARA O SUPORTE</li>
                            <?php
                            
                            for ($i=0; $i < $qtdE; $i++) {  
                                $vtM = $Sp->setCodEmpresa($empresas[$m]['EMP_COD'])->setStatus(1)->listarTodasMensagensEmpresa(0);
                                $qtdMsgEmpresa = (is_array($vtM) ? count($vtM) : 0);
                            ?>
                            <li>
                                <a href="<?= DIRPAGE ?>suporte/detalhar/<?= $empresas[$i]['EMP_COD']; ?>" title="Visualizar Mensagens da Empresa" class="list-group-item list-group-item-action">
                                    <div class="d-flex w-100 text-center justify-content-between">
                                        <h5 class=" text-center "><b><?= isset($empresas[$i]['EMP_NOME_FANTASIA']) ? 'EMPRESA: '.$empresas[$i]['EMP_NOME_FANTASIA']: ''; ?></b></h5>
                                        <p class="mb-1 text-uppercase"><span class=" badge text-bg-danger"><?= $qtdMsgEmpresa; ?></span>
                                            <small class="piscar text-body-secondary"><?= ($qtdMsgEmpresa >= 1)? 'AGUARDANDO RESPOSTA' : 'RESOLVIDO'; ?></small>
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <?php }?>
                        </ul>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>
