<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($suporte) ? count($suporte) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
//$new_msg = array();
//for ($i=0; $i < $qtdE; $i++) {  
    //for ($s=0; $s < $qtd; $s++) {  
       // if($empresas[$i]['EMP_COD'] == $suporte[$s]['EMP_COD']){
         //   $new_msg['NOME'] = $suporte[$s]['EMP_NOME_FANTASIA'];
          //  $new_msg[$i][$s] = $suporte[$s];
       // }
   // } 
//}
//dump($qtd);
?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec/suporte">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">MENSAGENS PARA O SUPORTE</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="row col-10 mx-auto m-1">
                        <ul class="list-group">
                            <li class="list-group-item bg-success text-white" aria-current="true">MENSAGENS PARA O SUPORTE</li>
                            <?php if ($qtd != 0) { ?>
                                <?php for ($i=1; $i < $qtd; $i++) {  
                                    ///for ($s=0; $s < $qtd; $s++) {  <i class="bi bi-check-all"></i> <i class="bi bi-check"></i>
                                    $data = new DateTime($suporte[$i]['SUP_DT_CADASTRO']); ?>
                                    <a href="<?= DIRPAGE ?>lctec/suporte/detalhar/<?= $suporte[$i]['EMP_COD'] ?>" class="list-group-item list-group-item-action">
                                        <div class="d-flex w-100 text-center justify-content-between">
                                            <h5 class="mb-1 text-center "><?= $suporte[$i]['SUP_MENSAGEM'] ?></h5>
                                            <small class="text-body-secondary"><?= $suporte[$i]['EMP_NOME_FANTASIA'].' - '.$data->format('d/m/Y H:i'); ?></small>
                                        </div>
                                        <p class="mb-1"></p>
                                        <small class="text-body-secondary"><?= ($suporte[$i]['SUP_STATUS'] == 1)? 'AGUARDANDO RESPOSTA' : 'DESATIVADA'; ?></small>
                                    </a>
                                <?php } ?>
                            <?php }else { ?>
                                NENHUMA MENSAGEM CADASTRADA
                            <?php } ?>
                        </ul>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>