<?php
use Libraries\Sessao;


include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($fornecedores) ? count($fornecedores) : 0);

?>
<body>
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                    <header class="py-3">
                        <section class="container px-3">
                            <div class="row gx-5 align-items-center justify-content-center">
                                <div class="col-lg-9 col-xl-9 col-xxl-9">
                                    <div class="my-1 px-4 mx-auto">
                                        <a class="text-decoration-none" href="<?= DIRPAGE; ?>fornecedores">
                                            <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="bi bi-boxes"></i> Gerenciar <span class="text-success">Fornecedores</span>
                                            </h5>
                                        </a>
                                    </div>
                                </div>
                                <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                            </div>
                        </section>
                        <section class="container col-12 mx-auto px-5">
                            <?= $breadcrumb ?>
                        </section>
                    </header>
                    <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                    <section class="bg-light  text-dark  py-2">
                        <div class="container mx-auto col-12 px-2 py-2 mx-auto row">
                            <div class="card bg-success text-center py-2 mb-4">
                                <div class="card-body  text-white">
                                    <h5 class="card-title">FORNECEDORES</h5>
                                    <p class="card-text">Cadastre os dados dos seus fornecedores</p>
                                    <a href="<?= DIRPAGE ?>fornecedores/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                                </div>
                            </div>
                            <?php if ($qtd != 0) { ?>
                            <table class="table table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th class="text-dark">#</th>
                                    <th class="text-dark">Tipo</th>
                                    <th class="text-dark">Nome</th>
                                    <th class="text-dark">Email</th>
                                    <th class="text-dark">Tel 1</th>
                                    <th class="text-dark">Resp.</th>
                                    <th class="text-dark">Status</th>
                                    <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                                </thead>
                                <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="<?= ($fornecedores[$i]['FOR_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= ($fornecedores[$i]['FOR_TIPO'] != '0')? (($fornecedores[$i]['FOR_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?></td>
                                        <td class="text-center align-middle"><?= $fornecedores[$i]['FOR_NOME_FANTASIA'].' '.$fornecedores[$i]['USU_SOBRENOME']; ?></td>
                                        <td class="text-center align-middle"><?= $fornecedores[$i]['FOR_EMAIL_1']; ?></td>
                                        <td class="text-center align-middle"><?= $fornecedores[$i]['FOR_TEL_1']; ?></td>
                                        <td class="text-center align-middle"><?= $fornecedores[$i]['FOR_RESPONSAVEL']; ?></td>
                                        <td class="text-center align-middle"><?= ($fornecedores[$i]['FOR_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                        <td class="text-center align-middle">
                                            <?php if($fornecedores[$i]['FOR_STATUS'] == 0){ ?>
                                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $fornecedores[$i]['FOR_COD']; ?>" data-nome="<?= $fornecedores[$i]['FOR_NOME_FANTASIA']; ?>"  data-status="<?= $fornecedores[$i]['FOR_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                            <?php }else { ?>
                                            <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'fornecedores/alteracao/'.$fornecedores[$i]['EMP_COD'].'/'.$fornecedores[$i]['USU_COD']; ?>" title="Alterar fornecedores"><i class="fa fa-edit"></i></a>
                                            <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $fornecedores[$i]['FOR_COD']; ?>" data-nome="<?= $fornecedores[$i]['FOR_NOME_FANTASIA']; ?>"  data-status="<?= $fornecedores[$i]['FOR_STATUS']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                            <?php } ?>
                                        </td>
                                        <?php } ?>
                                    </tr>
                                <?php $b++; } ?>
                                </tbody>
                            </table>
                        <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM FORNECEDOR CADASTRADO</h4>
                        <?php } ?>
                        </div>
                    </section>
                </div>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            </div>
           
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma desativação deste registro?</p>
                    <span id="FOR_NOME_FANTASIA" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="FOR_COD" name="FOR_COD" value="" />
                    <input type="hidden" id="FOR_STATUS" name="FOR_STATUS" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""><i class="fa fa-ban"></i> CONFIRMAR</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#FOR_COD').val(codigo);
                modal.find('#FOR_STATUS').val(status);
                modal.find('#deletar').val(codigo);
                modal.find('#FOR_NOME_FANTASIA').html(nome);
                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Fornecedor(a)?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Fornecedor(a)?');
                }
            });
        });
        $("#sts").click(function(){
            var FOR_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var FOR_STATUS = $('#FOR_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>fornecedores/status', {FOR_COD: FOR_COD,STATUS_FORNECEDOR: true,EMP_COD: EMP_COD,FOR_STATUS:FOR_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>fornecedores"}, 100);
            });

        });
    </script>
</body>
</html>