<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($movimentacoes) ? count($movimentacoes) : 0);
$qtdFP = (is_array($formas_pgto) ? count($formas_pgto) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-success">Contas a Pagar e Receber</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light  text-dark row  py-2">
                <div class="container mx-auto col-12 row">
                <?php if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Conta</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Data</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Classificação</th>
                            <th class="text-dark">Categoria</th>
                            <th class="text-dark">Forma de Pgto</th>
                            <th class="text-dark">Valor</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Obs</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) {  $data = new DateTime($empresas[$i]['MOV_DT_CADASTRO']);?>
                            <tr class="<?= ($movimentacoes[$i]['MOV_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['CTA_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['MOV_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['MOV_TIPO']; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['MOV_CLASSIFICACAO']; ?></td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($movimentacoes[$i]['CAT_COD'] != 0 or $movimentacoes[$i]['CAT_COD'] != '') {
                                        for ($c = 0; $c < $qtdC; $c++) { 
                                            if ($categorias[$c]['CAT_COD'] == $movimentacoes[$i]['CAT_COD']) { ?>
                                            <?= $categorias[$c]['CAT_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($movimentacoes[$i]['FPG_COD'] != 0 or $movimentacoes[$i]['FPG_COD'] != '') {
                                        for ($c = 0; $c < $qtdFP; $c++) { 
                                            if ($formas_pgto[$c]['FPG_COD'] == $movimentacoes[$i]['FPG_COD']) { ?>
                                            <?= $formas_pgto[$c]['FPG_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle"><?= number_format($movimentacoes[$i]['PGT_VALOR'],2,',','.'); ?></td>
                                <td class="text-center align-middle"><?= ($movimentacoes[$i]['MOV_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">

                                </td>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                <td class="text-center align-middle">
                                </td>
                                <?php } ?>
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                <?php }else { ?>
                    <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA MOVIMENTAÇÃO CADASTRADA</h4>
                <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>