<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdCLA = (is_array($classificacoes) ? count($classificacoes) : 0);
$qtd = (is_array($coluna) ? count($coluna) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>tarefas/colunas">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="fa fa-handshake"></i> Cadastrar <span class="text-success"> Colunas</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 " action="<?= DIRPAGE ?>tarefas/alterar_colunas" method="POST">
                            <div class="row ">
                                <div class="col-3 mb-2 text-center">
                                    <div class="form-floating mb-3">
                                        <select class="form-select" name="CLN_TIPO">                                        
                                            <option value="1" <?= (isset($_POST['CLN_TIPO']) &&  $_POST['CLN_TIPO']  == 1)? 'selected' : ((isset($coluna['CLN_TIPO']) && $coluna['CLN_TIPO'] == 1)? 'selected' : ''); ?>>TAREFAS</option> 
                                            <option value="2" <?= (isset($_POST['CLN_TIPO']) &&  $_POST['CLN_TIPO']  == 2)? 'selected' : ((isset($coluna['CLN_TIPO']) && $coluna['CLN_TIPO'] == 2)? 'selected' : ''); ?>>PRODUÇÃO</option> 
                                        </select>
                                        <label class="form-floating ">TIPO DA COLUNA</label>
                                    </div>
                                </div>
                                <div class="col-3 mb-2 form-floating ">
                                    <select class="form-select " name="CLN_POSICAO">                                        
                                        <?php for ($i=1; $i <= 50; $i++) { ?>
                                            <option value="<?= $i?>" <?= (isset($_POST['CLN_POSICAO']) &&  $_POST['CLN_POSICAO']  == $i)? 'selected' : ((isset($coluna['CLN_POSICAO']) && $coluna['CLN_POSICAO'] == $i)? 'selected' : '') ?>><?= $i ?></option>
                                        <?php } ?>
                                    </select>
                                    <label class="form-label">POSIÇÃO DA COLUNA</label>
                                </div>
                                <div class="col-6 mb-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="1" name="CLN_DESCRICAO" placeholder="" value="<?= isset($_POST['CLN_DESCRICAO']) ? $_POST['CLN_DESCRICAO'] :  ((isset($coluna['CLN_DESCRICAO']))? $coluna['CLN_DESCRICAO'] : ''); ?>">
                                        <label class="form-floating px-3" for="1">DESCRIÇÃO DA COLUNA</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <input type="hidden" class="form-control" name="CLN_COD" value="<?= isset($_SESSION['CLN_COD']) ? $_SESSION['CLN_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-warning" name="ALTERAR_COLUNA_TAREFA" type="submit"><i class="fa fa-edit"></i> Alterar</button>
                            </div> 
                        </form>
                    </div>
                </section>
                </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>