<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdCLA = (is_array($classificacoes) ? count($classificacoes) : 0);
$qtdCLN = (is_array($colunas) ? count($colunas) : 0);
$qtd = (is_array($tarefas) ? count($tarefas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>tarefas">
                                    <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Tarefas</span></h5>
                                </a>
                                <div class="col-12 my-1 px-4 mx-auto">
                                    <a type="button" class="btn btn-sm btn-success"  href="<?= DIRPAGE; ?>tarefas" title="Nova Tarefa"><i class="bi bi-bookmarks"></i> + TAREFA</a>
                                    <a type="button" class="btn btn-sm btn-dark"  href="<?= DIRPAGE; ?>avisos" title="Novo Aviso"><i class="bi bi-bell"></i> + AVISO</a>
                                </div>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="mx-auto row text-center col-12 py-1 mb-2 d-print-none">
                    <div class="card bg-success mx-auto text-center col-6 py-1 mb-2 d-print-none">
                        <div class="card-body text-white">
                            <h5 class="card-title">TAREFAS</h5>
                            <p class="card-text">Cadastre suas tarefas</p>
                            <a href="<?= DIRPAGE ?>tarefas/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>  
                    <div class="card bg-success mx-auto text-center col-6 py-1 mb-2 d-print-none">
                        <div class="card-body text-white">
                            <h5 class="card-title">COLUNAS</h5>
                            <p class="card-text">Cadastre as colunas para suas tarefas</p>
                            <a href="<?= DIRPAGE ?>tarefas/colunas" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>  
                </div>
                <?php if ($qtd != 0) { ?>
                    <div class="mx-auto row text-center col-12 py-1 mb-2 d-print-none">
                        <?php 
                         for ($c= 0; $c < $qtdCLN; $c++) {
                            $t = 1; ?>
                            <table class="table row col table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th colspan="2" class="text-center align-middle"><?= $colunas[$c]['CLN_DESCRICAO']; ?></th>
                                    <th class="text-center align-middle"><a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'tarefas/alteracao_colunas/'.$colunas[$c]['EMP_COD'].'/'.$colunas[$c]['CLN_COD']; ?>" title="Alterar coluna"><i class="fa fa-edit"></i></a></th>
                                    <tr>  
                                        <?php for ($i=0; $i < $qtd; $i++) {
                                            if($tarefas[$i]['CLN_COD'] == $colunas[$c]['CLN_COD']){ ?>
                                            <tr class="<?= ($tarefas[$i]['TRF_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                                                <td class="text-center align-middle"><?= $t; ?></td>
                                                <td class="text-center align-middle"><?= $tarefas[$i]['TRF_DESCRICAO']; ?></td>
                                                <td><button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $tarefas[$i]['TRF_COD']; ?>" data-nome="<?= $tarefas[$i]['TRF_DESCRICAO']; ?>" data-status="<?= $tarefas[$i]['CLN_COD']; ?>" title="Deseja mudar?" ><i class="fa fa-ban"></i></button></td>
                                            </tr>
                                            <?php $t++; } ?>
                                        <?php  } ?>
                                    </tr>
                                </thead>
                            </table> 
                        <?php } ?>
                        </div>
                <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA TAREFA CADASTRADA</h4>
                    <?php } ?>
            </section>
        </div>
        <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
    </div>
</body>
</html>
<!--- <thead class="text-center text-uppercase">
                        <th class="text-dark">#</th>
                        <th class="text-dark">Tipo</th>
                        <th class="text-dark">Descrição</th>
                        <th class="text-dark">Status</th>
                        <?php // if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php //} ?> 
                    </thead> 
                    
                    
                    <?php //$c = 1; for ($i= 0; $i < $qtd; $i++) { ?>
                                <tr class="<?php // ($tarefas[$i]['TRF_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                                    <td class="text-center align-middle"><?php  // $c; ?></td>
                                    <?php   if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                    <?php   } ?> 
                                </tr>
                            <?php //$c++;   } ?>
                    --->