<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>tarefas">
                                    <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Tarefas</span></h5>
                                </a>
                                <div class="col-12 my-1 px-4 mx-auto">
                                    <a type="button" class="btn btn-sm btn-success"  href="<?= DIRPAGE; ?>tarefas" title="Nova Tarefa"><i class="bi bi-bookmarks"></i> + TAREFA</a>
                                    <a type="button" class="btn btn-sm btn-dark"  href="<?= DIRPAGE; ?>avisos" title="Novo Aviso"><i class="bi bi-bell"></i> + AVISO</a>
                                </div>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="mx-auto row text-center col-12 py-1 mb-2 d-print-none">
                    <div class="card bg-success mx-auto text-center col-6 py-1 mb-2 d-print-none">
                        <div class="card-body text-white">
                            <h5 class="card-title">TAREFAS</h5>
                            <p class="card-text">Cadastre suas tarefas</p>
                            <a href="<?= DIRPAGE ?>tarefas/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>  
                    <div class="card bg-success mx-auto text-center col-6 py-1 mb-2 d-print-none">
                        <div class="card-body text-white">
                            <h5 class="card-title">COLUNAS</h5>
                            <p class="card-text">Cadastre as colunas para suas tarefas</p>
                            <a href="<?= DIRPAGE ?>tarefas/colunas" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>  
                </div>
            </section>
        </div>
        <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
    </div>
</body>
</html>