CREATE TABLE `tb_cargos_salarios` (
	`CGS_COD` INT(11) NOT NULL AUTO_INCREMENT,
	`EMP_COD` INT(11) NOT NULL,
	`USU_COD` INT(11) NOT NULL,
	`CGS_DT_CADASTRO` DATETIME NOT NULL,
	`CGS_DT_ATUALIZACAO` DATETIME NULL DEFAULT NULL,
	`CGS_NOME` VARCHAR(155) NOT NULL COLLATE 'utf8_general_ci',
	`CGS_SALARIO` DECIMAL(10,2) NULL DEFAULT NULL,
	`CGS_NIVEL` VARCHAR(111) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`CGS_TIPO` VARCHAR(11) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`CGS_COMISSAO` VARCHAR(11) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`CGS_STATUS` INT(11) NOT NULL,
	PRIMARY KEY (`CGS_COD`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;

------------------------------------------------------------------------------------

CREATE TABLE `tb_categorias` (
	`CAT_COD` INT(11) NOT NULL AUTO_INCREMENT,
	`EMP_COD` INT(11) NOT NULL,
	`USU_COD` INT(11) NOT NULL,
	`SET_COD` INT(11) NULL DEFAULT NULL,
	`CAT_DT_CADASTRO` DATETIME NULL DEFAULT NULL,
	`CAT_DT_ATUALIZACAO` DATETIME NULL DEFAULT NULL,
	`CAT_DESCRICAO` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`CAT_NIVEL` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`CAT_STATUS` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`CAT_COD`) USING BTREE,
	INDEX `USU_COD` (`USU_COD`) USING BTREE,
	INDEX `EMP_COD` (`EMP_COD`) USING BTREE,
	INDEX `SET_COD` (`SET_COD`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;

------------------------------------------------------------------------------------

CREATE TABLE `tb_promocoes` (
	`PRM_COD` INT(11) NOT NULL AUTO_INCREMENT,
	`EMP_COD` INT(11) NULL DEFAULT NULL,
	`USU_COD` INT(11) NULL DEFAULT NULL,
	`EST_COD` INT(11) NULL DEFAULT NULL,
	`SET_COD` INT(11) NULL DEFAULT NULL,
	`CAT_COD` INT(11) NULL DEFAULT NULL,
	`SCT_COD` INT(11) NULL DEFAULT NULL,
	`PRO_COD` INT(11) NULL DEFAULT NULL,
	`PRO_DESCRICAO` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`PRO_DT_CADASTRO` DATETIME NULL DEFAULT NULL,
	`PRO_DT_ATUALIZACAO` DATETIME NULL DEFAULT NULL,
	`PRO_DT_INICIAL` DATETIME NULL DEFAULT NULL,
	`PRO_DT_FINAL` DATETIME NULL DEFAULT NULL,
	`PRO_TEXTO` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`PRO_DESCONTO` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`PRO_STATUS` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`PRM_COD`) USING BTREE,
	INDEX `USU_COD` (`USU_COD`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


