<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($caixa) ? count($caixa) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>caixas">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark">
                                        <i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Caixas</span>
                                    </h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?> 
            <section class="bg-light  text-dark  py-2">
                <div class="card text-white mx-auto bg-10 m-1 py-3" style="max-width: 35rem;">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-10 fs-5 align-middle">
                                    <i class="bi bi-box"></i> SALDO <?= ($caixa['CXA_SALDO'] != '0')? "R$ ".number_format($caixa['CXA_SALDO'],2,',','.')  : 'R$ 0,00'; ?>
                                </div>  
                                <div class="col-1 mr-1">
                                    <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'caixas/alteracao/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Alterar Caixa"><i class="fa fa-edit"></i></a>
                                </div>
                            </div>  
                        </div>
                        <div class="card-body">
                            <a href="<?= DIRPAGE.'caixa/detalhar/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Acessar Caixa" class="col-auto link-light text-decoration-none">
                                <div class="row">
                                    <div class="col-12">
                                        <h5 class="card-title">Descrição: <?= $caixa['CXA_DESCRICAO']; ?></h5>
                                        <p class="card-text">Empresa/Negócio: <?= $caixa['EMP_NOME_FANTASIA']; ?></p>
                                    </div>
                                    <div class="col-12 mx-auto text-center">
                                        <h2 class="card-title">
                                            
                                        </h2>
                                        <p class="card-text ">ACESSAR</p>
                                    </div>
                                </div>
                            </a>  
                           
                        </div>
                        <div class="card-footer">
                        <div class="col-12 mx-auto text-center">
                                <a href="<?= DIRPAGE.'caixa/detalhar/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Abrir Caixa" class="col-12 mx-auto btn btn-success text-decoration-none">ABRIR CAIXA</a>
                            </div>  
                        </div>
                    </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>