<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdC = (is_array($contas) ? count($contas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>caixas">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark">
                                        <i class="bi bi-plus-square"></i> Alterar <span class="text-success">Caixas</span>
                                    </h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?> 
            <section class="bg-light  text-dark  py-2">
                <div class="container mx-auto col-12 px-2 py-2 row">
                    <form class="p-4 p-md-6 border text-uppercase rounded-3 " action="<?= DIRPAGE ?>caixas/alterar" method="POST">
                        <div class="row mx-auto text-center">
                            <div class="col-8 mb-2">
                                <label class="form-label">CONTA</label>
                                <select class="form-select form-select-lg" name="CTA_COD">
                                    <option value="0" <?= (isset($_POST['CTA_COD']) &&  $_POST['CTA_COD']  == "0")? 'selected' : (isset($caixa['CTA_COD']) &&  $caixa['CTA_COD']  == 0 ? 'selected' : '') ?>>---</option>
                                    <?php for ($i= 0; $i < $qtdC; $i++) { ?> 
                                        <option value="<?= $contas[$i]['CTA_COD']; ?>" <?= (isset($_POST['CTA_COD']) &&  $_POST['CTA_COD']  == $contas[$i]['CTA_COD'] )? 'selected' : (isset($caixa['CTA_COD']) &&  $caixa['CTA_COD']  == $contas[$i]['CTA_COD'] ? 'selected' : '') ?>><?= $contas[$i]['CTA_DESCRICAO'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-4 mb-3">
                                <label class="form-label" for="2">SALDO INICIAL(ATUAL)</label>  
                                <div class="input-group">    
                                    <span class="input-group-text">R$</span>  
                                    <input type="text" class="form-control form-control-lg real" id="" name="CXA_SALDO" placeholder="" value="<?= isset($_POST['CXA_SALDO']) ? $_POST['CXA_SALDO'] : (isset($caixa['CXA_SALDO'])? $caixa['CXA_SALDO'] : '0.00'); ?>">
                                </div>
                            </div>
                            <div class="col-12 mb-3">
                                <label class="form-label" for="1">DESCRIÇÃO</label>
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="1" name="CXA_DESCRICAO" placeholder="" value="<?= isset($_POST['CXA_DESCRICAO']) ? $_POST['CXA_DESCRICAO'] :(isset($caixa['CXA_DESCRICAO'])? $caixa['CXA_DESCRICAO'] : ''); ?>">
                                    <label class="form-floating px-3" for="1">DESCRIÇÃO DO CAIXA</label>
                                </div>
                            </div>
                            <hr class="my-4 text-dark">
                            <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($caixa['EMP_COD']) ? $caixa['EMP_COD'] : 0; ?>">
                            <input type="hidden" class="form-control" name="CXA_COD" value="<?= isset($caixa['CXA_COD']) ? $caixa['CXA_COD'] : 0; ?>">
                            <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                            <button class="w-100 btn btn-lg text-uppercase btn-warning" name="ALTERAR_CAIXA" type="submit"><i class="fa fa-edit"></i> Alterar</button>
                        </div>
                    </form>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="<?= DIRJS ?>jquery.maskMoney.js"></script>
            <script>
                $(document).ready(function(){

                    $('.real').maskMoney({
                        prefix:'',
                        allowNegative: true,
                        thousands:',', decimal:'.',
                        affixesStay: true
                    });
                })
            </script>
        </div>
    </div>