<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($clientes) ? count($clientes) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>clientes">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-people"></i> Gerenciar <span class="text-success">Seus Clientes</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light text-dark">
                <div class="container mx-auto col-12 px-2 py-2 row ">
                    <div class="card bg-success mx-auto text-center col-12 py-1 mb-2">
                        <div class="card-body text-white">
                            <h5 class="card-title">CLIENTES</h5>
                            <p class="card-text">Cadastre seus clientes</p>
                            <a href="<?= DIRPAGE ?>cadastros/cadastro_clientes" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>
                    <?php
                    if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Nome</th>
                            <th class="text-dark">Cadastro</th>
                            <th class="text-dark">Tel./Cel. 1</th>
                            <th class="text-dark">DT. NASC.</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Ações</th>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) { ?>
                            
                                <?php 
                                $data = new DateTime($clientes[$i]['CLI_DT_CADASTRO']);
                                $dt_nascimento = new DateTime($clientes[$i]['CLI_DT_NASCIMENTO']);
                                if ($clientes[$i]['CLI_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8) { ?>
                                 <tr class="bg-secondary">
                                    <td class="text-center align-middle"><?= $b; ?></td>
                                    <td class="text-center align-middle"><?= $clientes[$i]['CLI_NOME']; ?></td>
                                    <td class="text-center align-middle"><?= $data->format('d/m/Y h:i:s'); ?></td>
                                    <td class="text-center align-middle"><?= $clientes[$i]['CLI_TEL_1']; ?></td>
                                    <td class="text-center align-middle"><?= $dt_nascimento->format('d/m/Y'); ?></td>
                                    <td class="text-center align-middle"><?= ($clientes[$i]['CLI_TIPO'] != '0')? (($clientes[$i]['CLI_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?></td>
                                    <td class="text-center align-middle"><?= ($clientes[$i]['CLI_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                    <td class="text-center align-middle">
                                        <button type="button" class="btn btn-primary btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Ativar cliente" data-codigo="<?= $clientes[$i]['CLI_COD']; ?>" data-nome="<?= $clientes[$i]['CLI_NOME']; ?>" data-status="<?= $clientes[$i]['CLI_STATUS']; ?>" title="Deseja ativar?" ><i class="fa-regular fa-circle-check"></i></button>
                                    </td>
                                </tr>
                                <?php }else { ?>
                                <tr class="">
                                    <td class="text-center align-middle"><?= $b; ?></td>
                                    <td class="text-center align-middle"><?= $clientes[$i]['CLI_NOME']; ?></td>
                                    <td class="text-center align-middle"><?= $data->format('d/m/Y h:i:s'); ?></td>
                                    <td class="text-center align-middle"><?= $clientes[$i]['CLI_TEL_1']; ?></td>
                                    <td class="text-center align-middle"><?= $dt_nascimento->format('d/m/Y'); ?></td>
                                    <td class="text-center align-middle"><?= ($clientes[$i]['CLI_TIPO'] != '0')? (($clientes[$i]['CLI_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?></td>
                                    <td class="text-center align-middle"><?= ($clientes[$i]['CLI_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                    <td class="text-center align-middle">
                                        <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'clientes/alteracao/'.$clientes[$i]['EMP_COD'].'/'.$clientes[$i]['CLI_COD']; ?>" title="Alterar cliente"><i class="fa fa-edit"></i></a>
                                        <button type="button" class="btn btn-dark btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Desativar cliente" data-codigo="<?= $clientes[$i]['CLI_COD']; ?>" data-nome="<?= $clientes[$i]['CLI_NOME']; ?>" data-status="<?= $clientes[$i]['CLI_STATUS']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                    </td>
                                </tr>
                                <?php } ?>
                          
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM CLIENTE CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    Deseja desativar o Cliente?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="CLI_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="CLI_STATUS" name="CLI_STATUS" value="" />
                    <input type="hidden" id="CLI_COD" name="CLI_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#CLI_COD').val(codigo);
                modal.find('#CLI_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#CLI_NOME').html(nome);

                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Cliente?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Cliente?');
                }
            });
        });
        $("#sts").click(function(){
            var CLI_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var CLI_STATUS = $('#CLI_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>clientes/status', {CLI_COD: CLI_COD,STATUS_CLIENTE: true,EMP_COD: EMP_COD,CLI_STATUS: CLI_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>clientes"}, 100);
            });

        });
    </script>
</body>
</html>