<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($contas) ? count($contas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-success">Finanças</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light  text-dark row  py-2">
                <div class="container mx-auto col-12 row">
                    <div class="row col-12 text-center mb-2 mx-auto">
                        <div class="col-4 text-bg-success text-center">
                            <div class="card-body">
                                <h5 class="card-title mt-2">SANGRIAS</h5>
                                <p class="card-text">Veja as retiradas realizadas em seus caixas</p>
                                <a href="<?= DIRPAGE ?>caixas/sangrias" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-center">
                            <div class="card-body">
                                <h5 class="card-title">PDV</h5>
                                <p class="card-text">Realize vendas de forma prática, automatizando as baixas em seu estoque</p>
                                <a href="<?= DIRPAGE ?>pdv/ponto_de_venda" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-bg-success text-center">
                            <div class="card-body">
                                <h5 class="card-title">TRANSAÇÕES</h5>
                                <p class="card-text">Acesse todas as transações do caixa por período</p>
                                <a href="<?= DIRPAGE ?>pdv/transacoes" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-center">
                            <div class="card-body">
                                <h5 class="card-title">CAIXAS</h5>
                                <p class="card-text">Cadastre os seus caixas no sistema</p>
                                <a href="<?= DIRPAGE ?>caixas" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>

                    </div>
                    <hr>
                    <div class="col-4 row"></div>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>