<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>classificacoes/cadastro">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="fa fa-handshake"></i> Cadastrar <span class="text-success"> Classificação</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 bg-3" action="<?= DIRPAGE ?>classificacoes/alterar" method="POST">
                            <div class="row ">    
                                <div class="col-4 mb-2 text-center">
                                    <label class="form-label">TIPO</label>
                                    <div class="form-floating mb-3">
                                        <select class="form-select" name="CLA_TIPO">                                        
                                            <option value="0" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 0)? 'selected' : (($classificacao['CLA_TIPO'] == 0)? 'selected' : ''); ?>>----</option>   
                                            <option value="CATEGORIAS" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'CATEGORIAS')? 'selected' : (($classificacao['CLA_TIPO']  == 'CATEGORIAS')? 'selected' : ''); ?>>CATEGORIAS</option> 
                                            <option value="COL" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'COL')? 'selected' : (($classificacao['CLA_TIPO'] == 'COL')? 'selected' : ''); ?>>COLABORADORES</option> 
                                            <option value="CLI" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'CLI')? 'selected' : (($classificacao['CLA_TIPO'] == 'CLI')? 'selected' : ''); ?>>CLIENTES</option>
                                            <option value="EST" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'EST')? 'selected' : (($classificacao['CLA_TIPO'] == 'EST')? 'selected' : ''); ?>>ESTOQUES</option> 
                                            <option value="FOR" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'FOR')? 'selected' : (($classificacao['CLA_TIPO'] == 'FOR')? 'selected' : ''); ?>>FORNECEDORES</option> 
                                            <option value="LAN" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'LAN')? 'selected' : (($classificacao['CLA_TIPO'] == 'LAN')? 'selected' : ''); ?>>LANÇAMENTOS</option> 
                                            <option value="OUT" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'OUT')? 'selected' : (($classificacao['CLA_TIPO'] == 'OUT')? 'selected' : ''); ?>>OUTROS</option> 
                                            <option value="PRO" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'PRO')? 'selected' : (($classificacao['CLA_TIPO'] == 'PRO')? 'selected' : ''); ?>>PRODUTOS</option> 
                                            <option value="SERVIÇOS" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'SERVIÇOS')? 'selected' : (($classificacao['CLA_TIPO'] == 'SERVIÇOS')? 'selected' : ''); ?>>SERVIÇOS</option>      
                                            <option value="TAREFAS" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == 'TAREFAS')? 'selected' : (($classificacao['CLA_TIPO'] == 'TAREFAS')? 'selected' : ''); ?>>TAREFAS</option> 
                                        </select>
                                        <label class="form-floating ">TIPO DA CLASSIFICAÇÃO</label>
                                    </div>
                                </div>
                                <div class="col-8 mb-3">
                                    <label class="form-label" for="1">DESCRIÇÃO</label>
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="1" name="CLA_DESCRICAO" placeholder="" value="<?= isset($_POST['CLA_DESCRICAO']) ? $_POST['CLA_DESCRICAO'] :((isset($classificacao['CLA_DESCRICAO']))? $classificacao['CLA_DESCRICAO'] : ''); ?>">
                                        <label class="form-floating px-3" for="1">DESCRIÇÃO DA CLASSIFICAÇÃO</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="CLA_COD" value="<?= isset($classificacao['CLA_COD']) ? $classificacao['CLA_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-warning" name="ALTERAR_CLASSIFICACAO" type="submit"><i class="fa fa-edit"></i> Alterar</button>
                            </div> 
                        </form>
                    </div>
                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>