<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$cl = array(
    0 => 'A DEFINIR',
    1 => 'CATEGORIAS',
    2 => 'COLABORADORES',
    3 => 'CLIENTES',
    4 => 'ESTOQUES',
    5 => 'FORNECEDORES',
    6 => 'LANÇAMENTOS',
    7 => 'OUTROS',
    8 => 'PRODUTOS',
    9 => 'SERVIÇOS',
    10 =>'TAREFAS',
    11 => 'CONTAS'
);

$qtdCl = (is_array($cl) ? count($cl) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>classificacoes/cadastro">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="fa fa-handshake"></i> Cadastrar <span class="text-success"> Classificação</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 " action="<?= DIRPAGE ?>classificacoes/cadastrar" method="POST">
                            <div class="row ">    
                                <div class="col-4 mb-2 text-center">
                                    <label class="form-label">TIPO</label>
                                    <div class="form-floating mb-3">
                                        <select class="form-select" name="CLA_TIPO">                                         
                                        <?php for ($i=0; $i < $qtdCl; $i++) { ?> 
                                            <option value="<?= $i ?>" <?= (isset($_POST['CLA_TIPO']) &&  $_POST['CLA_TIPO']  == $i)? 'selected' : '' ?>><?= $cl[$i] ?></option>
                                        <?php } ?> 
                                        </select>
                                        <label class="form-floating ">TIPO DA CLASSIFICAÇÃO</label>
                                    </div>
                                </div>
                                <div class="col-8 mb-3">
                                    <label class="form-label" for="1">DESCRIÇÃO</label>
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="1" name="CLA_DESCRICAO" placeholder="" value="<?= isset($_POST['CLA_DESCRICAO']) ? $_POST['CLA_DESCRICAO'] :''; ?>">
                                        <label class="form-floating px-3" for="1">DESCRIÇÃO DA CLASSIFICAÇÃO</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVA_CLASSIFICACAO" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                            </div> 
                        </form>
                    </div>
                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>