<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-3 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>usuarios/cadastro">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="bi bi-person-circle"></i> Cadastrar <span class="text-success"> Usuários</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                            <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 bg-3" action="<?= DIRPAGE ?>usuarios/cadastrar" method="POST">
                            <div class="row ">    
                                <div class="col-2 mb-2 form-floating ">
                                    <select class="form-select " name="USU_NIVEL">                                        
                                        <?php for ($i=1; $i <= 10; $i++) { ?>
                                            <option value="<?= $i?>" <?= (isset($_POST['USU_NIVEL']) &&  $_POST['USU_NIVEL']  == $i)? 'selected' : '' ?>><?= $i ?></option>
                                        <?php } ?>
                                    </select>
                                    <label class="form-label">NÍVEL DO USUÁRIO</label>
                                </div>
                                <div class="col-4 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="1" name="USU_NOME" placeholder="Informe seu nome" value="<?= isset($_POST['USU_NOME']) ? $_POST['USU_NOME'] :''; ?>">
                                    <label class="px-3" for="1">Seu nome</label>
                                </div>    
                                <div class="col-6 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="2" name="USU_SOBRENOME" placeholder="Informe seu sobrenome" value="<?= isset($_POST['USU_SOBRENOME']) ? $_POST['USU_SOBRENOME'] : ''; ?>">
                                    <label class="px-3" for="2">Seu sobrenome</label>
                                </div> 
                            </div> 
                            <div class="row">
                                <hr>
                                <div class="col-5 text-center mb-3">
                                    <label for="inputPassword6" class="col-form-label">Seu Sexo</label>
                                    <div class="mx-auto text-center">   
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="USU_SEXO" id="flexRadioDefault2" value="1" <?= (isset($_POST['USU_SEXO']) && $_POST['USU_SEXO'] == 1) ? "checked" : ''; ?>>
                                            <label class="form-check-label" for="flexRadioDefault2">
                                                Masculino
                                            </label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="USU_SEXO" value="2" <?= (isset($_POST['USU_SEXO']) && $_POST['USU_SEXO'] == 2) ? "checked" : ''; ?> id="flexRadioDefault1">
                                            <label class="form-check-label" for="flexRadioDefault1">
                                                Feminino
                                            </label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-7 text-center mb-3">
                                    <label for="inputPassword6" class="col-form-label">Email de Acesso</label>
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="email" name="USU_EMAIL" placeholder="Informe seu email nome@examplo.com" value="<?= isset($_POST['USU_EMAIL']) ? $_POST['USU_EMAIL'] : ''; ?>">
                                        <label for="email">Seu Email</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <span class="text-center fs-3 mb-3">A SENHA PADRÃO SERÁ: <b>123456</b><br> O NOVO USUÁRIO DEVERÁ ALTERÁ-LA</span>
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVO_USUARIO" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                                <hr class="my-4 text-dark">
                            </div> 
                        </form>
                    </div>
                </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>
                            