<?php
use Libraries\Sessao;


include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($usuarios) ? count($usuarios) : 0);

$qtdS = (is_array($setores) ? count($setores) : 0);
?>
<body>
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                    <header class="py-3">
                        <section class="container px-3">
                            <div class="row gx-5 align-items-center justify-content-center">
                                <div class="col-lg-9 col-xl-9 col-xxl-9">
                                    <div class="my-1 px-4 mx-auto">
                                        <a class="text-decoration-none" href="<?= DIRPAGE; ?>usuarios">
                                            <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                                <i class="bi bi-person-circle"></i> Gerenciar <span class="text-success">Usuários</span>
                                            </h5>
                                        </a>
                                    </div>
                                </div>
                                <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                            </div>
                        </section>
                        <section class="container col-12 mx-auto px-5">
                            <?= $breadcrumb ?>
                        </section>
                    </header>
                    <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                    <section class="bg-light  text-dark  py-2">
                        <div class="container mx-auto col-12 px-2 py-2 row">
                        
                            <div class="card bg-success text-center py-2 mb-4" style="width: 100rem;">
                                <div class="card-body  text-white">
                                    <h5 class="card-title">USUÁRIOS</h5>
                                    <p class="card-text">Cadastre os seus usuários do sistema</p>
                                    <a href="<?= DIRPAGE ?>usuarios/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                                </div>
                            </div>
                            <?php if ($qtd != 0) { dump($usuarios);
exit;?>
                            <table class="table table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th class="text-dark">#</th>
                                    <th class="text-dark">Nome</th>
                                    <th class="text-dark">Email</th>
                                    <th class="text-dark">Setor</th>
                                    <th class="text-dark">Nível</th>
                                    <th class="text-dark">Status</th>
                                    <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                                </thead>
                                <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="<?= ($usuarios[$i]['USU_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_NOME'].' '.$usuarios[$i]['USU_SOBRENOME']; ?></td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_EMAIL']; ?></td>
                                        <td class="text-center align-middle">
                                            <?php for ($i= 0; $i < $qtdS; $i++) { ?>    
                                            <?= ($usuarios[$i]['SET_COD']== $setores[$i]['SET_COD'])? $setores[$i]['SET_DESCRICAO'] : 'N.I.'; ?>
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_NIVEL']; ?></td>
                                        <td class="text-center align-middle"><?= ($usuarios[$i]['USU_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                        <td class="text-center align-middle">
                                            <?php if($usuarios[$i]['USU_STATUS'] == 0){ ?>
                                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $usuarios[$i]['USU_COD']; ?>" data-nome="<?= $usuarios[$i]['USU_NOME']; ?>" data-status="<?= $usuarios[$i]['USU_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                            <?php }else { ?>
                                                <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'usuarios/alteracao/'.$usuarios[$i]['EMP_COD'].'/'.$usuarios[$i]['USU_COD']; ?>" title="Alterar usuário"><i class="fa fa-edit"></i></a>
                                                <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $usuarios[$i]['USU_COD']; ?>" data-nome="<?= $usuarios[$i]['USU_NOME']; ?>" data-status="<?= $usuarios[$i]['USU_STATUS']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                            <?php } ?>
                                        </td>
                                        <?php } ?>
                                    </tr>
                                <?php $b++; } ?>
                                </tbody>
                            </table>
                            <?php }else { ?>
                                 <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM USUÁRIO CADASTRADO</h4>
                            <?php } ?>
                        </div>
                    </section>
                </div>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            </div>
           
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    Deseja desativar o Usuário(a)?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma desativação deste registro?</p>
                    <span id="USU_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="USU_COD" name="USU_COD" value="" />
                    <input type="hidden" id="USU_STATUS" name="USU_STATUS" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""><i class="fa fa-ban"></i> CONFIRMAR</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#USU_COD').val(codigo);
                modal.find('#USU_NOME').html(nome);
                modal.find('#USU_STATUS').html(status);
                modal.find('#sts').val(codigo);
                
                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Usuário(a)?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Usuário(a)?');
                }
            });
        });
        $("#sts").click(function(){
            var USU_COD = $('#USU_COD').val();
            var EMP_COD = $('#EMP_COD').val();
            var USU_STATUS = $('#USU_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>usuarios/status', {USU_COD: USU_COD,STATUS_USUARIO: true,EMP_COD: EMP_COD, USU_STATUS: USU_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>usuarios"}, 100);
            });

        });
    </script>
</body>
</html>