<?php
use Libraries\Sessao;
session_start();

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($usuarios) ? count($usuarios) : 0);

?>
<body>
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                    <header class="py-3">
                        <section class="container px-3">
                            <div class="row gx-5 align-items-center justify-content-center">
                                <div class="col-lg-9 col-xl-9 col-xxl-9">
                                    <div class="my-1 px-4 mx-auto">
                                        <a class="text-decoration-none" href="<?= DIRPAGE; ?>usuarios">
                                            <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                                <i class="bi bi-person-circle"></i> Gerenciar <span class="text-success">Usuários</span>
                                            </h5>
                                        </a>
                                    </div>
                                </div>
                                <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                            </div>
                        </section>
                        <section class="container col-12 mx-auto px-5">
                            <?= $breadcrumb ?>
                        </section>
                    </header>
                    <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                    <section class="bg-light  text-dark  py-2">
                        <div class="container mx-auto col-12 px-2 py-2 row">
                        
                            <div class="card bg-success text-center py-2 mb-4" style="width: 100rem;">
                                <div class="card-body  text-white">
                                    <h5 class="card-title">USUÁRIOS</h5>
                                    <p class="card-text">Cadastre os seus usuários do sistema</p>
                                    <a href="<?= DIRPAGE ?>usuarios/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                                </div>
                            </div>
                            <?php if ($qtd != 0) { ?>
                            <table class="table table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th class="text-dark">#</th>
                                    <th class="text-dark">Nome</th>
                                    <th class="text-dark">Email</th>
                                    <th class="text-dark">Nível</th>
                                    <th class="text-dark">Status</th>
                                    <th class="text-dark">Ações</th>
                                </thead>
                                <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_NOME'].' '.$usuarios[$i]['USU_SOBRENOME']; ?></td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_EMAIL']; ?></td>
                                        <td class="text-center align-middle"><?= $usuarios[$i]['USU_NIVEL']; ?></td>
                                        <td class="text-center align-middle"><?= ($usuarios[$i]['USU_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <td class="text-center align-middle">
                                            <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'cadastros/alterar_usuarios/'.$usuarios[$i]['EMP_COD'].'/'.$usuarios[$i]['USU_COD']; ?>" title="Alterar usuário"><i class="fa fa-edit"></i></a>
                                            <button type="button" class="btn btn-dark btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#excluir" title="Desativar usuário" data-codigo="<?= $usuarios[$i]['USU_COD']; ?>" data-nome="<?= $usuarios[$i]['USU_NOME']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                        </td>
                                    </tr>
                                <?php $b++; } ?>
                                </tbody>
                            </table>
                            <?php }else { ?>
                                 <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM USUÁRIO CADASTRADO</h4>
                            <?php } ?>
                        </div>
                    </section>
                </div>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            </div>
           
        </div>
    </div>
    <div class="modal" id="excluir" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="excluir" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header text-center text-uppercase">
                    Deseja desativar o Usuário(a)?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma desativação deste registro?</p>
                    <span id="VDD_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="USU_COD" name="USU_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="deletar" type="button" class="btn btn-dark" value=""><i class="fa fa-ban"></i> CONFIRMAR</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#excluir').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var modal = $(this);
                modal.find('#USU_COD').val(codigo);
                modal.find('#deletar').val(codigo);
                modal.find('#USU_NOME').html(nome);
            });
        });
        $("#deletar").click(function(){
            var data = $('#deletar').val();
            var EMP_COD = $('#EMP_COD').val();
            setTimeout(function () {
                    $('#excluir').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>cadastros/excluir_vendedores', {USU_COD: data,EXCLUIR_USUARIO: true,EMP_COD: EMP_COD,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>cadastros/vendedores"}, 5000);
            });

        });
    </script>
</body>
</html>