<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdMEmp = (is_array($mod_emp) ? count($mod_emp) : 0);
$qtdEmpresas = (is_array($empresas) ? count($empresas) : 0);
?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>modulos/listar">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">MÓDULOS DO SISTEMA</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="container mx-auto col-12 row ">
                        <div class="card bg-2 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS UTILIZADOS PELAS EMPRESAS</h5>
                                <p class="card-text">Verifique quais empresas estao utilizando seus módulos</p>
                                <a href="<?= DIRPAGE ?>modulos/listar" class="btn btn-dark">LISTAR MÓDULOS</a>
                            </div>
                        </div>
                        <div class="card bg-1 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS</h5>
                                <p class="card-text">Cadastre novos módulos</p>
                                <a href="<?= DIRPAGE ?>modulos/cadastro" class="btn btn-dark">CADASTRAR MÓDULO</a>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                        <div class="row col-12 mt-2">
                        </div>  
                </section>
                <section class="container row mx-auto col-12 py-2 mb-5">

                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>