<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($modulos) ? count($modulos) : 0);
$qtdMEmp = (is_array($mod_emp) ? count($mod_emp) : 0);
$qtdEmpresas = (is_array($empresas) ? count($empresas) : 0);
?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>modulos/listar">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">MÓDULOS DO SISTEMA</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="container mx-auto col-12 row ">
                        <div class="card bg-2 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS UTILIZADOS PELAS EMPRESAS</h5>
                                <p class="card-text">Verifique quais empresas estao utilizando seus módulos</p>
                                <a href="<?= DIRPAGE ?>modulos/listar" class="btn btn-dark">LISTAR MÓDULOS</a>
                            </div>
                        </div>
                        <div class="card bg-1 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS</h5>
                                <p class="card-text">Cadastre novos módulos</p>
                                <a href="<?= DIRPAGE ?>modulos/cadastro" class="btn btn-dark">CADASTRAR MÓDULO</a>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                        <div class="row col-12 mt-2">
                        </div>  
                </section>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">

                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>       
                            <th class="text-dark">EMPRESA/MÓDULOS</th>
                            <?php 
                            for ($i= 0; $i < $qtd; $i++) { ?>
                                <th class="text-dark text-center align-middle"><?= $modulos[$i]['MOD_COD'].' - '; ?><?= $modulos[$i]['MOD_NOME']; ?></th>
                            <?php } ?>
                        </thead>
                        <tbody>
                            <?php $d = 1;for ($a = 0; $a < $qtdEmpresas; $a++) { ?>
                                <tr class="mx-auto text-center">
                                    <td class="text-center align-middle"><?= $d; ?></td>
                                    <td class="text-center align-middle"><?= $empresas[$a]['EMP_NOME_FANTASIA']; ?></td>
                                    <?php for ($b= 0; $b < $qtd; $b++) { $ok = false;  ?>
                                    <td class="text-center align-middle mx-auto">
                                        <?php for ($c= 0; $c < $qtdMEmp; $c++) {
                                        if ($empresas[$a]['EMP_COD'] == $mod_emp[$c]['EMP_COD'] && $mod_emp[$c]['MOD_COD'] == $modulos[$b]['MOD_COD']) { $ok = true; } ?>
                                        <?php } ?>   
                                        <?php if ($ok) { ?>
                                            <div class="mx-auto">
                                                <form id="CHECAR" method="post">
                                                    <input class="form-check-input text-center mx-auto checar" type="checkbox" title="Desativar módulo nesta Empresa?" data-empresa="<?= $empresas[$a]['EMP_COD'] ?>" data-modulo="<?= $modulos[$b]['MOD_COD'] ?>" data-status="1" id="flexCheckChecked" checked><i class="bi bi-ban"></i>
                                                </form>
                                            </div>
                                            <?php  } else {  ?>
                                            <div class="mx-auto">
                                                <input class="form-check-input  text-center mx-auto checar" type="checkbox" title="Ativar módulo nesta Empresa?" data-empresa="<?= $empresas[$a]['EMP_COD'] ?>" data-modulo="<?= $modulos[$b]['MOD_COD'] ?>" data-status="1" id="flexCheckChecked"><i class="bi bi-check2"></i>
                                            </div>
                                            <?php } ?>          
                                    </td>    
                                    <?php  } ?>
                                </tr>
                            <?php $d++; } ?>                                 
                           
                        </tbody>
                    </table>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    //jQuery( document ).ready(function() {
                        jQuery(".checar").click(function(){
                           var empresa = jQuery(this).attr("data-empresa");
                           var modulo = jQuery(this).attr("data-modulo");
                           var status = jQuery(this).attr("data-status");
                           $.get('<?= DIRPAGE; ?>modulo_empresa/alterar_modulo_empresa/'+empresa+'/'+modulo+'/'+status, function(retorno) {
                                //console.log(retorno);
                               resposta = JSON.parse(retorno);
                                if (resposta['COD'] !== 'ERRO') {
                                    $('#resposta').addClass('alert alert-success');
                                }else{
                                    $('#resposta').addClass('alert alert-warning');
                                }
                                $('#resposta').html(resposta['MENSAGEM']);
                                setTimeout( () => { window.location.href="<?= DIRPAGE ?>modulos/listar"}, 1200);
                                
                            });
                           
                        });
                </script>
            </div>
        </div>
    </div>
</body>
</html>
