<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'inc/cabecalho.phtml'; 
$qtdME = (is_array($modulos_empresa) ? count($modulos_empresa) : 0);
?>
<body>
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>admin/painel">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> Painel <span class="text-success">Administrativo (USUÁRIO MASTER)</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h1 class="display-5 text-center fw-bolder text-uppercase text-3 mb-2">LC-<span class="text-success">TECH</span></h1>
                            <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p>
                        </div>
                        <div class="col-6 mx-auto">
                            <?php include_once 'app/Views/admin/inc/calendario.phtml'; ?> 
                        </div>
                    </div>
                    <div class="row col-12 mt-2">
                        <?php if ($qtdME != 0) { 
                            for ($i=0; $i < $qtdME; $i++) { ?>
                            <?php if ($modulos_empresa[$i]['MOD_NOME'] == 'ESTOQUE') {
                                if ($qtdE) { ?>
                                    <div class="card  mx-auto text-<?= $modulos_empresa[$i]['MOD_COR']; ?> m-1 py-3" style="max-width: 15rem;">
                                        <a href="<?= DIRPAGE.$modulos_empresa[$i]['MOD_LINK']?>" class="col-auto link-light text-decoration-none">
                                            <div class="card-header"><i class="bi bi-plus-square"></i> <?= $modulos_empresa[$i]['MOD_NOME']; ?></div>
                                            <div class="card-body">
                                                <h5 class="card-title">Módulo de <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                                <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                            </div>
                                        </a>
                                    </div>
                            <?php }
                            }else { ?>
                            <div class="card  mx-auto text-<?= $modulos_empresa[$i]['MOD_COR']; ?> m-1 py-3" style="max-width: 15rem;">
                                <a href="<?= DIRPAGE.$modulos_empresa[$i]['MOD_LINK']?>" class="col-auto link-light text-decoration-none">
                                    <div class="card-header"><i class="bi bi-plus-square"></i> <?= $modulos_empresa[$i]['MOD_NOME']; ?></div>
                                    <div class="card-body">
                                        <h5 class="card-title">Módulo de <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                        <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                    </div>
                                </a>
                            </div>
                            <?php } } } ?>
                            <div class="card  mx-auto opacity-0 bg-orange m-1 py-3" style="max-width: 15rem;">
                                <a href="#<?= DIRPAGE?>configuracoes" class="col-auto link-light text-decoration-none">
                                    <div class="card-header"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</div>
                                    <div class="card-body">
                                        <h5 class="card-title">Módulo de configurações do sistema</h5>
                                        <p class="card-text"></p>
                                    </div>
                                </a>
                            </div>
                            <hr class="my-4 text-dark">

                            <!--
                            <div class="opacity-25 card text-bg-warning mb-3" style="max-width: 18rem;">
                            <div class="card-header">VENDAS</div>
                            <div class="card-body">
                                <h5 class="card-title">Módulo de Controle de Vendas</h5>
                                <p class="card-text"></p>
                            </div>
                            </div>
                            <div class="opacity-25 card text-bg-info mb-3" style="max-width: 18rem;">
                            <div class="card-header">RECURSOS HUMANOS</div>
                            <div class="card-body">
                                <h5 class="card-title">Módulo de Recursos Humanos</h5>
                                <p class="card-text"></p>
                            </div>
                            </div>
                             -->
                        </div>
                    </div>
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>