<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdME = (is_array($modulos) ? count($modulos) : 0);
?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">MÓDULOS DO SISTEMA</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mx-auto m-1">
                        <div class="col-12 text-center text-lg-start opacity-50">
                            <h3 class="fs-5 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span>
                            <p class="lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p></h3>
                        </div>
                    </div>
                    <div class="container mx-auto col-12 row ">
                        <div class="card bg-1 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS</h5>
                                <p class="card-text">Cadastre novos módulos</p>
                                <a href="<?= DIRPAGE ?>lctec/modulos_cadastro/" class="btn btn-dark">CADASTRAR MÓDULO</a>
                            </div>
                        </div>
                        <div class="card bg-2 mx-auto text-center col-6 py-1 mb-2">
                            <div class="card-body text-white">
                                <h5 class="card-title">MÓDULOS UTILIZADOS PELAS EMPRESAS</h5>
                                <p class="card-text">Verifique quais empresas estao utilizando seus módulos</p>
                                <a href="<?= DIRPAGE ?>lctec/modulos_listar/" class="btn btn-dark">LISTAR MÓDULOS</a>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                    <div class="row col-12 mt-2">
                        <?php if ($qtdME != 0) { 
                            for ($i=0; $i < $qtdME; $i++) { ?>
                                <div class="col-12 col-sm-6 col-md-4 rounded-2 text-center mb-2">
                                    <div class="card text-center mx-auto text-uppercase <?= $modulos[$i]['MOD_COR']; ?>">
                                        <a href="<?= DIRPAGE.$modulos[$i]['MOD_LINK']?>" title="Acessar Módulo" class="col-auto link-light text-decoration-none">
                                            <div class="card-header"><?= $modulos[$i]['MOD_ICON']; ?> <?= $modulos[$i]['MOD_NOME']; ?></div>
                                            <div class="card-body">
                                                <h5 class="card-title">Módulo de <?= $modulos[$i]['MOD_NOME']; ?></h5>
                                                <p class="card-text"><?= $modulos[$i]['MOD_DESCRICAO']; ?></p>
                                            </div>
                                        </a>
                                        <?php if($_SESSION['USU_NIVEL'] >= 11 && $_SESSION['USU_NIVEL'] <= 30){ ?>
                                        <div class="card-footer mx-auto row text-center col-12">
                                            <div class="col-6 ">
                                                <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'lctec/modulos_alterar/'.$modulos[$i]['MOD_COD']; ?>" title="Alterar Módulo"><i class="fa fa-edit"></i></a>
                                            </div>
                                            <div class="col-6">
                                                <?= ($modulos[$i]['MOD_STATUS'] == 1)? '<button class="btn btn-sm btn-success" title="Módulo Ativado"><i class="bi bi-bookmark-check"></i></button>' : '<button class="btn btn-sm  btn-danger"><i class="bi bi-ban"></i></button>'; ?></td>
                                            </div>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php  } } ?>
                            <div class="card  mx-auto bg-orange m-1 py-3" style="max-width: 15rem;">
                                <a href="#<?= DIRPAGE?>configuracoes" class="col-auto link-light text-decoration-none">
                                    <div class="card-header"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</div>
                                    <div class="card-body">
                                        <h5 class="card-title">Módulo de configurações do sistema</h5>
                                        <p class="card-text"></p>
                                    </div>
                                </a>
                            </div>
                           

                            <!--
                            <div class="opacity-25 card text-bg-warning mb-3" style="max-width: 18rem;">
                            <div class="card-header">VENDAS</div>
                            <div class="card-body">
                                <h5 class="card-title">Módulo de Controle de Vendas</h5>
                                <p class="card-text"></p>
                            </div>
                            </div>
                            <div class="opacity-25 card text-bg-info mb-3" style="max-width: 18rem;">
                            <div class="card-header">RECURSOS HUMANOS</div>
                            <div class="card-body">
                                <h5 class="card-title">Módulo de Recursos Humanos</h5>
                                <p class="card-text"></p>
                            </div>
                            </div>
                             -->
                        </div>
                    </div>
                    
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>