<?php 
use Libraries\Sessao;
use App\Models\Usuarios;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;

$Usuarios = new Usuarios;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($empresas) ? count($empresas) : 0);
?>
<body class="max-width:100%;max-height:100%;">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral_admin.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo_admin.phtml'; ?>
            
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5">
                            <div class="col-lg-9 row col-xl-9 col-xxl-9">
                                <img src="<?= DIRIMG ?>lctec_fundo_branco2.png" class="col-4 img-fluid" style="width: 150px; height: auto;" alt="..."> 
                                <div class="col-8 my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>lctec">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-1">
                                            <i class="bi bi-house"></i> GERENCIAR <span class="text-success">EMPRESAS E NEGÓCIOS</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao_admin.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container row mx-auto col-12 py-2 mb-5">
                    <div class="row col-12 mt-2">
                        <?php $b = 1; for ($i=0; $i < $qtd; $i++) { ?>
                        <?php $b++; } ?>   
                    </div>  
                </section>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
                <script type="text/javascript">
                    
                </script>
            </div>
        </div>
    </div>
</body>
</html>