<?php

use App\Models\Produtos;
use Libraries\Sessao;

$Produtos = new Produtos;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresa) ? count($empresa) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3 bg-2 ">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none text-white" href="<?= DIRPAGE; ?>estoques">
                                <h5 class="fs-2 fw-bolder text-uppercase"><i class="bi bi-box"></i> Gerenciar <span class="text-success">Estoques</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="col-12 row">
                    <div class="col-7 text-bg-success text-center">
                        <div class="card-body">
                            <h5 class="card-title">MOVIMENTAÇÃO DE ESTOQUES</h5>
                            <p class="card-text">Cadastre/Altere as suas entradas e saídas de produtos</p>
                            <a href="<?= DIRPAGE ?>estoques/movimentacao" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="col-5 text-center">
                        <div class="card-body">
                            <h5 class="card-title">ESTOQUE ATUAL</h5>
                            <p class="card-text">Verifique o estoque atual dos seus produtos</p>
                            <a href="<?= DIRPAGE ?>estoques/produtos_atual" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <!--<div class="col-4 text-bg-success text-center">
                        <div class="card-body">
                            <h5 class="card-title">MOVIMENTAÇÕES</h5>
                            <p class="card-text">Acompanhe as movimentacoes dos produtos</p>
                            <a href="<?php //DIRPAGE ?>estoques/movimentacoes" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>-->
                </div>
            </section>
            <section class="bg-light py-2">
                <div class=" col-11 mx-auto row">
                <hr class="my-4 text-dark">
                <?php
                    if($qtd != 0) {
                    for ($i=0; $i < $qtd; $i++) {  
                        if ($estoques[$i]['EST_STATUS'] == 1) {
                        
                        ?>
                        <div class="card col-5 m-2 text-white mx-auto text-bg-success m-1 py-3" style="max-width: 45rem;">
                            <a href="<?= DIRPAGE.'estoques/produtos/'.$estoques[$i]['EMP_COD'].'/'.$estoques[$i]['EST_COD']; ?>" title="Acessar Estoque" class="col-auto link-light text-decoration-none">
                            <div class="card-header"><i class="bi bi-box"></i> <?= $estoques[$i]['EST_TIPO']; ?></div>
                            <div class="card-body">
                                <div class="row col-12">
                                    <div class="col-8">
                                        <h5 class="card-title">Descrição: <?= $estoques[$i]['EST_DESCRICAO']; ?></h5>
                                        <p class="card-text">Empresa/Negócio: <?= $estoques[$i]['EMP_NOME_FANTASIA']; ?></p>
                                    </div>
                                    <div class="col-4">
                                        <h2 class="card-title">
                                            <?php 
                                                $prod = $Produtos->setCodEmpresa($estoques[$i]['EMP_COD'])->setCodEstoque($estoques[$i]['EST_COD'])->setTipo(1)->setStatus(1)->listarTodosTipo(0);
                                                $qtdP = (is_array($prod) ? count($prod) : 0);
                                                echo $qtdP;
                                            ?>
                                        </h2>
                                        <p class="card-text">Produto(s)</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <div class="col-12 mr-1">
                            <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'cadastros/alteracao_estoques/'.$estoques[$i]['EMP_COD'].'/'.$estoques[$i]['EST_COD']; ?>" title="Alterar estoque"><i class="fa fa-edit"></i></a>
                        </div>
                        <?php }elseif ( $estoques[$i]['EST_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 11) { ?>
                            <div class="card col-5 m-2 text-white mx-auto text-bg-secondary m-1 py-3" style="max-width: 45rem;">
                                <div class="card-header"><i class="bi bi-box"></i> <?= $estoques[$i]['EST_TIPO']; ?></div>
                                <div class="card-body">
                                    <div class="row col-12">
                                        <div class="col-8">
                                            <h5 class="card-title">Descrição: <?= $estoques[$i]['EST_DESCRICAO']; ?></h5>
                                            <p class="card-text">Empresa/Negócio: <?= $estoques[$i]['EMP_NOME_FANTASIA']; ?></p>
                                        </div>
                                        <div class="col-4">
                                            <h2 class="card-title">
                                                <?php 
                                                    $Produtos->setCodEmpresa($estoques[$i]['EMP_COD']);
                                                    $Produtos->setCodEstoque($estoques[$i]['EST_COD']);
                                                    $Produtos->setTipo(1);
                                                    $prod = $Produtos->listarTodosTipo(0);
                                                    $qtdP = (is_array($prod) ? count($prod) : 0);
                                                    echo $qtdP;
                                                ?>
                                            </h2>
                                            <p class="card-text">Produto(s)</p>
                                        </div>
                                    </div>
                                </div>
                                <?php if($_SESSION['USU_NIVEL'] >= 10){ ?>
                                <div class="col-12 mr-1">
                                    <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'cadastros/estoques/'.$estoques[$i]['EMP_COD']; ?>" title="Alterar estoque"><i class="fa fa-edit"></i></a>
                                </div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <?php } }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM ESTOQUE CRIADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>    