<?php 
use Libraries\Sessao;
session_start();

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>estoques/gerenciar/<?= $estoque['EMP_COD']?>/<?= $estoque['EST_COD']?>">
                                <h3 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box"></i> Gerenciar <span class="text-success">Estoque</span></h3></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="col-12 row">
                    <div class="col-12 text-bg-success text-center">
                        <div class="card-body">
                            <h5 class="card-title">SELECIONE O ESTOQUE</h5>
                            <p class="card-text">
                                <select class="form-select" id="buscar_produtos" name="EST_COD">     
                                    <option value="0" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == 0)? 'selected' : '' ?>>---</option>                     
                                    <?php 
                                    for ($i=0; $i < $qtd; $i++) { ?>
                                        <option value="<?= $estoques[$i]['EST_COD'] ?>" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == $estoques[$i]['EST_COD'])? 'selected' : '' ?>><?= $estoques[$i]['EST_DESCRICAO'] ?></option>
                                    <?php } ?>
                                </select>
                            </p>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 bg-3" action="<?= DIRPAGE ?>produtos/cadastrar" method="POST">
                            <div class="row">   
                                <hr class="my-4 text-dark">
                                <h5 class="card-title"><i class="bi bi-box2-fill"></i> PRODUTOS</h5>
                                <div class="card-body" id="retorno">
                                    <select class="form-select" id="produtos" name="PRO_COD">   

                                    </select>
                                </div>
                                <div class="col-4 form-floating mb-2">
                                    <select class="form-select" name="MOV_TIPO">
                                        <option value="0" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 0)? 'selected' : '' ?>>---</option>
                                        <option value="1" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 1)? 'selected' : '' ?>>ENTRADA</option>
                                        <option value="2" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 2)? 'selected' : '' ?>>SAÍDA</option>
                                    </select>
                                    <label class="form-label">TIPO</label>
                                </div>
                                <div class="col-4 form-floating mb-2">
                                    <select class="form-select" name="MOV_MOTIVO">
                                        <option value="0" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 0)? 'selected' : '' ?>>---</option>
                                        <option value="1" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 1)? 'selected' : '' ?>>COMPRA</option>
                                        <option value="2" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 2)? 'selected' : '' ?>>VENDA</option>
                                        <option value="3" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 3)? 'selected' : '' ?>>DEVOLUCÃO</option>
                                        <option value="4" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 4)? 'selected' : '' ?>>PERDA</option>
                                        <option value="5" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 5)? 'selected' : '' ?>>OUTROS</option>
                                    </select>
                                    <label class="form-label">MOTIVO</label>
                                </div>
                                <div class="col-4 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="2" name="PRO_QUANTIDADE" placeholder="0" value="<?= isset($_POST['PRO_QUANTIDADE']) ? $_POST['PRO_QUANTIDADE'] : ''; ?>">
                                    <label class="px-3" for="2">QUANTIDADE</label>
                                </div>
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($estoques['EMP_COD']) ? $estoques['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <a class="col-4 btn btn-lg text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques/"><i class="bi bi-ban"></i> Cancelar</a>
                                <button class="col-8 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVA_MOVIMENTACAO_ESTOQUE" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                                <hr class="my-4 text-dark">
                            </div>
                        </form>
                    </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    
    <script type="text/javascript">
        
        $("#buscar_produtos").change(function(){
            var EST_COD = $(this).find('option:selected').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;
            carregarProdutos(EST_COD, EMP_COD,"#produtos");
        });
        function carregarProdutos(EST_COD, EMP_COD,selecionado="#produtos"){
            $.post('<?= DIRPAGE; ?>estoques/listar_produtos', {PRODUTOS_ESTOQUE: true,EMP_COD: EMP_COD,EST_COD:EST_COD,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                console.log(resposta);
                $(selecionado).find('option').remove().end();
                    $(selecionado).append($('<option>', {
                        value: 0,
                        text: '---'
                }));
                //if (resposta['PROCOD'] !== 'ERRO') {
                   // $('#retorno').addClass('alert alert-success');
                //}else{
                    //$('#retorno').addClass('alert alert-warning');
               // }
               // $('#resposta').html(resposta['MENSAGEM']);
    
            });
        }
    </script>
</body>

</html>    