<?php 
use App\Models\Produtos;
use Libraries\Sessao;
session_start();
$Produtos = new Produtos;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($estoques) ? count($estoques) : 0);
$qtdE = (is_array($empresas) ? count($empresas) : 0);
$qtdM = (is_array($movimentacoes) ? count($movimentacoes) : 0);
?>

<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>estoques/movimentacao">
                                <h3 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box"></i> Movimentação De <span class="text-success">Estoque</span></h3></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="col-12 row">
                    <div class="col-8 mx-auto text-bg-success text-center">
                        <div class="card-body">
                            <h5 class="card-title">SELECIONE O ESTOQUE</h5>
                            <p class="card-text">
                                <select class="form-select" id="buscar_produtos" name="EST_COD">     
                                    <option value="0" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == 0)? 'selected' : '' ?>>---</option>                     
                                    <?php 
                                    for ($i=0; $i < $qtd; $i++) { if ($estoques[$i]['EST_STATUS'] == 1) { ?>
                                        <option value="<?= $estoques[$i]['EST_COD'] ?>" <?= (isset($_POST['EST_COD']) &&  $_POST['EST_COD']  == $estoques[$i]['EST_COD'])? 'selected' : '' ?>><?= $estoques[$i]['EST_DESCRICAO'] ?></option>
                                    <?php } } ?>
                                </select>
                            </p>
                        </div>
                    </div>
                    <hr class="my-4 text-dark">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3" action="<?= DIRPAGE ?>estoques/cadastrar_movimentacao" method="POST">
                            <div class="row">   
                                <h5 class="card-title text-center"><i class="bi bi-box2-fill"></i> MOVIMENTAÇÃO DO PRODUTO</h5>
                                <div class="col-8" id="retorno">
                                    <label class="form-label">SELECIONE O PRODUTO</label>
                                    <select class="form-select" id="produtos" name="PRO_COD">   
                                        <option value="0">SELECIONE UM ESTOQUE</option>
                                    </select>
                                </div>
                                <div class="col-4 mb-2">
                                    <label class="form-label">DATA</label>
                                    <input type="date" name="MOV_DT_MOVIMENTACAO" class="form-control" value="<?= isset($_POST['MOV_DT_MOVIMENTACAO']) ? $_POST['MOV_DT_MOVIMENTACAO'] : date('Y-m-d') ?>">
                                </div>
                                <div class="col-4 form-floating mb-2">
                                    <select class="form-select" name="MOV_TIPO">
                                        <option value="0" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 0)? 'selected' : '' ?>>---</option>
                                        <option value="1" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 1)? 'selected' : '' ?>>ENTRADA</option>
                                        <option value="2" <?= (isset($_POST['MOV_TIPO']) &&  $_POST['MOV_TIPO']  == 2)? 'selected' : '' ?>>SAÍDA</option>
                                    </select>
                                    <label class="form-label">TIPO</label>
                                </div>
                                <div class="col-4 form-floating mb-2">
                                    <select class="form-select" name="MOV_MOTIVO">
                                        <option value="0" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 0)? 'selected' : '' ?>>---</option>
                                        <option value="1" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 1)? 'selected' : '' ?>>COMPRA</option>
                                        <option value="2" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 2)? 'selected' : '' ?>>VENDA</option>
                                        <option value="3" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 3)? 'selected' : '' ?>>AJUSTE</option>
                                        <option value="4" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 4)? 'selected' : '' ?>>DEVOLUÇÃO CLIENTE</option>
                                        <option value="5" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 5)? 'selected' : '' ?>>DEVOLUÇÃO FORNECEDOR</option>
                                        <option value="6" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 6)? 'selected' : '' ?>>PERDA</option>
                                        <option value="7" <?= (isset($_POST['MOV_MOTIVO']) &&  $_POST['MOV_MOTIVO']  == 7)? 'selected' : '' ?>>OUTROS</option>
                                    </select>
                                    <label class="form-label">MOTIVO</label>
                                </div>
                                <div class="col-4 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="2" name="MOV_QUANTIDADE" placeholder="0" value="<?= isset($_POST['MOV_QUANTIDADE']) ? $_POST['MOV_QUANTIDADE'] : ''; ?>">
                                    <label class="px-3" for="2">QUANTIDADE</label>
                                </div>
                                <div class="col-12 mb-2 " style="height:100px">
                                    <label for="address2" class="form-label">DESCRIÇÃO</label>
                                    <textarea type="text" class="form-control  maiusculo" name="MOV_DESCRICAO"><?= isset($_POST['MOV_DESCRICAO'])? $_POST['MOV_DESCRICAO']  : '' ?></textarea>
                                </div>
                                <input type="hidden" class="form-control" id="EST_COD" name="EST_COD" value="">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <a class="col-4 btn btn-lg text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-ban"></i> Cancelar</a>
                                <button class="col-8 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVA_MOVIMENTACAO_ESTOQUE" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                            </div>
                        </form>
                    </div>
            </section>
            <section class="bg-light text-dark">
                <div class="container mx-auto col-12 px-2 py-2 row ">
                <?php ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">ESTOQUE</th>
                            <th class="text-dark">CÓDIGO</th>
                            <th class="text-dark">PRODUTO</th>
                            <th class="text-dark">DATA</th>
                            <th class="text-dark">ENTRADA</th>
                            <th class="text-dark">SAÍDA</th>
                            <th class="text-dark">MOTIVO</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Ações</th>
                        </thead>
                        <tbody>
                            <?php $b = 1; for ($i=0; $i < $qtdM; $i++) { 
                                 $data = new DateTime($movimentacoes[$i]['MOV_DT_MOVIMENTACAO']);
                                ?>
                            <tr class="<?= ($movimentacoes[$i]['MOV_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['EST_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $movimentacoes[$i]['PRO_COD']; ?></td>
                                <td class="text-center align-middle">
                                    <?php $produto = $Produtos->setCodEmpresa($movimentacoes[$i]['EMP_COD'])->setCodEstoque($movimentacoes[$i]['EST_COD'])->setCodigo($movimentacoes[$i]['PRO_COD'])->listar(0);
                                    echo $produto['PRO_NOME'];
                                    ?>
                                </td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <?= ($movimentacoes[$i]['MOV_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span></td><td></td>' : '<td></td><td class="text-center align-middle"><span class="text-danger">'.$movimentacoes[$i]['MOV_QUANTIDADE'].'</span>'; ?></td>
                                <td class="text-center align-middle">

                                    <?= $movimentacoes[$i]['MOV_MOTIVO']; ?>
                                
                                </td>
                                <td class="text-center align-middle"><?= ($movimentacoes[$i]['MOV_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
                                    <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'estoque/alteracao_movimentacao/'.$movimentacoes[$i]['EMP_COD'].'/'.$movimentacoes[$i]['EST_COD'].'/'.$movimentacoes[$i]['MOV_COD']; ?>" title="Alterar movimentacao"><i class="fa fa-edit"></i></a>
                                    <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="" data-codigo="<?= $movimentacoes[$i]['COL_COD']; ?>" data-estoque="<?= $movimentacoes[$i]['EST_COD']; ?>"  data-status="<?= $movimentacoes[$i]['MOV_STATUS']; ?>" title="Deseja excluir?" ><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                        <?php $b++; } ?>
                    </table>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    
    <script type="text/javascript">
        
        $("#buscar_produtos").change(function(){
            var EST_COD = $(this).find('option:selected').val();
            var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;
            carregarProdutos(EST_COD, EMP_COD,"#produtos");
        });
        function carregarProdutos(EST_COD, EMP_COD,selecionado="#produtos"){
            $.post('<?= DIRPAGE; ?>estoques/listar_produtos', {PRODUTOS_ESTOQUE: true,EMP_COD: EMP_COD,EST_COD:EST_COD,cache: false}, function(retorno) {
                
                var dados = JSON.parse(retorno);
                
                $(selecionado).find('option').remove().end();
                    $(selecionado).append($('<option>', {
                        value: 0,
                        text: '---'
                }));
                //console.log(dados);
                document.getElementById("EST_COD").value ='';
                document.getElementById("EST_COD").value = EST_COD;
                

               
                for(var i=0;dados.length>i;i++){
                    $(selecionado).append($('<option>', {
                        value: dados[i].PRO_COD,
                        text: dados[i].PRO_NOME
                    }));
                    console.log(codificarHtml(dados[i].PRO_NOME))
                }
                function codificarHtml(texto){
                    var htmlCodigo = { 
                                '&aacute;' : {'code' : 'á'},
                                '&Aacute;' : {'code' : 'Á'},
                                '&atilde;' : {'code' : 'ã'},
                                '&Atilde;' : {'code' : 'Ã'},
                                '&agrave;' : {'code' : 'à'},
                                '&Agrave;' : {'code' : 'À'},                       
                                '&eacute;' : {'code' : 'é'},
                                '&Eacute;' : {'code' : 'É'},
                                '&iacute;' : {'code' : 'í'},
                                '&Iacute;' : {'code' : 'Í'},
                                '&oacute;' : {'code' : 'ó'},
                                '&Oacute;' : {'code ': 'Ó'}, 
                                '&otilde;' : {'code' : 'õ'},
                                '&Otilde;' : {'code' : 'Õ'},
                                '&uacute;' : {'code' : 'ú'},
                                '&Uacute;' : {'code' : 'Ú'},
                                '&ccedil;' : {'code' : 'ç'},
                                '&Ccedil;' : {'code' : 'Ç'}                      };
                    var acentos = ['á', 'Á', 'ã', 'Ã', 'à', 'À', 'é', 'É', 'í', 'Í', 'ó', 'Ó', 'õ', 'Õ', 'ú', 'Ú', 'ç', 'Ç'];
                    
                    for(var i=0; i<acentos.length; i++){
                        if(htmlCodigo [acentos[i]] != undefined){
                            texto = texto.replaceAll(acentos[i], htmlCodigo[acentos[i]].code );
                        }
                    }
                    return texto;
                }

               
                //if (resposta['PROCOD'] !== 'ERRO') {
                   // $('#retorno').addClass('alert alert-success');
                //}else{
                    //$('#retorno').addClass('alert alert-warning');
               // }
               // $('#resposta').html(resposta['MENSAGEM']);
    
            });
        }
    </script>
</body>

</html>    