<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($conta) ? count($conta) : 0);
$qtdF = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>contas/depositos/<?= $conta['EMP_COD'] ?>/<?= $conta['CTA_COD'] ?>">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Conta <span class="text-success"> <?= $conta['CTA_NOME'] ?></span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
            <section class="bg-light py-2">
                <div class="container col-12 px-2 py-2 mx-auto row">
                    <?php if ($qtd) { ?>
                    <div class="p-2 text-center bg-body-tertiary rounded-3">
                        <h1 class="text-body-emphasis"><?= $conta['CTA_DESCRICAO'] ?></h1>
                        <p class="lead text-center ">
                        </p>
                    </div>

                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 " action="<?= DIRPAGE ?>contas/depositar" method="POST">
                            <div class="row">    
                                <div class="col-4 form-floating mb-3">
                                    <div class="form-floating">
                                        <input type="text" class="form-control" disabled value="ENTRADA">
                                        <label class="px-3" for="1">TIPO DE MOV.</label>
                                    </div>
                                </div>   
                                <div class="col-4 mb-3">
                                   
                                    <div class="input-group form-floating">    
                                        
                                        <span class="input-group-text">R$</span>  
                                        <input type="text" class="form-control form-control-lg real" id="" name="TRS_VALOR_TOTAL" placeholder="" value="<?= isset($_POST['TRS_VALOR']) ? $_POST['TRS_VALOR'] : '0,00'; ?>">
                                    </div>
                                </div>
                                <div class="col-4 form-floating mb-3">
                                    
                                    <div class="form-floating">
                                        <input type="date" class="form-control form-control-lg" name="TRS_DATA" placeholder="" value="<?= isset($_POST['TRS_DATA']) ? $_POST['TRS_DATA'] : date('Y-m-d'); ?>">
                                        <label class="px-3" for="2">DATA</label>
                                    </div> 
                                </div> 
                                <div class="col-6">
                                        <div class=" mb-3">
                                            <label class="form-label">FORMA DE PAGAMENTO</label>
                                            <div class="form-floating mb-3">
                                                <select class="form-select text-uppercase mb-3 form-floating" name="FPG_COD">
                                                    <option value="0" <?= (isset($_POST['FPG_COD']) &&  $_POST['FPG_COD']  == "0")? 'selected' : '' ?>>---</option>
                                                    <?php for ($i= 0; $i < $qtdF; $i++) { if ($formas_pagamentos[$i]['FPG_STATUS'] == 1) { ?> 
                                                        <option value="<?= $formas_pagamentos[$i]['FPG_COD']; ?>" <?= (isset($_POST['FPG_COD']) &&  $_POST['FPG_COD']  == $formas_pagamentos[$i]['FPG_COD'] )? 'selected' : '' ?>><?= $formas_pagamentos[$i]['FPG_DESCRICAO'] ?></option>
                                                    <?php } } ?> 
                                                </select>
                                                <label class="form-floating mb-3">FORMA DE PAGAMENTO</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 mb-3">
                                        <label class="form-label">CLASSIFICAÇÃO</label>
                                        <div class="form-floating mb-3">
                                            <select class="form-select text-uppercase mb-3 form-floating" name="CLA_COD">
                                                <option value="0" <?= (isset($_POST['CLA_COD']) &&  $_POST['CLA_COD']  == "0")? 'selected' : '' ?>>---</option>
                                                <?php for ($i= 0; $i < $qtdCL; $i++) { if ($classificacoes[$i]['CLA_STATUS'] == 1) { ?> 
                                                    <option value="<?= $classificacoes[$i]['CLA_COD']; ?>" <?= (isset($_POST['CLA_COD']) &&  $_POST['CLA_COD']  == $classificacoes[$i]['CLA_COD'] )? 'selected' : '' ?>><?= $classificacoes[$i]['CLA_DESCRICAO'] ?></option>
                                                <?php } } ?> 
                                            </select>
                                            <label class="form-floating mb-3">CLASSIFICAÇÃO (opcional)</label>
                                        </div>
                                    </div>
                                <div class="col-12 mb-3">
                                   
                                    <div class="form-floating">
                                        <input type="text" class="form-control maiusculo" id="1" name="TRS_DESCRICAO" placeholder="" value="<?= isset($_POST['TRS_DESCRICAO']) ? $_POST['TRS_DESCRICAO'] :''; ?>">
                                        <label class="form-floating" for="1">DESCRIÇÃO</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <input type="hidden" class="form-control" name="TRS_TIPO" value="1">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="CTA_COD" value="<?= isset($conta['CTA_COD']) ? $conta['CTA_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVA_TRANSACAO" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                            </div> 
                        </form>
                    <?php } else { ?>
                        NENHUMA CONTA LOCALIZADA
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="<?= DIRJS ?>jquery.maskMoney.js"></script>
    <script>
        $(document).ready(function(){

            $('.real').maskMoney({
                prefix:'',
                allowNegative: true,
                thousands:'', decimal:'.',
                affixesStay: true
            });
        })
    </script>
</body>
</html>    