<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($conta) ? count($conta) : 0);
$qtdT = (is_array($transacoes_conta) ? count($transacoes_conta): 0);
$qtdTE = (is_array($transacoes_conta_entradas) ? count($transacoes_conta_entradas): 0);
$qtdTS = (is_array($transacoes_conta_saidas) ? count($transacoes_conta_saidas): 0);
$somaE = $somaS = 0;
for ($i=0; $i < $qtdTE; $i++) { $somaE += $transacoes_conta_entradas[$i]['TRS_VALOR_TOTAL'];}
for ($i=0; $i < $qtdTS; $i++) { $somaS += $transacoes_conta_saidas[$i]['TRS_VALOR_TOTAL'];}
//dump($transacoes_conta_entradas);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                <?= $modulo[0]['MOD_ICON'] ?> Conta <span class="text-dark"> <?= $conta['CTA_TIPO'] ?></span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
            <section class="bg-light py-2">
                <div class="container col-12 px-2 py-2 mx-auto row">
                    <?php if ($qtd) { ?>
                    <div class="p-2 text-center bg-body-tertiary rounded-3">
                        <h1 class="text-body-emphasis"><?= $conta['CTA_DESCRICAO'] ?></h1>
                        <p class="lead text-center ">
                        </p>
                    </div>
                    <div class="col-11 row mx-auto">
                        <div class="card col bg-success m-1">
                            <div class="card-body text-white">
                                <h5 class="card-title">ENTRADAS <i class="bi bi-arrow-down-square"></i></h5>
                                <p class="card-text "><h2> <i class="bi bi-plus-square"></i> R$ <?= $somaE ?></h2></p>
                            </div>
                        </div>
                        <div class="card col bg-danger m-1">
                            <div class="card-body text-white">
                                <h5 class="card-title">SAÍDAS <i class="bi bi-arrow-up-square"></i></h5>
                                <p class="card-text"><h2> <i class="bi bi-dash-square"></i> R$ <?= $somaS ?></h2></p>
                            </div>
                        </div>
                        <div class="card col m-1">
                            <div class="card-body">
                                <h5 class="card-title">SALDO <i class="bi bi-currency-dollar"></i></h5>
                                <p class="card-text"><h2> <i class="bi bi-plus-square"></i> R$ <?= $conta['CTA_SALDO'] ?></h2></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 row mt-4 mx-auto text-center">
                        <p class="text-center fs-3">MOVIMENTAÇÃO <hr class="my-1 text-dark"></p>
                        <div class="col-4 text-bg-success text-center">
                            <div class="card-body">
                                <h5 class="card-title">DEPOSITAR</h5>
                                <p class="card-text">Deposite valores na conta Empresa/negócio</p>
                                <a href="<?= DIRPAGE ?>contas/depositos/<?= $conta['EMP_COD'] ?>/<?= $conta['CTA_COD'] ?>" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-bg-danger text-center">
                            <div class="card-body">
                                <h5 class="card-title">RETIRAR</h5>
                                <p class="card-text">Retire valores da conta Empresa/negócio</p>
                                <a href="<?= DIRPAGE ?>contas/saques/<?= $conta['EMP_COD'] ?>/<?= $conta['CTA_COD'] ?>" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-bg-secondary text-center">
                            <div class="card-body">
                                <h5 class="card-title">TRANSFERIR</h5>
                                <p class="card-text">Envie valores para outra conta cadastrada no sistema</p>
                                <a href="<?= DIRPAGE ?>contas/transferencias/<?= $conta['EMP_COD'] ?>/<?= $conta['CTA_COD'] ?>" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                    </div>
                    <?php } else { ?>
                        NENHUMA CONTA LOCALIZADA
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>    