<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($contas) ? count($contas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>contas">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                <?= $modulo[0]['MOD_ICON'] ?> Listagem de <span class="text-dark">Contas</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
            <section class="bg-light py-2">
                <div class="container col-10 px-2 py-2 mx-auto row">
                <?php
                    if($qtd != 0) {
                    for ($i=0; $i < $qtd; $i++) {  ?>
                    <div class="card text-white mx-auto text-bg-secondary m-1 py-3" style="max-width: 35rem;">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-10 fs-5 align-middle">
                                    <i class="bi bi-box"></i> <?= ($contas[$i]['CTA_TIPO'] != '0')? (($contas[$i]['CTA_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?>
                                </div>  
                                <div class="col-1 mr-1">
                                    <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'contas/alteracao/'.$contas[$i]['EMP_COD'].'/'.$contas[$i]['CTA_COD']; ?>" title="Alterar conta"><i class="fa fa-edit"></i></a>
                                </div>
                            </div>  
                        </div>
                        <div class="card-body">
                            <a href="<?= DIRPAGE.'contas/detalhar/'.$contas[$i]['EMP_COD'].'/'.$contas[$i]['CTA_COD']; ?>" title="Acessar Conta" class="col-auto link-light text-decoration-none">
                                <div class="row">
                                    <div class="col-12">
                                        <h5 class="card-title">Descrição: <?= $contas[$i]['CTA_DESCRICAO']; ?></h5>
                                        <p class="card-text">Empresa/Negócio: <?= $contas[$i]['EMP_NOME_FANTASIA']; ?></p>
                                    </div>
                                    <div class="col-12 mx-auto text-center">
                                        <h2 class="card-title">
                                            
                                        </h2>
                                        <p class="card-text ">ACESSAR</p>
                                    </div>
                                </div>
                            </a>  
                        </div>
                    </div>
                    <?php } }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA CONTA CRIADA</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>    