<?php
use Libraries\Sessao;
session_start();

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($colaboradores) ? count($colaboradores) : 0);
$qtdCS = (is_array($cargos_salarios) ? count($cargos_salarios) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
?>
<body>
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                    <header class="py-3">
                        <section class="container px-3">
                            <div class="row gx-5 align-items-center justify-content-center">
                                <div class="col-lg-9 col-xl-9 col-xxl-9">
                                    <div class="my-1 px-4 mx-auto">
                                        <a class="text-decoration-none" href="<?= DIRPAGE; ?>colaboradores">
                                            <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                                <i class="bi bi-person-bounding-box"></i> Gerenciar <span class="text-success">Colaboradores</span>
                                            </h5>
                                        </a>
                                    </div>
                                </div>
                                <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                            </div>
                        </section>
                        <section class="container col-12 mx-auto px-5">
                            <?= $breadcrumb ?>
                        </section>
                    </header>
                    <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                    <section class="bg-light  text-dark  py-2">
                        <div class="container mx-auto col-12 px-2 py-2 row">
                            <div class="card bg-success text-center py-2 mb-4" style="width: 100rem;">
                                <div class="card-body  text-white">
                                    <h5 class="card-title">COLABORADORES</h5>
                                    <p class="card-text">Cadastre os seus Colaboradores no sistema</p>
                                    <a href="<?= DIRPAGE ?>colaboradores/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                                </div>
                            </div>
                        <?php if ($qtd != 0) { ?>
                            <table class="table table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th class="text-dark">#</th>
                                    <th class="text-dark">Nome</th>
                                    <th class="text-dark">Email</th>
                                    <th class="text-dark">1º Tel.</th>
                                    <th class="text-dark">Nível</th>
                                    <th class="text-dark">Comissão</th>
                                    <th class="text-dark">Setor</th>
                                    <th class="text-dark">Cargo</th>
                                    <th class="text-dark">Status</th>
                                    <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                                </thead>
                                <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="<?= ($colaboradores[$i]['COL_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= $colaboradores[$i]['COL_NOME'].' '.$colaboradores[$i]['USU_SOBRENOME']; ?></td>
                                        <td class="text-center align-middle"><?= $colaboradores[$i]['COL_EMAIL']; ?></td>
                                        <td class="text-center align-middle"><?= $colaboradores[$i]['COL_TEL_1']; ?></td>
                                        <td class="text-center align-middle"><?= $colaboradores[$i]['COL_NIVEL']; ?></td>
                                        <td class="text-center align-middle"><?= $colaboradores[$i]['COL_COMISSAO']; ?></td>
                                        <td class="text-center align-middle">
                                        <?php 
                                            if($colaboradores[$i]['SET_COD'] != 0 or $colaboradores[$i]['SET_COD'] != '') {
                                                for ($c = 0; $c < $qtdCS; $c++) { 
                                                    if ($setores[$c]['SET_COD'] == $colaboradores[$i]['SET_COD']) { ?>
                                                    <?= $setores[$c]['SET_DESCRICAO']; ?>   
                                                <?php } } ?> 
                                            <?php }else { ?>
                                                À DEFINIR
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center align-middle">
                                        <?php 
                                            if($colaboradores[$i]['CGS_COD'] != 0) {
                                                for ($c = 0; $c < $qtdCS; $c++) { 
                                                    if ($cargos_salarios[$c]['CGS_COD'] == $colaboradores[$i]['CGS_COD']) { ?>
                                                    <?= $cargos_salarios[$c]['CGS_NOME']; ?>   
                                                <?php } } ?> 
                                            <?php }else { ?>
                                                À DEFINIR
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center align-middle"><?= ($colaboradores[$i]['COL_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                        <td class="text-center align-middle">

                                            <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'colaboradores/alteracao/'.$colaboradores[$i]['EMP_COD'].'/'.$colaboradores[$i]['COL_COD']; ?>" title="Alterar colaborador"><i class="fa fa-edit"></i></a>
                                            
                                            <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#excluir" title="Excluir vendedor" data-codigo="<?= $colaboradores[$i]['COL_COD']; ?>" data-nome="<?= $colaboradores[$i]['COL_NOME']; ?>" title="Deseja excluir?" ><i class="fa fa-ban"></i></button>
                                        </td>
                                        <?php } ?>
                                    </tr>
                                <?php $b++; } ?>
                                </tbody>
                            </table>
                        <?php }else { ?>
                            <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM COLABORADOR(A) CADASTRADO</h4>
                        <?php } ?>
                        </div>
                    </section>
                </div>
                <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            </div>
            
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <div class="modal" id="excluir" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="excluir" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header text-center text-uppercase">
                    Deseja excluir o Vendedor(a)?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma exclusão deste registro?</p>
                    <span id="COL_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="COL_COD" name="COL_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="deletar" type="button" class="btn btn-danger" value=""><i class="fa fa-trash"></i> DELETAR</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#excluir').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var modal = $(this);
                modal.find('#COL_COD').val(codigo);
                modal.find('#deletar').val(codigo);
                modal.find('#COL_NOME').html(nome);
            });
        });
        $("#deletar").click(function(){
            var data = $('#deletar').val();
            var EMP_COD = $('#EMP_COD').val();
            setTimeout(function () {
                    $('#excluir').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>calaboradores/status', {COL_COD: data,EXCLUIR_VENDEDOR: true,EMP_COD: EMP_COD,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>colaboradores"}, 3000);
            });

        });
    </script>
</body>
</html>