<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdF = (is_array($fornecedores) ? count($fornecedores) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);;
$qtd = (is_array($produto) ? count($produto) : 0);

?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-3 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>produtos/detalhar/<?= $produto['EMP_COD']?>/<?= $produto['EST_COD']?>/<?= $produto['PRO_COD']?>">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box2-fill"></i> Detalhar <span class="text-success"> Produto</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <section class="bg-light py-2">
                    <div class="col-12 mx-auto text-center m-1">
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                    </div>
                    <div class="container col-11 mx-auto row">
                        <div class="py-1">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
                                            <h4><b>NOME:</b></h4>
                                        </td>
                                        <td colspan="4">
                                            <h3 class="display-4 fw-bold"><?= $produto['PRO_NOME'] ?></h3>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <h4><b>PREÇO DE CUSTO:</b></h4>
                                        </td>
                                        <td>
                                            <h3 class="display-4 fw-bold"><?= $produto['PRO_PRECO_UNITARIO'] ?></h3>
                                        </td>
                                        <td>
                                            <h4><b>PREÇO DE VENDA:</b></h4>
                                        </td>
                                        <td>
                                            <h3 class="display-4 fw-bold"><?= $produto['PRO_PRECO_VENDA'] ?></h3>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <h4><b>QUANTIDADE ATUAL:</b></h4></td>
                                        <td>
                                            <h3 class="display-4 fw-bold"><?= ($produto['PRO_QUANTIDADE'] < $produto['PRO_QTD_MIN'])? '<span title="Produto abaixo do estoque mínimo definido" class="bagde bg-warning">'.$produto['PRO_QUANTIDADE'].'</span>' : $produto['PRO_QUANTIDADE']; ?></h3>
                                        </td>
                                        <td>
                                            <h4><b>QUANTIDADE MIN:</b></h4>
                                        </td>
                                        <td>
                                            <h3 class="display-4 fw-bold"><?= $produto['PRO_QTD_MIN'] ?></h3>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h4><b>DESCRIÇÃO:</b></h4>
                                        </td>
                                        <td colspan="4">
                                             <?= $produto['PRO_DESCRICAO'] ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <h4><b>CATEGORIA:</b></h4>
                                        </td>
                                        <td colspan="4">
                                            <button class="btn btn-success btn-sm" type="button">
                                                <?php for ($c = 0; $c < $qtdC; $c++) { 
                                                    if ($categorias[$c]['CAT_COD'] == $produto['CAT_COD']) { ?>
                                                    <?= $categorias[$c]['CAT_DESCRICAO']; ?>   
                                                <?php } } ?>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5">
                                            <h4><b>VENDAS EFETUADAS:</b></h4>
                                        </td>
                                    </tr>
                                    </tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="<?= DIRJS ?>jquery.maskMoney.js"></script>
        </div>
    </div>
   
    </body>
</html>