<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdF = (is_array($fornecedores) ? count($fornecedores) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
$qtd = (is_array($produto) ? count($produto) : 0);
$qtdMP = (is_array($movimentacoes_produto) ? count($movimentacoes_produto) : 0);

?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-3 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>produtos/detalhar/<?= $produto['EMP_COD']?>/<?= $produto['EST_COD']?>/<?= $produto['PRO_COD']?>">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box2-fill"></i> Detalhar <span class="text-success"> Produto</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <section class="bg-light py-2">
                    <div class="col-12 mx-auto row text-center p-3">
                        <div class="col-4 mx-auto text-center text-bg-success">
                            <div class="card-body">
                                <h5 class="card-title">ESTOQUE ATUAL</h5>
                                <p class="card-text">Verifique o estoque atual dos seus produtos</p>
                                <a href="<?= DIRPAGE ?>estoques/produtos_atual" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>    
                        <div class="col-4 mx-auto text-center">
                            <div class="card-body">
                                <h5 class="card-title">LISTAR MOVIMENTAÇÃO DE ESTOQUES</h5>
                                <p class="card-text">Veja as entradas e saídas de produtos</p>
                                <a href="<?= DIRPAGE ?>movimentacoes/listar" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="col-4 text-bg-success text-center">
                            <div class="card-body">
                                <h5 class="card-title">MOVIMENTAÇÃO DE ESTOQUES</h5>
                                <p class="card-text">Cadastre/Altere as suas entradas e saídas de produtos</p>
                                <a href="<?= DIRPAGE ?>movimentacoes" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                        <div class="mx-auto text-center">
                            <a class="col-5 btn btn-sm m-3 text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                            <a class="col-5 btn btn-sm m-3 text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques/produtos/<?= $produto['EMP_COD']?>/<?= $produto['EST_COD']?>"><i class="bi bi-arrow-left"></i> VOLTAR AOS PRODUTOS</a>
                        </div>
                    </div>
                    <div class="container col-11 mx-auto row">
                        <ul class="nav nav-tabs" id="produtos" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="PRO_COD" data-bs-toggle="tab" data-bs-target="#PRO_COD" type="button" role="tab" aria-controls="PRO_COD" aria-selected="true">DAODS</button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="VEN_COD" data-bs-toggle="tab" data-bs-target="#VEN_COD" type="button" role="tab" aria-controls="VEN_COD" aria-selected="false">VENDAS</button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">COMPRAS</button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled-tab-pane" type="button" role="tab" aria-controls="disabled-tab-pane" aria-selected="false" disabled>OUTROS</button>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="PRO_COD" role="tabpanel" aria-labelledby="PRO_COD" tabindex="0">
                                <div class="bg-body-tertiary p-5 rounded">
                                    <h3><?= $produto['PRO_NOME'] ?></h3>
                                    <p class="lead"><?= $produto['PRO_DESCRICAO'] ?></p>
                                    <a class="btn btn-lg btn-primary" href="/docs/5.3/components/navbar/" role="button">View navbar docs »</a>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="VEN_COD" role="tabpanel" aria-labelledby="VEN_COD" tabindex="0">
                            
                            </div>
                            <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
                        </div>
                        <div class="py-1">
                           
                        </div>
                    </div>
                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="<?= DIRJS ?>jquery.maskMoney.js"></script>
        </div>
    </div>
   
    </body>
</html>