<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($produtos) ? count($produtos) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);

?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>estoques/produtos/<?= $estoque['EMP_COD']?>/<?= $estoque['EST_COD']?>">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-box2-fill"></i> Listagem de <span class="text-success">Produtos</span></h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                    </div>
                </section>
                <section class="mx-auto px-3">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light text-dark">
                <div class="container mx-auto col-12 px-2 py-2 row ">
                    <div class="card bg-success mx-auto text-center col-12 py-1 mb-2">
                        <div class="card-body text-white">
                            <h5 class="card-title">PRODUTOS</h5>
                            <p class="card-text">Cadastre seus produtos</p>
                            <a href="<?= DIRPAGE ?>produtos/cadastro/<?= $estoque['EMP_COD']?>/<?= $estoque['EST_COD']?>" class="btn btn-dark">CADASTRAR PRODUTO</a>
                        </div>
                    </div>
                    <div class="col-12 mx-auto text-center m-1">
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>movimentacoes"><i class="bi bi-arrow-left"></i> VOLTAR AS MOVIMENTAÇÕES</a>   
                        <a class="col-4 btn btn-sm text-uppercase btn-secondary" href="<?= DIRPAGE; ?>estoques"><i class="bi bi-arrow-left"></i> VOLTAR AOS ESTOQUES</a>
                    </div>
                <?php if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">ESTOQUE</th>
                            <th class="text-dark">TIPO</th>
                            <th class="text-dark">CÓDIGO</th>
                            <th class="text-dark">REFERÊNCIA</th>
                            <th class="text-dark">CATEGORIA</th>
                            <th class="text-dark">NOME</th>
                            <th class="text-dark">QTD</th>
                            <th class="text-dark">PREÇO UNITÁRIO</th>
                            <th class="text-dark">PREÇO VENDA</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Ações</th>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) { ?>
                            <tr class="<?= ($produtos[$i]['PRO_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?>
                                    <a type="button" class="btn btn-outline-secondary btn-sm d-print-none" href="<?= DIRPAGE.'produtos/detalhar/'.$produtos[$i]['EMP_COD'].'/'.$produtos[$i]['EST_COD'].'/'.$produtos[$i]['PRO_COD']; ?>" title="Detalhar produto"><i class="bi bi-eye"></i></a>
                                </td>
                                <td class="text-center align-middle"><?= $produtos[$i]['EST_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= ($produtos[$i]['PRO_TIPO'] == 1)? 'PRODUTO': (($produtos[$i]['PRO_TIPO'] == 2) ? 'SERVIÇO' : 'N.I.'); ?></td>
                                <td class="text-center align-middle"><?= $produtos[$i]['PRO_CODIGO']; ?></td>
                                <td class="text-center align-middle"><?= $produtos[$i]['PRO_REFERENCIA']; ?></td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($produtos[$i]['CAT_COD'] != 0 or $produtos[$i]['CAT_COD'] != '') {
                                        for ($c = 0; $c < $qtdC; $c++) { 
                                            if ($categorias[$c]['CAT_COD'] == $produtos[$i]['CAT_COD']) { ?>
                                            <?= $categorias[$c]['CAT_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle"><?= $produtos[$i]['PRO_NOME']; ?></td>
                                <td class="text-center align-middle"><?= $produtos[$i]['PRO_QUANTIDADE']; ?></td>
                                <!--<td class="text-center align-middle"><?php //= number_format($produtos[$i]['PRO_PRECO_UNITARIO'],2,',','.'); ?></td>
                                <td class="text-center align-middle"><?php //= number_format($produtos[$i]['PRO_PRECO_VENDA'],2,',','.'); ?></td>-->
                                <td class="text-center align-middle">R$ <?= $produtos[$i]['PRO_PRECO_UNITARIO']; ?></td>
                                <td class="text-center align-middle">R$ <?= $produtos[$i]['PRO_PRECO_VENDA']; ?></td>
                                <td class="text-center align-middle"><?= ($produtos[$i]['PRO_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
                                    <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'produtos/alteracao/'.$produtos[$i]['EMP_COD'].'/'.$produtos[$i]['EST_COD'].'/'.$produtos[$i]['PRO_COD']; ?>" title="Alterar produto"><i class="fa fa-edit"></i></a>
                                    <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="" data-codigo="<?= $produtos[$i]['PRO_COD']; ?>" data-nome="<?= $produtos[$i]['PRO_NOME']; ?>" data-estoque="<?= $produtos[$i]['EST_COD']; ?>"  data-status="<?= $produtos[$i]['PRO_STATUS']; ?>" title="Deseja excluir?" ><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">ESTOQUE SEM  NENHUM PRODUTO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    Deseja desativar o produto?
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="PRO_NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="PRO_STATUS" name="PRO_STATUS" value="" />
                    <input type="hidden" id="PRO_COD" name="PRO_COD" value="" />
                    <input type="hidden" id="EST_COD" name="EST_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var estoque = button.data('estoque');
                var modal = $(this);
                modal.find('#PRO_COD').val(codigo);
                modal.find('#PRO_STATUS').val(status);
                modal.find('#EST_COD').val(estoque);
                modal.find('#sts').val(codigo);
                modal.find('#PRO_NOME').html(nome);

                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Produto?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja reativar o Produto?');
                }
            });
        });
        $("#sts").click(function(){
            var PRO_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var EST_COD = $('#EST_COD').val();
            var PRO_STATUS = $('#PRO_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>produtos/status', {PRO_COD: PRO_COD,STATUS_PRODUTO: true,EMP_COD: EMP_COD,EST_COD:EST_COD,PRO_STATUS: PRO_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>estoques/produtos/"+EMP_COD+"/"+EST_COD}, 100);
            });

        });
    </script>
</body>
</html>