<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($categorias) ? count($categorias) : 0);
$qtdS = (is_array($setores) ? count($setores) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
$ca = array(
    0 => 'A DEFINIR',
    1 => 'CATEGORIAS',
    2 => 'COLABORADORES',
    3 => 'CLIENTES',
    4 => 'ESTOQUES',
    5 => 'FORNECEDORES',
    6 => 'LANÇAMENTOS',
    7 => 'OUTROS',
    8 => 'PRODUTOS',
    9 => 'SERVIÇOS',
    10 =>'TAREFAS'
);

$qtdCA = (is_array($ca) ? count($ca) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>categorias">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark">
                                        <i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Categorias</span>
                                    </h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?> 
            <section class="bg-light  text-dark  py-2">
                <div class="container mx-auto col-12 px-2 py-2 row">
                    <div class="card bg-success text-center py-2 mb-4" style="width: 100rem;">
                        <div class="card-body  text-white">
                            <h5 class="card-title">CATEGORIAS</h5>
                            <p class="card-text">Cadastre os suas categorias no sistema</p>
                            <a href="<?= DIRPAGE ?>categorias/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>
                    <?php if ($qtd != 0) { ?>
                        <table id="ordena" class="table table-striped table-bordered sortable">
                            <thead class="text-center text-uppercase">
                                <th class="text-dark"><a name="column_sort"></a>  <a href="#column_sort">#</a></th>
                                <th class="text-dark">Descrição</th>
                                <th class="text-dark">Tipo</th>
                                <th class="text-dark">Setor</th>
                                <th class="text-dark">CLassificação</th>
                                <th class="text-dark">Nível</th>
                                <th class="text-dark">Status</th>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?> 
                            </thead>
                            <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="<?= ($categorias[$i]['CAT_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= $categorias[$i]['CAT_DESCRICAO']; ?></td>
                                        <td class="text-center align-middle">
                                        <?php for ($m=0; $m < $qtdCA; $m++) { ?>
                                            <?= (isset($categorias[$i]['CAT_TIPO']) &&  $categorias[$i]['CAT_TIPO']  == $m)? $ca[$m]: '' ?>
                                        <?php } ?>
                                        </td>
                                        <td class="text-center align-middle">
                                        <?php 
                                            if($categorias[$i]['SET_COD'] != 0) {
                                                for ($c = 0; $c < $qtdS; $c++) { 
                                                    if ($setores[$c]['SET_COD'] == $categorias[$i]['SET_COD']) { ?>
                                                    <?= $setores[$c]['SET_DESCRICAO']; ?>   
                                                <?php } } ?> 
                                            <?php }else { ?>
                                                À DEFINIR
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center align-middle">
                                        <?php 
                                            if($categorias[$i]['CLA_COD'] != 0) {
                                                for ($c = 0; $c < $qtdCL; $c++) { 
                                                    if ($classificacoes[$c]['CLA_COD'] == $categorias[$i]['CLA_COD']) { ?>
                                                    <?= $classificacoes[$c]['CLA_DESCRICAO']; ?>   
                                                <?php } } ?> 
                                            <?php }else { ?>
                                                À DEFINIR
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center align-middle"><?= $categorias[$i]['CAT_NIVEL']; ?></td>
                                        <td class="text-center align-middle"><?= ($categorias[$i]['CAT_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                            <td class="text-center align-middle">
                                                <?php if($categorias[$i]['CAT_STATUS'] == 0){ ?>
                                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Ativar categoria" data-codigo="<?= $categorias[$i]['CAT_COD']; ?>" data-nome="<?= $categorias[$i]['CAT_DESCRICAO']; ?>"  data-status="<?= $categorias[$i]['CAT_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-circle-check"></i></button>
                                                <?php }else { ?>
                                                <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'categorias/alteracao/'.$categorias[$i]['EMP_COD'].'/'.$categorias[$i]['CAT_COD']; ?>" title="Deseja Alterar?"><i class="fa fa-edit"></i></a>
                                                <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" title="Desativar categoria" data-codigo="<?= $categorias[$i]['CAT_COD']; ?>" data-nome="<?= $categorias[$i]['CAT_DESCRICAO']; ?>" data-status="<?= $categorias[$i]['CAT_STATUS']; ?>"  title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                                <?php } ?> 
                                            </td>
                                        <?php } ?> 
                                    </tr>
                                <?php $b++; } ?>
                            </tbody>
                        </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA CATEGORIA CADASTRADA</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="NOME" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="CAT_STATUS" name="CAT_STATUS" value="" />
                    <input type="hidden" id="CODIGO" name="CAT_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var descricao = button.data('descricao');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#CODIGO').val(codigo);
                modal.find('#CAT_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#NOME').html(descricao);
                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o Categoria?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o Categoria?');
                }
            });
        });
        $("#sts").click(function(){
            var CAT_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var CAT_STATUS = $('#CAT_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>categorias/status', {CAT_COD: CAT_COD,STATUS_CATEGORIA: true,EMP_COD: EMP_COD,CAT_STATUS: CAT_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>categorias"}, 100);
            });

        });

        const table = document.querySelector('table'); //get the table to be sorted

        table.querySelectorAll('th') // get all the table header elements
        .forEach((element, columnNo)=>{ // add a click handler for each 
            element.addEventListener('click', event => {
                sortTable(table, columnNo); //call a function which sorts the table by a given column number
            })
        })
        function sortTable(table, sortColumn){
        // get the data from the table cells
        const tableBody = table.querySelector('tbody')
        const tableData = table2data(tableBody);
        // sort the extracted data
        tableData.sort((a, b)=>{
            if(a[sortColumn] > b[sortColumn]){
            return 1;
            }
            return -1;
        })
        // put the sorted data back into the table
        data2table(tableBody, tableData);
        }
        // this function gets data from the rows and cells 
        // within an html tbody element
        function table2data(tableBody){
        const tableData = []; // create the array that'll hold the data rows
        tableBody.querySelectorAll('tr')
            .forEach(row=>{  // for each table row...
            const rowData = [];  // make an array for that row
            row.querySelectorAll('td')  // for each cell in that row
                .forEach(cell=>{
                rowData.push(cell.innerText);  // add it to the row data
                })
            tableData.push(rowData);  // add the full row to the table data 
            });
        return tableData;
        }

        // this function puts data into an html tbody element
        function data2table(tableBody, tableData){
        tableBody.querySelectorAll('tr') // for each table row...
            .forEach((row, i)=>{  
            const rowData = tableData[i]; // get the array for the row data
            row.querySelectorAll('td')  // for each table cell ...
                .forEach((cell, j)=>{
                cell.innerText = rowData[j]; // put the appropriate array element into the cell
                })
            });
        }
    </script>
</body>
</html>