<?php 
use Libraries\Sessao;
session_start();
include_once 'inc/cabecalho.phtml';

?>

<body class="bg-dark" bs-data="">
    <main class=" mx-auto">
        <?php //include_once 'inc/nav.phtml'; ?>
        <!-- Header-->
        <header class="bg-dark py-2">
            <section class="container">
                <div class="row">
                <div class="col-12 mt-5 text-center text-lg-start text-white-50">
                    <h1 class="display-5 text-center fw-bolder text-uppercase text-3 mb-2">LC-<span class="text-success">TEC</span></h1>
                    <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p>
                </div>
                    <div class="col-lg-12 col-xl-12 col-xxl-12">
                        <div class="my-5 text-center">
                        <h3>ERRO 404</h3>
                        </div>
                    </div>
                </div>
            </section>
        </header>
        <div class="container  mx-auto col-xl-12 col-xxl-12 px-2 py-1">
            <div class="text-center">
                PÁGINA NÃO ENCONTRADA
            </div>
        </div>
    </main>
    <?php include_once 'inc/rodape.phtml'; ?>
</body>

</html>