<?php 
use Libraries\Sessao;

include_once 'inc/cabecalho.phtml';

?>

<body class="bg-dark" bs-data="">
    <main class=" mx-auto">
        <?php //include_once 'inc/nav.phtml'; ?>
        <!-- Header-->
        <header class="bg-dark py-2">
            <section class="container">
                <div class="row">
                <div class="col-12 mt-5 text-center text-lg-start text-white-50">
                    <h1 class="display-4 text-center fw-bolder text-uppercase text-3 mb-2">LC/<span class="text-success">TEC</span></h1>
                    <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES PARA O SEU NEGÓCIO</p>
                </div>
                    <div class="col-lg-12 col-xl-12 col-xxl-12">
                        <div class="my-5 text-center">
                        <h3>POR MOTIVOS DE SEGURANÇA, SEU ACESSO FOI FINALIZADO!</h3>
                        </div>
                    </div>
                </div>
            </section>
        </header>
        <div class="container  mx-auto col-12 py-1">
            <div class="text-center">
            <p><a href="<?= DIRPAGE ?>site" class="btn btn-outline-success text-white text-uppercase text-center text-decoration-none">Acessar Novamente</a></p>
            </div>
        </div>
    </main>
    <?php include_once 'inc/rodape.phtml'; ?>
    <?php //include_once 'app/Views/admin/inc/limite_acesso.phtml';?>
    <script type="text/javascript">
            function createBubble() {
                const section = document.querySelector("Section");
                const createElement = document.createElement("span");
                var size = Math.random() * 60;
  
                createElement.style.animation = "animation 6s linear infinite";
                createElement.style.width = 180 + size + "px";
                createElement.style.height = 180 + size + "px";
                createElement.style.left = Math.random() * innerWidth + "px";
                section.appendChild(createElement);
  
                setTimeout(() => {
                    createElement.remove();
                }, 4000);
            }
            setInterval(createBubble, 400);
    </script>
</body>

</html>