<?php 
use Libraries\Sessao;

include_once 'inc/cabecalho.phtml';

?>

<body class="bg-dark" bs-data="">
    <main class="flex-shrink-0">
        <?php //include_once 'inc/nav.phtml'; ?>
        <!-- Header-->
        <header class="bg-dark py-2">
            <section class="container px-4">
                <div class="row gx-5 align-items-center justify-content-center">
                    <div class="col-lg-10 col-xl-10 col-xxl-10">
                        <div class="my-2 text-center text-xl-start">
                            <a class="text-decoration-none" href="<?= DIRPAGE; ?>site/gerencial"><h1 class="display-5 text-center fw-bolder text-uppercase text-white mb-2">Acesso <span class="text-success">Gerencial</span></h1></a>
                        </div>
                    </div>
                </div>
            </section>
        </header>
        <div class="d-lg-flex half">
            <div class="bg order-1 order-md-2" style="background-image: url(<?= DIRIMG ?>'login.jpg');"></div>
                <div class="contents order-2 order-md-1">

                    <div class="container">
                        <div class="row align-items-center justify-content-center">
                        <div class="col-md-7">
                            <h3>Login to <strong>Colorlib</strong></h3>
                            <p class="mb-4">Lorem ipsum dolor sit amet elit. Sapiente sit aut eos consectetur adipisicing.</p>
                            <form action="#" method="post">
                            <div class="form-group first">
                                <label for="username">Username</label>
                                <input type="text" class="form-control" placeholder="your-email@gmail.com" id="username">
                            </div>
                            <div class="form-group last mb-3">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" placeholder="Your Password" id="password">
                            </div>
                            
                            <div class="d-flex mb-5 align-items-center">
                                <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                                <input type="checkbox" checked="checked"/>
                                <div class="control__indicator"></div>
                                </label>
                                <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span> 
                            </div>

                            <input type="submit" value="Log In" class="btn btn-block btn-primary">

                            </form>
                        </div>
                </div>
            </div>
        </div>
        <div class="container col-xl-10 col-xxl-8 px-2 py-1">
            <div class="row align-items-center mt-5 g-lg-9">
                <?php include_once 'inc/logo.phtml'; ?>
                <div class="col-12 col-md-6 mx-auto">
                <?= Sessao::alert('ERRO'); ?>
                    <form class="p-2 p-md-4" action="<?= DIRPAGE ?>login/auth_admin" method="POST">
                        <div class="form-floating mb-1">
                            <input type="email" class="form-control" id="email" name="email_usuario" placeholder="Informe seu email" value="<?= isset($_POST['email_usuario']) ? $_POST['email_usuario'] : '' ?>">
                            <label for="email">Seu Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="senha_usuario" id="floatingPassword" placeholder="Digite sua senha">
                            <label for="floatingPassword">Sua Senha</label>
                        </div>
                        <button class="w-100 btn btn-lg text-uppercase btn-outline-success" name="acesso" value="<?= isset($_SESSION['acesso']) ? $_SESSION['acesso'] : '' ?>" type="submit"><i class="fa fa-sign-in"></i> Entrar</button>
                        <hr class="my-3 text-white">
                        <div class="form-floating m-2 mb-0 text-uppercase text-center">
                            <p><a href="<?= DIRPAGE ?>login/lembrar" class="btn btn-outline-success text-white text-center text-decoration-none">Esqueci minha senha</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <?php include_once 'inc/rodape.phtml'; ?>
</body>

</html>