<?php 
use Libraries\Sessao;
$_SESSION['acesso'] = date('i:s');
include_once 'inc/cabecalho.phtml';
?>
<body class="bg-dark" bs-data="">
    <main class="flex-shrink-0">
            <!-- Header-->
        <header class="bg-dark py-2">
            <section class="container px-5">
                <div class="row align-items-center justify-content-center">
                    <div class="col-lg-10 col-xl-10 col-xxl-12">
                        <div class="my-5 text-center text-xl-start">
                            <a class="text-decoration-none" href="<?= DIRPAGE; ?>login/index"><h2 class="fs-5 text-center fw-bolder text-uppercase text-white mb-1">Acesso <span class="text-success">Administrativo</span></h2></a>
                        </div>
                    </div>
                </div>
            </section>
        </header>
        <div class="container col-xl-10 col-xxl-10">
            <div class="row align-items-center g-lg-5">
                <div class="col-12 col-sm-12 col-md-4 col-lg-7 text-center text-lg-start text-white-50">
                    <?php include_once 'inc/logo.phtml'; ?>
                </div>
                <div class="col-12 col-sm-12 col-md-8 col-lg-5 mx-auto">
                <?= Sessao::alert('ERRO'); ?>
                    <form class="p-2 p-md-4" action="<?= DIRPAGE ?>login/auth" method="POST">
                        <div class="form-floating mb-1">
                            <input type="email" class="form-control" id="email" name="email_usuario" placeholder="Informe seu email" value="<?= isset($_POST['email_usuario']) ? $_POST['email_usuario'] : '' ?>">
                            <label for="email">Seu Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="senha_usuario" id="floatingPassword" placeholder="Digite sua senha">
                            <label for="floatingPassword">Sua Senha</label>
                        </div>
                        <button class="w-100 btn btn-lg text-uppercase btn-success" name="acesso" value="<?= isset($_SESSION['acesso']) ? $_SESSION['acesso']: '' ?>" type="submit"><i class="fa fa-sign-in"></i> Entrar</button>
                        <hr class="my-3 text-white">
                        <div class="form-floating m-2 mb-0 text-uppercase text-center">
                            <p><a href="<?= DIRPAGE ?>login/lembrar" class="btn btn-outline-success text-white text-center text-decoration-none">Esqueci minha senha</a></p>
                            <p><a href="<?= DIRPAGE ?>site/cadastro" class="btn btn-outline-dark text-white text-center text-decoration-none">Cadastre-se</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <?php include_once 'inc/rodape.phtml'; ?>
</body>

</html>