<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($contas) ? count($contas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-success">Finanças</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light  text-dark row  py-2">
                <div class="container mx-auto col-12 mx-auto row">
                    <?php if ($qtd == 0) { ?>
                        <div class="card bg-success text-center py-4 mb-4" style="width: 30rem;">
                            <div class="card-body text-white">
                                <h5 class="card-title">FINANCEIRO</h5>
                                <p class="card-text">Crie/Altere os dados da sua conta principal</p>
                                <a href="<?= DIRPAGE ?>financeiro/cadastro_conta" class="btn btn-dark">ACESSAR</a>
                            </div>
                        </div>
                    <?php }else { ?>
                        <div class="card bg-success text-white  mx-auto text-center py-4 mb-4" style="width: 20rem;">
                            <h5 class="card-title">FINANCEIRO</h5>
                            <p class="card-text">Crie/Altere os dados da sua conta principal</p>
                            <a href="<?= DIRPAGE ?>financeiro/contas" class="btn btn-success">ACESSAR</a>
                        </div>
                        <div class="card bg-secondary text-white mx-auto  text-center py-4 mb-4" style="width: 20rem;">
                            <h5 class="card-title">PDV</h5>
                            <p class="card-text">Ponto de Venda</p>
                            <a href="<?= DIRPAGE ?>financeiro/pdv" class="btn btn-secondary">ACESSAR</a>
                        </div>
                        <div class="card bg-info text-white mx-auto text-center py-4 mb-4" style="width: 20rem;">
                            <h5 class="card-title">FLUXO DE CAIXA</h5>
                            <p class="card-text">Acompanhe seu fluxo de caixa</p>
                            <a href="<?= DIRPAGE ?>financeiro/fluxo_caixa" class="btn btn-info">ACESSAR</a>
                        </div>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>