<?php 
use Libraries\Sessao;
use App\Models\ModulosEmpresa;



include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtdME = (is_array($modulos_empresa) ? count($modulos_empresa) : 0);
$qtd = (is_array($modulos) ? count($modulos) : 0);

$ModulosEmpresa = new ModulosEmpresa;
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>modulo_empresa">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Módulos da Empresa</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="container bg-light mx-auto py-2 mb-5">
                <div class="col-12 row">
                    <h5 class="fw-bolder text-center text-uppercase text-dark"><i class="bi bi-ban-square"></i> Módulos Ativos</h5>
                    <?php if ($qtdME != 0) { 
                        for ($i=0; $i < $qtdME; $i++) { ?>
                        <div class="col-12 col-sm-4 col-md-6 rounded-2 text-center mb-2">
                            <div class="card  mx-auto <?= $modulos_empresa[$i]['MOD_COR']; ?> py-1">
                                <div class="card-header">
                                    <?= $modulos_empresa[$i]['MOD_ICON']; ?> <?= $modulos_empresa[$i]['MOD_NOME']; ?> 
                                    </div>
                                <div class="card-body">
                                    <h5 class="card-title text-uppercase">Módulo <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                    <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                </div>  
                            
                                <div class="card-footer text-center">
                                    <?php if($modulos_empresa[$i]['MOD_NOME'] != 'CADASTROS'){ ?>
                                    <a type="button" href="<?= DIRPAGE ?>modulo_empresa/alterar/<?= $modulos_empresa[$i]['EMP_COD']?>/<?= $modulos_empresa[$i]['MOD_COD']?>/<?= $modulos_empresa[$i]['MLE_STATUS'] ?>" class="btn btn-<?= $modulos_empresa[$i]['MOD_COR']; ?> link-light text-decoration-none">
                                        <?php if ($modulos_empresa[$i]['MLE_STATUS'] == 1 ) { ?>
                                        <i class="bi bi-ban"></i> DESATIVAR
                                        <?php }else{ ?>
                                        <i class="bi bi-check2"></i> ATIVAR
                                        <?php } ?>
                                    </a>
                                    <?php }else{ ?>
                                        <i class="bi bi-check2"></i> ATIVADO
                                    <?php } ?>
                                </div>
                            
                            </div>
                        </div>
                        <?php } ?>
                    <?php } ?>
                    <?php if($_SESSION['USU_NIVEL'] >= 10){ ?>
                        <?php if ($qtdME != $qtd) { ?>
                        <hr>
                        <h5 class="fw-bolder text-center text-uppercase text-dark"><i class="bi bi-ban-square"></i>Ative Outros Módulos</h5> 
                        <?php }else { ?>
                            <h5 class="fw-bolder mt-4 text-center text-uppercase text-warning"><i class="bi bi-ban-square"></i> Todos os Módulos Estão Ativados</h5> 
                        <?php } ?>
                        <?php
                        for ($i=0; $i < $qtd; $i++) {  
                            $ck = $ModulosEmpresa->setCodEmpresa($_SESSION['EMP_COD'])->setCodModulo($modulos[$i]['MOD_COD'])->checarRegistroModuloEmpresa(0);
                        
                            if (!$ck) { ?>
                            <?php if ($modulos[$i]['MOD_STATUS'] == 1 ) { ?>
                                <div class="col-12 col-sm-4 col-md-6 rounded-2 text-center mb-2">
                                    <div class="card mx-auto <?= $modulos[$i]['MOD_COR']; ?> py-1">
                                        <div class="card-header">
                                            <?= $modulos[$i]['MOD_ICON']; ?> <?= $modulos[$i]['MOD_NOME']; ?> 
                                            </div>
                                        <div class="card-body">
                                            <h5 class="card-title text-uppercase">Módulo <?= $modulos[$i]['MOD_NOME']; ?></h5>
                                            <p class="card-text"><?= $modulos[$i]['MOD_DESCRICAO']; ?></p>
                                        </div>  
                                        <a type="button" href="<?= DIRPAGE ?>modulo_empresa/alterar/<?= $_SESSION['EMP_COD']?>/<?= $modulos[$i]['MOD_COD']?>/<?= $modulos[$i]['MOD_STATUS'] ?>" class="btn btn-<?= $modulos[$i]['MOD_COR']; ?> link-light text-decoration-none">
                                            <i class="bi bi-check2"></i> ATIVAR
                                        </a>
                                    </div>
                                </div>  
                                <?php } ?>
                            <?php  }
                        }  ?>    
                    <?php }else { ?>
                        <h5 class="fw-bolder mt-4 text-center text-uppercase text-warning"><i class="bi bi-ban-square"></i> Todos os Módulos Estão Ativados</h5> 
                    <?php } ?>
                </div>
            </section>
        </div>
        <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
    </div>
</body>
</html>
<!-- <a type="button" href="<?php //= DIRPAGE ?>modulo_empresa/alterar/<?php //= $_SESSION['EMP_COD']?>/<?php //= $modulos[$i]['MOD_COD'] ?>" class="btn btn-<?php //= $modulos[$i]['MOD_COR']; ?> link-light text-decoration-none"></a> !>