<?php

use App\Models\AberturaFechamentoCaixa;
use Libraries\Sessao;

$Abfc = new AberturaFechamentoCaixa;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtd = (is_array($caixa) ? count($caixa) : 0);

//$af = $Abfc->setCodEmpresa($_SESSION['EMP_COD'])-
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>caixas">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark">
                                        <?= $modulo[0]['MOD_ICON'] ?> Gerenciar <span class="text-success">Caixas</span>
                                    </h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?> 
            <section class="bg-light  text-dark  py-2">
                <div class="card text-white mx-auto bg-10 m-1 py-3" style="max-width: 35rem;">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-10 fs-5 align-middle">
                                    <i class="bi bi-box"></i> SALDO <?= ($caixa['CXA_SALDO'] != '0')? "R$ ".number_format($caixa['CXA_SALDO'],2,',','.')  : 'R$ 0,00'; ?>
                                </div>  
                                <div class="col-1 mr-1">
                                    <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'caixas/alteracao/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Alterar Caixa"><i class="fa fa-edit"></i></a>
                                </div>
                            </div>  
                        </div>
                        <div class="card-body">
                            <a href="<?= DIRPAGE.'caixa/detalhar/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Acessar Caixa" class="col-auto link-light text-decoration-none">
                                <div class="row">
                                    <div class="col-12">
                                        <h5 class="card-title">Descrição: <?= $caixa['CXA_DESCRICAO']; ?></h5>
                                        <p class="card-text">Empresa/Negócio: <?= $caixa['EMP_NOME_FANTASIA']; ?></p>
                                    </div>
                                    <div class="col-12 mx-auto text-center">
                                        <h2 class="card-title">
                                            
                                        </h2>
                                        <p class="card-text ">ACESSAR</p>
                                    </div>
                                </div>
                            </a>  
                           
                        </div>
                        <div class="card-footer">
                            <div class="col-12 mx-auto text-center">
                                <button type="button" data-bs-toggle='modal' data-bs-target="#af_caixa" data-empresa="<?= $caixa['EMP_COD']?>" data-caixa="<?= $caixa['CXA_COD'] ?>" title="Abrir Caixa" class="col-12 mx-auto btn btn-success text-decoration-none">ABRIR CAIXA</button>
                            </div>  
                        </div>
                    </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
        <div class="modal fade" id="af_caixa"  tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"  aria-labelledby="af_caixa" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">ABERTURA/FECHAMENTO</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5 class="modal-title">CONFIRMAR ABERTURA/FECHAMENTO</h5>
                <form>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">USUÁRIO:</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">SENHA:</label>
                        <input type="password" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="AFC_STATUS" name="AFC_STATUS" value="" />
                <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                <input type="hidden" id="USU_COD" name="USU_COD" value="<?= $_SESSION['USU_COD'] ?>" />
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                <button type="button" id="sts" class="btn btn-primary">ABRIR/FECHAR - CAIXA</button>
            </div>
            </div>
        </div>
    </div>
    </div>
    
    <script type="text/javascript">
        const exampleModal = document.getElementById('af_caixa')
        if (exampleModal) {
        exampleModal.addEventListener('show.bs.modal', event => {
            // Button that triggered the modal
            const button = event.relatedTarget
            // Extract info from data-bs-* attributes
            const caixa = button.getAttribute('data-caixa')

            console.log(caixa);
        });
        }
        $("#sts").click(function(){
            var CXA_COD = $('#CXA_COD').val();
            var EMP_COD = $('#EMP_COD').val();
            var USU_COD = $('#USU_COD').val();
            var USU_STATUS = $('#USU_STATUS').val();
            var AFC_STATUS = $('#sts').val();
            var MOV_STATUS = $('#MOV_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>movimentacoes/reverter_movimentacao', {
                PRO_COD: PRO_COD,
                EXCLUIR_MOVIMENTACAO_PRODUTO: true,
                EMP_COD:EMP_COD,
                EST_COD:EST_COD,
                MOV_COD:MOV_COD, 
                USU_COD:USU_COD,
                MOV_STATUS: MOV_STATUS
            }, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta2').addClass('alert alert-success');
                }else{
                    $('#resposta2').addClass('alert alert-warning');
                }
                $('#resposta2').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>movimentacoes/"}, 1000);
            });

        });
    </script>
</body>
</html>    