<?php

use App\Models\AberturaFechamentoCaixas;
use Libraries\Sessao;

$Abfc = new AberturaFechamentoCaixas;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 

$qtdAF = (is_array($ab_caixas)? count($ab_caixas): 0);
$qtd = (is_array($caixa) ? count($caixa) : 0);

if ($qtdAF !=0) {
    # code...
} else {
    # code...
}

//$af = $Abfc->setCodEmpresa($_SESSION['EMP_COD'])-
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>caixas">
                                    <h3 class="fs-2 fw-bolder text-uppercase text-dark">
                                        <?= $modulo[0]['MOD_ICON'] ?> Gerenciar <span class="text-success">Caixas</span>
                                    </h3>
                                </a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?> 
            <section class="bg-light  text-dark  py-2">
                <div class="card text-white mx-auto bg-10 m-1 py-3" style="max-width: 35rem;">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-10 fs-5 align-middle">
                                    <i class="bi bi-box"></i> SALDO <?= ($caixa['CXA_SALDO'] != '0')? "R$ ".number_format($caixa['CXA_SALDO'],2,',','.')  : 'R$ 0,00'; ?>
                                </div>  
                                <div class="col-1 mr-1">
                                    <a type="button" class="btn btn-outline-warning btn-sm d-print-none" href="<?= DIRPAGE.'caixas/alteracao/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Alterar Caixa"><i class="fa fa-edit"></i></a>
                                </div>
                            </div>  
                        </div>
                        <div class="card-body">
                            <a href="<?= DIRPAGE.'caixas/detalhar/'.$caixa['EMP_COD'].'/'.$caixa['CXA_COD']; ?>" title="Acessar Caixa" class="col-auto link-light text-decoration-none">
                                <div class="row">
                                    <div class="col-12">
                                        <h5 class="card-title">Descrição: <?= $caixa['CXA_DESCRICAO']; ?></h5>
                                        <p class="card-text">Empresa/Negócio: <?= $caixa['EMP_NOME_FANTASIA']; ?></p>
                                    </div>
                                    <div class="col-12 mx-auto text-center">
                                        <h2 class="card-title">
                                            
                                        </h2>
                                        <p class="card-text ">ACESSAR</p>
                                    </div>
                                </div>
                            </a>  
                           
                        </div>
                        <div class="card-footer">
                            <div class="col-12 mx-auto text-center">
                                <button type="button" data-bs-toggle='modal' data-bs-target="#af_caixa" data-empresa="<?= $caixa['EMP_COD']?>" data-caixa="<?= $caixa['CXA_COD'] ?>" data-status="" title="Abrir Caixa" class="col-12 mx-auto btn btn-dark text-decoration-none">ABRIR/FECHAR - CAIXA</button>
                            </div>  
                        </div>
                    </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <div class="modal fade" id="af_caixa"  tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"  aria-labelledby="af_caixa" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">ABERTURA/FECHAMENTO</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="<?= DIRPAGE ?>caixas/status_abertura_fechamento" method="post">
                            <div class="modal-body">
                                <h5 class="modal-title">CONFIRMAR ABERTURA/FECHAMENTO</h5>
                                <div class="col-12 row mx-auto mb-3">
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="2">SALDO (ATUAL)</label>  
                                        <div class="input-group">    
                                            <span class="input-group-text">R$</span>  
                                            <input type="text" class="form-control form-control-lg real" id="CXA_SALDO" name="CXA_SALDO" value="">
                                        </div>
                                    </div>
                                    <div class="col-6 form-floating mb-2">
                                        <input type="date" name="AF_DATA" class="form-control form-control-lg" value="<?= date('Y-m-d') ?>">
                                        <label class="form-label">DATA</label>
                                    </div>
                                    <div class="col-12 mb-3">
                                        <label class="form-label" for="1">OBSERVAÇÃO</label>
                                        <div class="form-floating mb-3">
                                            <textarea class="form-control maiusculo" id="AF_OBSERVACAO" name="AF_OBSERVACAO"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 mx-auto mb-3">
                                    <div class="mb-3">
                                        <label for="recipient-name" class="col-form-label">USUÁRIO:</label>
                                        <input type="text" name="USU_COD_CAIXA" class="form-control">
                                    </div>
                                    <div class="mb-3">
                                        <label for="message-text" class="col-form-label">SENHA:</label>
                                        <input type="password" name="USU_SENHA_CAIXA" class="form-control"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="hidden" id="AFC_STATUS" name="AFC_STATUS" value="" />
                                <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                                <input type="hidden" id="USU_COD" name="USU_COD" value="<?= $_SESSION['USU_COD'] ?>" />
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                                <button type="button" id="sts" class="btn btn-primary">ABRIR/FECHAR - CAIXA</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    
    <script type="text/javascript">
        const exampleModal = document.getElementById('af_caixa')
        if (exampleModal) {
            exampleModal.addEventListener('show.bs.modal', event => {
                // Button that triggered the modal
                const button = event.relatedTarget
                // Extract info from data-bs-* attributes
                const caixa = button.getAttribute('data-caixa')

                console.log(caixa);
            });
        }
        $("#sts").click(function(){
            var EMP_COD = $('#EMP_COD').val();
            var USU_COD = $('#USU_COD').val();
            var CXA_COD = $('#CXA_COD').val();
            var AFC_DATA = $('#AFC_DATA').val();
            var AFC_SALDO = $('#AFC_SALDO').val();
            var USU_COD_CAIXA = $('#USU_COD_CAIXA').val();
            var USU_SENHA_CAIXA = $('#USU_SENHA_CAIXA').val();
            var AFC_STATUS = $('#AFC_STATUS').val();
            setTimeout(function () {
                    $('#af_caixa').modal('hide');
            }, 200);
            $.post('<?= DIRPAGE; ?>caixas/status_abertura_fechamento', {
                ABERTURA_FECHAMENTO: true,
                EMP_COD:EMP_COD,
                USU_COD: USU_COD,
                CXA_COD: CXA_COD,
                AFC_DATA: AFC_DATA,
                AFC_SALDO: AFC_SALDO,
                USU_COD_CAIXA:USU_COD_CAIXA,
                USU_SENHA_CAIXA:USU_SENHA_CAIXA, 
                AFC_STATUS: AFC_STATUS
            }, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                //setTimeout( () => { window.location.href="<? //= DIRPAGE ?>caixas"}, 3000);
            });

        });
        $('.real').maskMoney({
            prefix:'',
            allowNegative: true,
            thousands:'', decimal:'.',
            affixesStay: true
        });
    </script>
</body>
</html>    