<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($lancamentos) ? count($lancamentos) : 0);
$qtdLP = (is_array($lancamentos_pagar) ? count($lancamentos_pagar) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>pagamentos/pagar">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-dark">Pagamentos >> A PAGAR</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            
            <section class="bg-light text-dark row py-2">
                <section class="container col-12 mx-auto p-1 text-center fs-4 d-print-none">
                    <div class="container mx-auto col-8 row">
                        <div class="container input-group mb-3 mx-auto col-6">
                            <input type="text" id="pesquisar" class="form-control form-control-lg col-6" placeholder="Descrição do lançamento">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2">BUSCAR</button>
                        </div>
                    </div>
                    <?= $qtdLP ?> RESULTADOS
                </section>
                <div class="container mx-auto col-12 row">
                
                <?php
                    if($qtdLP != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark" title="Participa dos resultados da empresa">R</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Parcela</th>
                            <th class="text-dark">Data Venc.</th>
                            <th class="text-dark">Valor</th>
                            <th class="text-dark ">Pagar</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark d-print-none">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                         $b = 1;
                         for ($i= 0; $i < $qtdLP; $i++) { 
                             $data = new DateTime($lancamentos_pagar[$i]['LAN_DT_VENCIMENTO']);
                        ?>
                         <tr class="<?= ($lancamentos_pagar[$i]['LAN_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                            <td class="text-center align-middle"><?= $b; ?></td>
                            <td class="text-center align-middle <?= ($lancamentos_pagar[$i]['LAN_RESULTADOS'] == 1)? 'bg-success text-white': ''; ?>"><?= ($lancamentos_pagar[$i]['LAN_RESULTADOS'] == 1)? '$': ''; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos_pagar[$i]['LAN_DESCRICAO']; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos_pagar[$i]['LAN_PARCELA']; ?></td>
                            <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                            <td class="text-center align-middle"><?= number_format($lancamentos_pagar[$i]['LAN_VALOR'],2,',','.'); ?></td>
                            <td class="text-center align-middle">
                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $lancamentos_pagar[$i]['LAN_COD']; ?>" data-nome="<?= $lancamentos_pagar[$i]['LAN_DESCRICAO']; ?>" data-status="<?= $lancamentos_pagar[$i]['LAN_STATUS']; ?>" title="Deseja Pagar?" ><i class="fa fa-check"></i></button>
                            </td>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                            <td class="text-center align-middle d-print-none">
                                <?php if($lancamentos_pagar[$i]['LAN_STATUS'] == 0){ ?>
                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal' data-bs-target="#status" data-codigo="<?= $lancamentos_pagar[$i]['LAN_COD']; ?>" data-nome="<?= $lancamentos_pagar[$i]['CLI_NOME']; ?>" data-status="<?= $lancamentos_pagar[$i]['LAN_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                <?php }else { ?>
                                <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'lancamentos/alteracao/'.$lancamentos_pagar[$i]['EMP_COD'].'/'.$lancamentos_pagar[$i]['LAN_COD']; ?>" title="Alterar lancamento"><i class="fa fa-edit"></i></a>
                                <?php } ?>
                            </td>
                            <?php } ?>
                        </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM LANÇAMENTO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    </body>
</html>