<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($lancamentos) ? count($lancamentos) : 0);
$qtdLP = (is_array($lancamentos_pagar) ? count($lancamentos_pagar) : 0);
$qtdF = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>pagamentos/pagar">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-dark">Pagamentos >> A PAGAR</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            
            <section class="bg-light text-dark row py-2">
                <section class="container col-12 mx-auto p-1 text-center fs-4 d-print-none">
                    <div class="container mx-auto col-8 row">
                        <div class="container input-group mb-3 mx-auto col-6">
                            <input type="text" id="pesquisar" class="form-control form-control-lg col-6" placeholder="Descrição do lançamento">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2">BUSCAR</button>
                        </div>
                    </div>
                    <?= $qtdLP ?> RESULTADOS
                </section>
                <div class="container mx-auto col-12 row">
                
                <?php
                    if($qtdLP != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark" title="Participa dos resultados da empresa">R</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Parcela</th>
                            <th class="text-dark">Data Venc.</th>
                            <th class="text-dark">Valor</th>
                            <th class="text-dark ">Pagar</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark d-print-none">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                         $b = 1;
                         for ($i= 0; $i < $qtdLP; $i++) { 
                             $data = new DateTime($lancamentos_pagar[$i]['LAN_DT_VENCIMENTO']);
                        ?>
                         <tr class="<?= ($lancamentos_pagar[$i]['LAN_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                            <td class="text-center align-middle"><?= $b; ?></td>
                            <td class="text-center align-middle <?= ($lancamentos_pagar[$i]['LAN_RESULTADOS'] == 1)? 'bg-success text-white': ''; ?>"><?= ($lancamentos_pagar[$i]['LAN_RESULTADOS'] == 1)? '$': ''; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos_pagar[$i]['LAN_DESCRICAO']; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos_pagar[$i]['LAN_PARCELA']; ?></td>
                            <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                            <td class="text-center align-middle"><?= number_format($lancamentos_pagar[$i]['LAN_VALOR'],2,',','.'); ?></td>
                            <td class="text-center align-middle">
                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#pagar" data-codigo="<?= $lancamentos_pagar[$i]['LAN_COD']; ?>" data-valor="<?= $lancamentos_pagar[$i]['LAN_VALOR']; ?>" data-parcela="<?= $lancamentos_pagar[$i]['LAN_PARCELA']; ?>" data-nome="<?= $lancamentos_pagar[$i]['LAN_DESCRICAO']; ?>" data-vencimento="<?= $lancamentos_pagar[$i]['LAN_DT_VENCIMENTO']; ?>" data-status="<?= $lancamentos_pagar[$i]['LAN_STATUS']; ?>" title="Deseja Pagar?" ><i class="fa fa-check"></i></button>
                            </td>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                            <td class="text-center align-middle d-print-none">
                                <?php if($lancamentos_pagar[$i]['LAN_STATUS'] == 0){ ?>
                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal' data-bs-target="#status" data-codigo="<?= $lancamentos_pagar[$i]['LAN_COD']; ?>" data-nome="<?= $lancamentos_pagar[$i]['CLI_NOME']; ?>" data-status="<?= $lancamentos_pagar[$i]['LAN_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                <?php }else { ?>
                                <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'lancamentos/alteracao/'.$lancamentos_pagar[$i]['EMP_COD'].'/'.$lancamentos_pagar[$i]['LAN_COD']; ?>" title="Alterar lancamento"><i class="fa fa-edit"></i></a>
                                <?php } ?>
                            </td>
                            <?php } ?>
                        </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM LANÇAMENTO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <div class="modal fade" id="pagar"  tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"  aria-labelledby="pagar" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">PAGAR LANÇAMENTO</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="<?= DIRPAGE ?>pagamentos/pagar_lançamento" method="post">
                            <div class="modal-body">
                                <h5 class="modal-title text-center mb-3">CONFIRMAR PAGAMENTO</h5>
                                <div class="col-12 row mx-auto mb-3">
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="2">VALOR A PAGAR</label>  
                                        <div class="input-group">    
                                            <span class="input-group-text">R$</span>  
                                            <input type="text" class="form-control form-control-lg real" id="LAN_VALOR" name="PAG_VALOR" value="">
                                        </div>
                                    </div>
                                    <div class="col-6 mb-2">
                                        <label class="form-label">PARCELA?</label>
                                        <div class="">
                                            <input type="text" class="form-control form-control-lg" disabled id="LAN_PARCELA" name="LAN_PARCELA" value="">
                                        </div>
                                    </div>
                                    <div class="col-6 mb-2">
                                        <label class="form-label">DATA DO PAGAMENTO</label>
                                        <div class="">
                                            <input type="date" class="form-control form-control-lg" name="PAG_DT_PAGAMENTO" value="<?= date('Y-m-d') ?>">
                                        </div>
                                    </div>
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="2">DATA DE VENCIMENTO</label>  
                                        <input type="text" class="form-control form-control-lg" disabled id="LAN_DT_VENCIMENTO" name="LAN_DT_VENCIMENTO" value="">
                                    </div>
                                    <div id="FPG" class="col-12 mx-auto mb-3">
                                        <label class="form-label">FORMA DE PAGAMENTO</label>
                                        <select  class="form-select" name="FPG_COD"> 
                                        <?php for ($i=0; $i < $qtdF; $i++) { if ($formas_pagamentos[$i]['FPG_STATUS'] == 1) { ?>
                                            <option value="<?= $i ?>" <?= (isset($_POST['FPG_COD']) &&  $_POST['FPG_COD']  == $i)? 'selected' : '' ?>><?= ($formas_pagamentos[$i]['FPG_TIPO'] == 1)? 'À VISTA' : 'À PRAZO'; ?> - <?= $formas_pagamentos[$i]['FPG_DESCRICAO'] ?></option>
                                        <?php } } ?>
                                        </select>
                                        
                                    </div>
                                    <div class="col-12 mb-3">
                                        <label class="form-label" for="2">DESCRIÇÃO</label>  
                                        <input type="text" class="form-control form-control-lg" disabled id="LAN_DESCRICAO" name="LAN_DESCRICAO" value="">
                                    </div>
                                    <div class="col-12 mb-3">
                                        <label class="form-label" for="1">OBSERVAÇÃO</label>
                                        <div class="form-floating mb-3">
                                            <textarea class="form-control maiusculo" id="LAN_OBSERVACAO" name="PAG_OBSERVACAO"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 mx-auto mb-3">
                                    
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="hidden" id="LAN_STATUS" name="LAN_STATUS" value="" />
                                
                                <input type="hidden" id="LAN_COD" name="LAN_COD" value="" />
                                <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                                <input type="hidden" id="USU_COD" name="USU_COD" value="<?= $_SESSION['USU_COD'] ?>" />
                                <button type="button" class="btn btn-dark" data-bs-dismiss="modal">CANCELAR</button>
                                <button type="submit" id="sts" name="CADASTRAR_PAGAMENTO" class="btn <?= $modulo[0]['MOD_COR'] ?> text-white"><i class="bi bi-box-arrow-right"></i> PAGAR</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
        $(document).ready(function() {
            $('#pagar').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var vencimento = button.data('vencimento');
                var valor = button.data('valor');
                var parcela = button.data('parcela');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#LAN_COD').val(codigo);
                const novaData = new Date(vencimento);
                modal.find('#LAN_DT_VENCIMENTO').val(novaData.toLocaleDateString('pt-BR'));
                modal.find('#LAN_VALOR').val(valor);
                modal.find('#LAN_PARCELA').val(parcela);
                modal.find('#LAN_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#LAN_DESCRICAO').val(nome);
            });
        });
        $("#sts2").click(function(){
            var LAN_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var USU_COD = $('#USU_COD').val();
            var LAN_VALOR = $('#LAN_VALOR').val();
            var LAN_DT_PAGAMENTO = $('#LAN_DT_PAGAMENTO').val();
            var LAN_OBSERVACAO = $('#LAN_OBSERVACAO').val();
            var LAN_STATUS = $('#LAN_STATUS').val();
            setTimeout(function () {
                    $('#pagar').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>pagamentos/pagar_lançamento', {LAN_COD: LAN_COD,EMP_COD: EMP_COD,USU_COD: USU_COD,LAN_VALOR: LAN_VALOR,LAN_DT_PAGAMENTO: LAN_DT_PAGAMENTO,LAN_OBSERVACAO: LAN_OBSERVACAO,CADASTRAR_PAGAMENTO: true, LAN_STATUS: LAN_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>lancamentos/pagar"}, 200);
            });

        });
        </script>
        </div>
    </div>
    </body>
</html>