<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($setores) ? count($setores) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-5 align-items-center justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>setores/cadastro">
                                        <h5 class="fs-2 fw-bolder text-uppercase text-dark">
                                            <i class="fa fa-handshake"></i> Cadastrar <span class="text-success"> Setores</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 " action="<?= DIRPAGE ?>setores/cadastrar" method="POST">
                            <div class="row ">    
                                <div class="col-2 mb-2 text-center">
                                    <label class="form-label">NÍVEL</label>
                                    <div class="form-floating mb-3">
                                        <select class="form-select " name="SET_NIVEL">                                        
                                            <?php for ($i=1; $i <= 20; $i++) { ?>
                                                <option value="<?= $i?>" <?= (isset($_POST['SET_NIVEL']) &&  $_POST['SET_NIVEL']  == $i)? 'selected' : ''; ?>><?= $i ?></option>
                                            <?php } ?>
                                        </select>
                                        <label class="form-floating ">NÍVEL DO SETOR</label>
                                    </div>
                                </div>
                                <div class="col-3 mb-2 text-center">
                                    <label class="form-label">TIPO</label>
                                    <div class="form-floating mb-3">
                                        <select class="form-select" name="SET_TIPO">                                        
                                            <option value="0" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 0)? 'selected' : ''; ?>>----</option>   
                                            <option value="1" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 1)? 'selected' : ''; ?>>CATEGORIAS</option> 
                                            <option value="2" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 2)? 'selected' : ''; ?>>CLIENTES</option> 
                                            <option value="3" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 3)? 'selected' : ''; ?>>ESTOQUES</option> 
                                            <option value="4" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 4)? 'selected' : ''; ?>>PRODUTOS</option> 
                                            <option value="5" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 5)? 'selected' : ''; ?>>SERVIÇOS</option> 
                                            <option value="6" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 6)? 'selected' : ''; ?>>COLABORADORES</option> 
                                            <option value="7" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 7)? 'selected' : ''; ?>>USUÁRIOS</option> 
                                            <option value="150" <?= (isset($_POST['SET_TIPO']) &&  $_POST['SET_TIPO']  == 150)? 'selected' : ''; ?>>OUTROS</option> 
                                        </select>
                                        <label class="form-floating ">TIPO DO SETOR</label>
                                    </div>
                                </div>
                                <div class="col-7 mb-3">
                                    <label class="form-label" for="1">DESCRIÇÃO</label>
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control maiusculo" id="1" name="SET_DESCRICAO" placeholder="" value="<?= isset($_POST['SET_DESCRICAO']) ? $_POST['SET_DESCRICAO'] :''; ?>">
                                        <label class="form-floating px-3" for="1">DESCRIÇÃO DO SETOR</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($_SESSION['EMP_COD']) ? $_SESSION['EMP_COD'] : 0; ?>">
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVO_SETOR" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                            </div> 
                        </form>
                    </div>
                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>