<?php 
use Libraries\Sessao;
use Libraries\Util;
$Util = new Util;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($transacoes) ? count($transacoes) : 0);
$qtdFP = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
!isset($m)? $m = $Util->getMesAtual():''; 
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>transacoes">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-dark">Transações</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  

            <section class="bg-light text-dark py-3">
                <div class="col-12 mx-auto mt-5">
                    <form class="col-12 d-print-none mt-3" id="filtrar" action="<?= DIRPAGE ?>transacoes" method="POST">
                        <div class="col-12 row mx-auto mt-5 align-items-center align-middle">
                            <div class="col-4 text-uppercase text-center mx-auto fs-4 "><?= Util::mesLowercase(date('n',$m))?>/<?= date('Y') ?> </div>
                            <div class="col-4 mx-auto">
                                <input type="radio" class="btn-check" name="TIPO" id="option1" value="0" <?= (!isset($_POST['TIPO']) or  $_POST['TIPO']  == 0)? 'checked' : '' ?>>
                                <label class="btn col" for="option1">TODOS</label></input>
                                <input type="radio" class="btn-check" name="TIPO" id="option2" value="1" <?= (isset($_POST['TIPO']) &&  $_POST['TIPO']  == 1)? 'checked' : '' ?>/>
                                <label class="btn col" for="option2">ENTRADA</label></input>
                                <input type="radio" class="btn-check" name="TIPO" id="option3" value="2" <?= (isset($_POST['TIPO']) &&  $_POST['TIPO']  == 2)? 'checked' : '' ?>/>
                                <label class="btn col" for="option3">SAÍDA</label></input>                  
                            </div>
                            <div class="col-4 mx-auto">
                                <div class="input-group">
                                    <input type="date" class="form-control" name="DATA_INICIAL" value="<?= isset($_POST['DATA_INICIAL']) ? $_POST['DATA_INICIAL'] : date('Y-m-01'); ?>">
                                    <span class="input-group-text">Á</span>
                                    <input type="date" class="form-control" name="DATA_FINAL" value="<?= isset($_POST['DATA_FINAL']) ? $_POST['DATA_FINAL'] : date('Y-m-t'); ?>">
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="filtrar">
                    </form>
                </div>
               
                <div class="col-12 row mx-auto text-center align-items-center mb-3 align-middle mt-3">
                    <div class="col-6 mx-auto">
                        <button type='submit' name='btnPrint' class='btn btn-outline-dark text-center' onclick='window.print();'>
                            <i class="bi bi-printer"></i>
                        </button>
                    </div>
                    <div class="col-6 mx-auto">
                        <?= $qtd ?> RESULTADOS
                        <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($empresa['EMP_COD']) ? $empresa['EMP_COD'] : 0; ?>">
                        <input type="hidden" class="form-control" name="filtrar" value="1">
                    </div>
                </div>
                <div class="mx-auto col-12 row">
                <?php if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Conta</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Data</th>
                            <th class="text-dark">Classificação</th>
                           
                            <th class="text-dark">Forma de Pgto</th>
                            <th class="text-dark">TIPO</th>
                            <th class="text-dark">ENTRADA</th>
                            <th class="text-dark">SAÍDA</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Obs</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            $entrada = $saida = $saldo = $te = $ts = 0;
                            for ($i= 0; $i < $qtd; $i++) {  
                                ($transacoes[$i]['TRS_TIPO'] == 1)? $entrada +=$transacoes[$i]['TRS_VALOR_TOTAL']: $saida +=$transacoes[$i]['TRS_VALOR_TOTAL'];
                                ($transacoes[$i]['TRS_TIPO'] == 1)? $te++ : $ts++;
                                $saldo = ($entrada-$saida);
                                $data = new DateTime($transacoes[$i]['TRS_DT_CADASTRO']); ?>
                            <tr class="<?= ($transacoes[$i]['TRS_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $transacoes[$i]['CTA_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $transacoes[$i]['TRS_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <td class="text-center align-middle">
                                    <?php 
                                    if($transacoes[$i]['CLA_COD'] != 0 or $transacoes[$i]['CLA_COD'] != '') {
                                        for ($c = 0; $c < $qtdCL; $c++) { 
                                            if ($classificacoes[$c]['CLA_COD'] == $transacoes[$i]['CLA_COD']) { ?>
                                            <?= $classificacoes[$c]['CLA_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                
                                <td class="text-center align-middle">
                                <?php 
                                    if($transacoes[$i]['FPG_COD'] != 0 or $transacoes[$i]['FPG_COD'] != '') {
                                        for ($f = 0; $f < $qtdFP; $f++) { 
                                            if ($formas_pagamentos[$f]['FPG_COD'] == $transacoes[$i]['FPG_COD']) { ?>
                                            <?= $formas_pagamentos[$f]['FPG_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <?= ($transacoes[$i]['TRS_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">ENTRADA</span></td>' : '<td class="text-center align-middle"><span class="text-danger">SAÍDA</span></td>'; ?>
                                <?= ($transacoes[$i]['TRS_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">R$ '.number_format($transacoes[$i]['TRS_VALOR_TOTAL'],2,',','.').'</td><td></td>' : '<td></td><td class="text-center align-middle"><span class="text-danger">R$ '.number_format($transacoes[$i]['TRS_VALOR_TOTAL'],2,',','.').'</span></td>'; ?>
                                <td class="text-center align-middle"><?= ($transacoes[$i]['TRS_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <td class="text-center align-middle">
                                </td>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                <td class="text-center align-middle">
                                    <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal' data-bs-target="#deletar" title="Deletar" data-codigo="<?= $transacoes[$i]['TRS_COD']; ?>" data-nome="<?= $transacoes[$i]['TRS_DESCRICAO']; ?>"  data-status="<?= $transacoes[$i]['TRS_STATUS']; ?>"><i class="fa fa-trash"></i></button>
                                </td>
                                <?php } ?>
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th colspan="4" class="text-center align-middle text-dark">ENTRADA</th>
                            <th colspan="4" class="text-center align-middle text-dark">SAÍDA</th>
                            <th colspan="4" class="text-center align-middle text-dark">SALDO</th>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-center align-middle text-dark">QTD</td>
                            <td colspan="2" class="text-center align-middle text-dark">TOTAL</td>
                            <td colspan="2" class="text-center align-middle text-dark">QTD</td>
                            <td colspan="2" class="text-center align-middle text-dark">TOTAL</td>
                            <td colspan="2" class="text-center align-middle text-dark">QTD</td>
                            <td colspan="2" class="text-center align-middle text-dark">TOTAL</td>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-center align-middle"><?= $te ?></td>
                            <td colspan="2" class="text-center align-middle">R$ <?= number_format($entrada,2,',','.') ?></td>
                            <td colspan="2" class="text-center align-middle"><?= $ts ?></td>
                            <td colspan="2" class="text-center align-middle">R$ <?= number_format($saida,2,',','.') ?></td>
                            <td colspan="2" class="text-center align-middle"><?= $qtd ?></td>
                            <td colspan="2" class="text-center align-middle">R$ <?= number_format($saldo,2,',','.') ?></td>
                        </tr>
                        </tfoot>
                    </table>
                <?php }else { ?>
                    <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA TRANSAÇÃO CADASTRADA</h4>
                <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
            <div class="modal" id="deletar" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="deletar" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div id="title2" class="modal-header text-center text-uppercase">
                            
                        </div>
                        <div class="modal-body text-center">
                            <p class="text-center text-uppercase mx-auto">Excluir registro?</p>
                            <span id="LAN_DESCRICAO2" class="mt-3 text-center h5"></span>
                        </div>
                        <div class="modal-footer">
                            <input type="hidden" id="TRS_STATUS" name="TRS_STATUS" value="" />
                            <input type="hidden" id="TRS_COD" name="TRS_COD" value="" />
                            <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                            <button id="sts2" type="button" class="btn btn-danger" value=""><i class="fa fa-trash"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
         $('#filtrar').on('change', function(){
            $(this).closest('form').submit();
        });
    </script>
</body>
</html>