<?php 
use Libraries\Sessao;

include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($transacoes) ? count($transacoes) : 0);
$qtdFP = (is_array($formas_pagamentos) ? count($formas_pagamentos) : 0);
$qtdC = (is_array($categorias) ? count($categorias) : 0);
$qtdCL = (is_array($classificacoes) ? count($classificacoes) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid <?= $modulo[0]['MOD_COR'] ?> p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-white mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-dark">Transações</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light  text-dark row  py-2">
                <div class="container mx-auto col-12 row">
                <?php if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Conta</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Data</th>
                            <th class="text-dark">Classificação</th>
                            <th class="text-dark">Categoria</th>
                            <th class="text-dark">Forma de Pgto</th>
                            <th class="text-dark">TIPO</th>
                            <th class="text-dark">ENTRADA</th>
                            <th class="text-dark">SAÍDA</th>
                            <th class="text-dark">Status</th>
                            <th class="text-dark">Obs</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                            $b = 1;
                            for ($i= 0; $i < $qtd; $i++) {  $data = new DateTime($transacoes[$i]['TRS_DT_CADASTRO']);?>
                            <tr class="<?= ($transacoes[$i]['TRS_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : '';?>">
                                <td class="text-center align-middle"><?= $b; ?></td>
                                <td class="text-center align-middle"><?= $transacoes[$i]['CTA_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $transacoes[$i]['TRS_DESCRICAO']; ?></td>
                                <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                                <td class="text-center align-middle">
                                    <?php 
                                    if($transacoes[$i]['CLA_COD'] != 0 or $transacoes[$i]['CLA_COD'] != '') {
                                        for ($c = 0; $c < $qtdCL; $c++) { 
                                            if ($classificacoes[$c]['CLA_COD'] == $transacoes[$i]['CLA_COD']) { ?>
                                            <?= $classificacoes[$c]['CLA_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($transacoes[$i]['CAT_COD'] != 0 or $transacoes[$i]['CAT_COD'] != '') {
                                        for ($c = 0; $c < $qtdC; $c++) { 
                                            if ($categorias[$c]['CAT_COD'] == $transacoes[$i]['CAT_COD']) { ?>
                                            <?= $categorias[$c]['CAT_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <td class="text-center align-middle">
                                <?php 
                                    if($transacoes[$i]['FPG_COD'] != 0 or $transacoes[$i]['FPG_COD'] != '') {
                                        for ($c = 0; $c < $qtdFP; $c++) { 
                                            if ($formas_pagamentos[$c]['FPG_COD'] == $transacoes[$i]['FPG_COD']) { ?>
                                            <?= $formas_pagamentos[$c]['FPG_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                                </td>
                                <?= ($transacoes[$i]['TRS_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">ENTRADA</span></td>' : '<td class="text-center align-middle"><span class="text-danger">SAÍDA</span></td>'; ?>
                                <?= ($transacoes[$i]['TRS_TIPO'] == 1)? '<td class="text-center align-middle"><span class="text-primary">'.number_format($transacoes[$i]['TRS_VALOR_TOTAL'],2,',','.').'</td><td></td>' : '<td></td><td class="text-center align-middle"><span class="text-danger">'.number_format($transacoes[$i]['TRS_VALOR_TOTAL'],2,',','.').'</span></td>'; ?>
                                <td class="text-center align-middle"><?= ($transacoes[$i]['TRS_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                                <td class="text-center align-middle">
                                </td>
                                <?php } ?>
                            </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                <?php }else { ?>
                    <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUMA TRANSAÇÃO CADASTRADA</h4>
                <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>