<div class="col-12 my-5 text-center justify-content-center text-lg-start text-white-50">
    <img src="<?= DIRIMG ?>lctec_fundo_escuro.png" class="img-fluid mx-auto" style="width: 50px; height: auto;" alt="..."> 
    <!--<h1 class="fs-4 text-center fw-bolder text-uppercase">LC<span class="fs-3 text-small">/</span><span class="text-success">TEC</span></h1>-->
    <p class="col-lg lead text-center fs-5">DESENVOLVENDO SOLUÇÕES <br> PARA O SEU NEGÓCIO</p>
</div>