<?php use Libraries\Sessao; ?>
<link rel="stylesheet" href="<?= DIRCSS ?>style.css">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="<?= DIRJS ?>scripts.js"></script>
<footer class="fixed-bottom bg-dark mt-auto py-4">
      <div class="container text-center">
        <span class="text-uppercase text-secondary">LC-TEC © 2023 Copyright Todos os direitos reservados </span>
      </div>
</footer>