<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($lancamentos) ? count($lancamentos) : 0);
$qtdC = (is_array($contas) ? count($contas) : 0);
$qtdR = (is_array($contas_receber) ? count($contas_receber) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>financeiro">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-success">Lançamentos</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light  text-dark row  py-2">
                <div class="container mx-auto col-12 row">
                    <div class="card bg-success mx-auto text-center col-12 py-1 mb-2">
                        <div class="card-body text-white">
                            <h5 class="card-title">LANÇAMENTOS</h5>
                            <p class="card-text">Cadastre seus lançamentos</p>
                            <a href="<?= DIRPAGE ?>lancamentos/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>
                    <?php
                    if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Conta</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Parcela</th>
                            <th class="text-dark">Classificação</th>
                            <th class="text-dark">Categoria</th>
                            <th class="text-dark">Forma de Pgto</th>
                            <th class="text-dark">Data Venc.</th>
                            <th class="text-dark">Valor</th>
                            <th class="text-dark">Data Pagamento</th>
                            <th class="text-dark">Obs</th>
                            <th class="text-dark">Status</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                         $b = 1;
                         for ($i= 0; $i < $qtd; $i++) { 
                             $data = new DateTime($lancamentos[$i]['LAN_DT_CADASTRO']);
                        ?>
                         <tr class="<?= ($lancamentos[$i]['LAN_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                            <td class="text-center align-middle"><?= $b; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos[$i]['LAN_TIPO']; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos[$i]['LAN_DESCRICAO']; ?></td>
                        </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM LANÇAMENTO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="LAN_DESCRICAO" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="LAN_STATUS" name="LAN_STATUS" value="" />
                    <input type="hidden" id="LAN_COD" name="LAN_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#LAN_COD').val(codigo);
                modal.find('#LAN_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#LAN_DESCRICAO').html(nome);

                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o lançamento?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o lançamento?');
                }
            });
        });
        $("#sts").click(function(){
            var LAN_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var LAN_STATUS = $('#LAN_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>lancamentos/status', {LAN_COD: LAN_COD,STATUS_LANCAMENTO: true,EMP_COD: EMP_COD,LAN_STATUS: LAN_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>lancamentos"}, 100);
            });

        });
    </script>
</body>
</html>