<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($lancamentos) ? count($lancamentos) : 0);
$qtdL = (is_array($lan_todos) ? count($lan_todos) : 0);

$qtdC = (is_array($contas) ? count($contas) : 0);
//$qtdR = (is_array($contas_receber) ? count($contas_receber) : 0);
//dump($qtdL);
$qtdPg = (isset($_POST['LAN_QTD']) && $_POST['LAN_QTD'] != 10) ? $_POST['LAN_QTD'] : 10;
$qtdP = ceil($qtdL/$qtdPg);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3 d-print-none">
                <section class="container px-3 ">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>lancamentos">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2">
                                    <i class="bi bi-coin"></i> Gerenciar  <span class="text-success">Lançamentos</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5 d-print-none">
                    <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light text-dark row py-2">
                <div class="container mx-auto col-12 row ">
                    <div class="card bg-success mx-auto text-center col-12 py-1 mb-2 d-print-none">
                        <div class="card-body text-white">
                            <h5 class="card-title">LANÇAMENTOS</h5>
                            <p class="card-text">Cadastre seus lançamentos</p>
                            <a href="<?= DIRPAGE ?>lancamentos/cadastro" class="btn btn-dark">NOVO CADASTRO</a>
                        </div>
                    </div>  
                    <form class="p-4 p-md-6 border text-uppercase rounded-3 bg-3 d-print-none" id="filtrar" name="filtrar" action="<?= DIRPAGE ?>lancamentos" method="POST">
                        <div class="col-12 row mx-auto align-items-center align-middle ">
                            <div class="col-2 row">    
                                <select class="col-1 form-select" name="LAN_QTD" >
                                <option value="0">...</option>
                                <?php for ($q=10; $q <= 100; $q++) { ?>
                                    <?php if ($q > 10) { $q += 9; } ?>
                                    <option value="<?= $q ?>" <?= (isset($_POST['LAN_QTD']) &&  $_POST['LAN_QTD']  == $q)? 'selected' : $qtdPg ?>><?= $q ?></option>
                                <?php } ?>
                                </select>
                            </div>
                            <div class="col-5 mx-auto">
                                <input type="radio" class="btn-check" name="LAN_TIPO" id="option5" value="0" <?= (!isset($_POST['LAN_TIPO']) or  $_POST['LAN_TIPO']  == 0)? 'checked' : '' ?>>
                                <label class="btn col" for="option5">TODOS</label></input>
                                <input type="radio" class="btn-check" name="LAN_TIPO" id="option2" value="1" <?= (isset($_POST['LAN_TIPO']) &&  $_POST['LAN_TIPO']  == 1)? 'checked' : '' ?>/>
                                <label class="btn col" for="option2">À PAGAR</label></input>
                                <input type="radio" class="btn-check" name="LAN_TIPO" id="option3" value="2" <?= (isset($_POST['LAN_TIPO']) &&  $_POST['LAN_TIPO']  == 2)? 'checked' : '' ?>/>
                                <label class="btn col" for="option3">À RECEBER</label>     </input>                           
                            </div>
                            <div class="col-5 mx-auto">
                                <input type="radio" class="btn-check" name="LAN_RESULTADOS" id="op6" value="2" <?= (!isset($_POST['LAN_RESULTADOS']) or  $_POST['LAN_RESULTADOS']  == 2)? 'checked' : '' ?>>
                                <label class="btn col" for="op6">TODOS</label></input>
                                <input type="radio" class="btn-check" name="LAN_RESULTADOS" id="op7" value="1" <?= (isset($_POST['LAN_RESULTADOS']) &&  $_POST['LAN_RESULTADOS']  == 1)? 'checked' : '' ?>/>
                                <label class="btn col" for="op7">PARTICIPA</label></input>
                                <input type="radio" class="btn-check" name="LAN_RESULTADOS" id="op8" value="0" <?= (isset($_POST['LAN_RESULTADOS']) &&  $_POST['LAN_RESULTADOS']  == 0)? 'checked' : '' ?>/>
                                <label class="btn col" for="op8">NÃO PARTICIPA</label></input>                           
                            </div>
                            <!--<div class="col-2 row mx-auto ">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" name="LAN_RESULTADOS" title="PARTICIPA DOS RESULTADOS" role="switch" id="flexSwitchCheckChecked" <?php  // (isset($_POST['LAN_RESULTADOS']) && $_POST['LAN_RESULTADOS'] == 'on')? 'checked': ''?>>
                                </div>
                            </div>-->
                           
                            
                        </div>
                        <div class="col-12 row mx-auto mt-3">
                            <div class="col-4">
                                <button type='submit' name='btnPrint' class='btn btn-outline-dark text-center' onclick='window.print();'>
                                    <i class="bi bi-printer"></i>
                                </button>
                            </div>
                            <div class="col-4 mx-auto">
                                <div class="input-group">
                                    <input type="date" class="form-control" name="LAN_DT_INICIAL" value="<?= isset($_POST['LAN_DT_INICIAL']) ? $_POST['LAN_DT_INICIAL'] : date('Y-01-01'); ?>">
                                    <span class="input-group-text">Á</span>
                                    <input type="date" class="form-control" name="LAN_DT_FINAL" value="<?= isset($_POST['LAN_DT_FINAL']) ? $_POST['LAN_DT_FINAL'] : date('Y-m-t'); ?>">
                                </div>
                            </div>
                            <div class="col-4 mx-auto">
                                <ul class="pagination col-12 text-center">
                                    <li class="page-item"><button type="submit" name="LAN_PAGINA" class="page-link" value="1">Primeira</button></li>
                                    <?php if($qtdP-1 > 1){ ?> <li class="page-item "><button type="submit" name="LAN_PAGINA" class="page-link" title="<?= $LAN_PAGINA-1 ?>" value="<?= ($LAN_PAGINA > 1)? $LAN_PAGINA-1: '' ?>"><<</button></li> <?php } ?>
                                    <li class="page-item active"><button class="page-link"><?= $LAN_PAGINA ?></button></li>
                                    <?php if($qtdP+1 > $qtdP){ ?><li class="page-item"><button type="submit" name="LAN_PAGINA" class="page-link" title="<?= $LAN_PAGINA+1 ?>" value="<?= $LAN_PAGINA+1 ?>">>></button></li><?php } ?>
                                    <li class="page-item"><button type="submit" name="LAN_PAGINA" class="page-link" title="<?= $qtdP ?>" value="<?= $qtdP ?>">Última>></button></li>
                                </ul>
                            </div>
                        </div>
                        <input type="hidden" class="form-control" name="EMP_COD" value="<?= isset($empresa['EMP_COD']) ? $empresa['EMP_COD'] : 0; ?>">
                        <input type="hidden" class="form-control" name="filtrar" value="1">
                    </form>
                    <section class="container col-12 mx-auto p-1 text-center fs-4 d-print-none">
                    <?= $qtd ?> RESULTADOS
                    </section>
                
                    <?php
                    if($qtd != 0) { ?>
                    <table class="table table-striped table-bordered">
                        <thead class="text-center text-uppercase">
                            <th class="text-dark">#</th>
                            <th class="text-dark" title="Participa dos resultados da empresa">R</th>
                            <th class="text-dark">Tipo</th>
                            <th class="text-dark">Conta</th>
                            <th class="text-dark">Descrição</th>
                            <th class="text-dark">Parcela</th>
                            <th class="text-dark">Classificação</th>
                            <th class="text-dark">Categoria</th>
                            <th class="text-dark">Data Venc.</th>
                            <th class="text-dark">Valor</th>
                            <th class="text-dark">Obs</th>
                            <th class="text-dark ">Status</th>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?><th class="text-dark d-print-none">Ações</th><?php } ?>
                        </thead>
                        <tbody>
                        <?php
                         $b = 1;
                         for ($i= 0; $i < $qtd; $i++) { 
                             $data = new DateTime($lancamentos[$i]['LAN_DT_VENCIMENTO']);
                        ?>
                         <tr class="<?= ($lancamentos[$i]['LAN_STATUS'] == 0 && $_SESSION['USU_NIVEL'] >= 8)? 'bg-secondary' : ''; ?>">
                            <td class="text-center align-middle"><?= $b; ?></td>
                            <td class="text-center align-middle <?= ($lancamentos[$i]['LAN_RESULTADOS'] == 1)? 'bg-success text-white': ''; ?>"><?= ($lancamentos[$i]['LAN_RESULTADOS'] == 1)? '$': ''; ?></td>
                            <td class="text-center align-middle"><?= ($lancamentos[$i]['LAN_TIPO'] == 1)? 'A PAGAR': (($lancamentos[$i]['LAN_TIPO'] == 2) ? 'A RECEBER' : 'N.I.'); ?></td>
                            <td class="text-center align-middle">
                            <?php 
                                if($lancamentos[$i]['CTA_COD'] !=0 or $lancamentos[$i]['CTA_COD'] != '') {
                                    for ($c = 0; $c < $qtdC; $c++) { 
                                        if ($contas[$c]['CTA_COD'] == $lancamentos[$i]['CTA_COD']) { ?>
                                        <?= $contas[$c]['CTA_DESCRICAO']; ?>   
                                    <?php } } ?> 
                                <?php }else { ?>
                                    À DEFINIR
                                <?php } ?> 
                            </td>
                            <td class="text-center align-middle"><?= $lancamentos[$i]['LAN_DESCRICAO']; ?></td>
                            <td class="text-center align-middle"><?= $lancamentos[$i]['LAN_PARCELA']; ?></td>
                            <td class="text-center align-middle">
                                <?php 
                                if($lancamentos[$i]['CLA_COD'] !=0 or $lancamentos[$i]['CLA_COD'] != '') {
                                    for ($c = 0; $c < $qtdCL; $c++) { 
                                        if ($classificacoes[$c]['CLA_COD'] == $lancamentos[$i]['CLA_COD']) { ?>
                                        <?= $classificacoes[$c]['CLA_DESCRICAO']; ?>   
                                    <?php } } ?> 
                                <?php }else { ?>
                                    À DEFINIR
                                <?php } ?> 
                            </td>
                            <td class="text-center align-middle">
                                <?php 
                                    if($lancamentos[$i]['CAT_COD'] != 0 or $lancamentos[$i]['CAT_COD'] != '') {
                                        for ($c = 0; $c < $qtdCA; $c++) { 
                                            if ($categorias[$c]['CAT_COD'] == $lancamentos[$i]['CAT_COD']) { ?>
                                            <?= $categorias[$c]['CAT_DESCRICAO']; ?>   
                                        <?php } } ?> 
                                    <?php }else { ?>
                                        À DEFINIR
                                    <?php } ?> 
                            </td>
                            <td class="text-center align-middle"><?= $data->format('d/m/Y'); ?></td>
                            <td class="text-center align-middle"><?= number_format($lancamentos[$i]['LAN_VALOR'],2,',','.'); ?></td>
                            <td class="text-center align-middle">
                                <?php if($lancamentos[$i]['LAN_OBSERVACAO'] != '') { ?>
                                <button type="button" class="btn btn-dark btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#obs" title="" data-codigo="<?= $lancamentos[$i]['LAN_COD']; ?>" data-obs="<?= $lancamentos[$i]['LAN_OBSERVACAO']; ?>" title="Visualizar?" ><i class="fa fa-eye"></i></button>
                                <?php } ?> 
                            </td>
                            <td class="text-center align-middle"><?= ($lancamentos[$i]['LAN_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                            <?php if($_SESSION['USU_NIVEL'] >= 8){ ?>
                            <td class="text-center align-middle d-print-none">
                                <?php if($lancamentos[$i]['LAN_STATUS'] == 0){ ?>
                                <button type="button" class="btn btn-success btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $lancamentos[$i]['LAN_COD']; ?>" data-nome="<?= $lancamentos[$i]['CLI_NOME']; ?>" data-status="<?= $lancamentos[$i]['LAN_STATUS']; ?>" title="Deseja ativar?" ><i class="fa fa-ban"></i></button>
                                <?php }else { ?>
                                <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'lancamentos/alteracao/'.$lancamentos[$i]['EMP_COD'].'/'.$lancamentos[$i]['LAN_COD']; ?>" title="Alterar lancamento"><i class="fa fa-edit"></i></a>
                                <button type="button" class="btn btn-danger btn-sm d-print-none" data-bs-toggle='modal'  data-bs-target="#status" data-codigo="<?= $lancamentos[$i]['LAN_COD']; ?>" data-nome="<?= $lancamentos[$i]['LAN_DESCRICAO']; ?>" data-status="<?= $lancamentos[$i]['LAN_STATUS']; ?>" title="Deseja desativar?" ><i class="fa fa-ban"></i></button>
                                <?php } ?>
                            </td>
                            <?php } ?>
                        </tr>
                        <?php $b++; } ?>
                        </tbody>
                    </table>
                    
                    <?php }else { ?>
                        <h4 class="text-center text-warning fs-4">EMPRESA SEM NENHUM LANÇAMENTO CADASTRADO</h4>
                    <?php } ?>
                </div>
            </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
    <div class="modal" id="status" tabindex="-1" role="dialog" data-bs-backdrop="true" aria-labelledby="status" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div id="title" class="modal-header text-center text-uppercase">
                    
                </div>
                <div class="modal-body text-center">
                    <p class="text-center text-uppercase mx-auto">Confirma mudança de status deste registro?</p>
                    <span id="LAN_DESCRICAO" class="mt-3 text-center h5"></span>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="LAN_STATUS" name="LAN_STATUS" value="" />
                    <input type="hidden" id="LAN_COD" name="LAN_COD" value="" />
                    <input type="hidden" id="EMP_COD" name="EMP_COD" value="<?= $empresa['EMP_COD'] ?>" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCELAR</button>
                    <button id="sts" type="button" class="btn btn-dark" value=""></button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#status').on('show.bs.modal', function(event) {
                var button = null;
                var button = $(event.relatedTarget); // Button that triggered the modal
                var codigo = null;
                var codigo = button.data('codigo'); // Extract info from data-* attributes
                var nome = button.data('nome');
                var status = button.data('status');
                var modal = $(this);
                modal.find('#LAN_COD').val(codigo);
                modal.find('#LAN_STATUS').val(status);
                modal.find('#sts').val(codigo);
                modal.find('#LAN_DESCRICAO').html(nome);

                if (status === 1) {
                    modal.find('#sts').html('<i class="fa fa-ban"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja desativar o lançamento?');
                }else{
                    modal.find('#sts').html('<i class="fa fa-circle-check"></i> CONFIRMAR');
                    modal.find('#title').html('Deseja ativar o lançamento?');
                }
            });
        });
        $("#sts").click(function(){
            var LAN_COD = $('#sts').val();
            var EMP_COD = $('#EMP_COD').val();
            var LAN_STATUS = $('#LAN_STATUS').val();
            setTimeout(function () {
                    $('#status').modal('hide');
            }, 100);
            $.post('<?= DIRPAGE; ?>lancamentos/status', {LAN_COD: LAN_COD,STATUS_LANCAMENTO: true,EMP_COD: EMP_COD,LAN_STATUS: LAN_STATUS,cache: false}, function(retorno) {
                var resposta = JSON.parse(retorno);
                if (resposta['COD'] !== 'ERRO') {
                    $('#resposta').addClass('alert alert-success');
                }else{
                    $('#resposta').addClass('alert alert-warning');
                }
                $('#resposta').html(resposta['MENSAGEM']);
                setTimeout( () => { window.location.href="<?= DIRPAGE ?>lancamentos"}, 100);
            });

        });

        $('#filtrar').on('change', function(){
            $(this).closest('form').submit();
        });
    </script>
</body>
</html>