<?php 
use Libraries\Sessao;
use Libraries\Url;
use Libraries\Util;
$Util = new Util;
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
?>
    <body class="">
        <div class="d-flex" id="wrapper">
            <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
            <div id="page-content-wrapper">
            <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid p-0">
                <header class="py-3 text-white <?= $modulo[0]['MOD_COR'] ?>">
                    <section class="container px-3">
                        <div class="row gx-5 align-items-center text-white justify-content-center">
                            <div class="col-lg-9 col-xl-9 col-xxl-9">
                                <div class="my-1 px-4 mx-auto">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>comercial">
                                    <h5 class="fs-2 fw-bolder text-uppercase text-white"><?= $modulo[0]['MOD_ICON'] ?> Gerenciar <span class="">Vendas</span></h5></a>
                                </div>
                            </div>
                            <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?>   
                        </div>
                    </section>
                    <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                    </section>
                </header>
                <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
                <section class="container-fluid col-12 bg-light mx-auto py-2 mb-5">

                </section>
            </div>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </body>
</html>