<?php use Libraries\Util; ?>
<!--<div class="text-center">
<script src="<?php // DIRJS ?>calendario_admin.js"></script>
       <script type="text/javascript">
            var mois = <?php // date('m') ?>;
            calendar(mois);
        </script>
</div>-->
<style>
    table td.other-month{
        opacity: .5;
    }
</style>
<div class="row col-12">
    <div class="col-6">
   <table class="table table-bordered table-striped text-center">
        <thead>
            <tr>
            <th colspan="7">
                <!-- https://www.youtube.com/watch?v=O1nT0jvj11A -->
                <span class="btn-group"> 
                    <?php $mes = Util::getMesAtual(); ?>
                    <a href="<?= DIRPAGE.'admin/mes/'.Util::retMes($mes); ?>" class="btn"><i class="bi bi-chevron-double-left"></i> </a>
                    <a class="btn active"><?= date('F',$startDate)?></a>
                    <a href="<?= DIRPAGE.'admin/mes/'.Util::avcMes($mes); ?>" class="btn"><i class="bi bi-chevron-double-right"></i></a>
                </span>
            </th>
            </tr>
            <tr>
                <th>DOM</th>
                <th>SEG</th>
                <th>TER</th>
                <th>QUA</th>
                <th>QUI</th>
                <th>SEX</th>
                <th>SAB</th>
            </tr>
        </thead>
        <?php
        $startDate = strtotime("last sunday",$mes); 
        echo'<tbody>';
        for ($row =0; $row  < 6; $row ++) { 
            echo'<tr>';
            for ($cl=0; $cl < 7; $cl++) { 
                
                if (date('Y-m',$startDate) !== date('Y-m',$mes)) {
                    echo'<td class="other-month">';
                } else {
                    echo'<td>';
                }
                echo date('j',$startDate);
                echo'</td>';
                //somando o calendario
                $startDate = strtotime("+1 day",$startDate);
            }
            echo'</tr>';
        }
        echo'</tbody></table>';
?>
           <!--
            <tr>
                <td>5</td>
                <td>6</td>
                <td>7</td>
                <td>8</td>
                <td>9</td>
                <td>10</td>
                <td>11</td>
            </tr>
            <tr>
                <td>12</td>
                <td>13</td>
                <td>14</td>
                <td>15</td>
                <td>16</td>
                <td>17</td>
                <td>18</td>
            </tr>
            <tr>
                <td>19</td>
                <td class="btn-primary"><strong>20</strong></td>
                <td>21</td>
                <td>22</td>
                <td>23</td>
                <td>24</td>
                <td>25</td>
            </tr>
            <tr>
                <td>26</td>
                <td>27</td>
                <td>28</td>
                <td>29</td>
                <td class="muted">1</td>
                <td class="muted">2</td>
                <td class="muted">3</td>
            </tr>-->

    </div>  
</div>
