<div class="bg-dark position-relative d-print-none" id="sidebar-wrapper" style="font-size: 1.15rem;">
    <div class="sidebar-heading fw-bold fs-3 text-white" style="width: auto; height:68px;">LC-<span class="text-success">TEC</span></div>

    <div class="d-flex align-items-start">
        <div class="list-group list-group-flush text-uppercase" >
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Painel Administrativo" href="<?= DIRPAGE?>admin"><i class="bi bi-house"></i>  PAINEL</a>
            <?php if ($_SESSION['EMP_COD'] != 0) { ?>
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Cadastros da Empresa/Negócio" href="<?= DIRPAGE?>cadastros"><i class="bi bi-plus-square"></i> CADASTROS</a>
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Estoques da Empresa/Negócio" href="<?= DIRPAGE?>estoques"><i class="bi bi-plus-square"></i> ESTOQUES</a>
            <!--<a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Ponto de Venda da Empresa/Negócio" href="<?php //DIRPAGE?>financeiro/pdv"><i class="bi bi-cash-coin"></i> PDV</a>
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Configuraões do Sistema" href="<?php // DIRPAGE?>configuracoes"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</a>-->
            <?php } ?>
        </div>
   
    </div>
    <hr>
    <div class="position-absolute bottom-0 mb-0 py-0 start-0">
        <div class="list-group list-group-flush text-uppercase py-0" >
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Encerrar Acesso" href="<?= DIRPAGE?>login/sair"><i class="bi bi-box-arrow-right"></i> SAIR</a>
        </div>
    </div>
</div>