<div class="bg-dark position-relative d-print-none" id="sidebar-wrapper" style="font-size: 1.15rem;">
   
    <div class="sidebar-heading fw-bold fs-3 text-white" style="width: auto; height:68px;">LC/<span class="text-success">TEC</span></div>

    <div class="d-flex align-items-start">
    <div class="list-group list-group-flush text-uppercase mb-4" >
        
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Painel Administrativo" href="<?= DIRPAGE?>admin"><i class="bi bi-house"></i>  PAINEL ADM</a>
        <?php if ($_SESSION['USU_NIVEL'] >=20) { ?>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Painel Gerencial" href="<?= DIRPAGE?>lctec"><i class="bi bi-house"></i>  PAINEL LC/<span class="text-success">TEC</span></a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Empresas/Negócios" href="<?= DIRPAGE?>lctec/empresas"><i class="bi bi-plus-square"></i> EMPRESAS</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/equipes"><i class="bi bi-cash-coin"></i> ADMINISTRATIVO</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Cadastros" href="<?= DIRPAGE?>lctec/cadastros"><i class="bi bi-cash-coin"></i> CADASTROS</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/equipes"><i class="bi bi-cash-coin"></i> EQUIPES</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/suporte"><i class="bi bi-cash-coin"></i> SUPORTE</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/usuarios"><i class="bi bi-cash-coin"></i> DESEMPENHO</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/usuarios"><i class="bi bi-cash-coin"></i> MANUTENÇÃO</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/modulos"><i class="bi bi-cash-coin"></i> MÓDULOS</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Equipes" href="<?= DIRPAGE?>lctec/usuarios"><i class="bi bi-cash-coin"></i> USUÁRIOS</a>
        <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Configurações do Sistema" href="<?= DIRPAGE?>lctec/configuracoes"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</a>
        <?php } ?>
    </div>
   
    </div>
    <hr>
    <div class="position-absolute bottom-0 mb-0 py-0 start-0">
        <div class="list-group list-group-flush text-uppercase py-0" >
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Encerrar Acesso" href="<?= DIRPAGE?>login/sair"><i class="bi bi-box-arrow-right"></i> SAIR</a>
        </div>
    </div>
</div>