<?php 
use App\Models\ModulosEmpresa;
$ModulosEmpresa = new ModulosEmpresa;
$mk = $ModulosEmpresa->setCodEmpresa($_SESSION['EMP_COD'])->listar(0);
$qtdMK = (is_array($mk) ? count($mk) : 0);
?>
<div class="bg-dark position-relative d-print-none" id="sidebar-wrapper" style="font-size: 1rem;">
    <div class="sidebar-heading fw-bold fs-3 text-center text-white" title="" style="width: auto; height: auto;">LC<span class="fs-3 text-small">/</span><span class="text-success">TEC</span></div>
<div class="mt-3"></div>
    <div class="d-flex align-items-start">
        <div class="list-group list-group-flush text-uppercase" >
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Painel Administrativo" href="<?= DIRPAGE?>admin"><i class="bi bi-house"></i>  PAINEL ADM</a>
            <?php if (isset($_SESSION['EMP_COD']) && $_SESSION['EMP_COD'] != 0) { ?>
                <?php if(isset($_SESSION['USU_NIVEL']) && $_SESSION['USU_NIVEL'] >= 20){ ?>
                <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Painel Gerencial" href="<?= DIRPAGE?>lctec"><i class="bi bi-house"></i>  PAINEL LC/<span class="text-success">TEC</span></a>
                <?php } ?>
            <?php if ($qtdMK != 0) { 
                for ($i=0; $i < $qtdMK; $i++) { ?>
                    <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="<?= $mk[$i]['MOD_NOME']; ?>" href="<?= DIRPAGE?><?= $mk[$i]['MOD_LINK']; ?>"><i class="bi bi-plus-square"></i> <?= $mk[$i]['MOD_NOME']; ?></a>
                <?php } } ?>
            <!--<a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Ponto de Venda da Empresa/Negócio" href="<?php //DIRPAGE?>financeiro/pdv"><i class="bi bi-cash-coin"></i> PDV</a>
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Configuraões do Sistema" href="<?php // DIRPAGE?>configuracoes"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</a>-->
            <?php } ?>
        </div>
   
    </div>
    <hr>
    <div class="position-absolute bottom-0 mb-0 py-0 start-0">
        <div class="list-group list-group-flush text-uppercase py-0" >
            <a class="list-group-item list-group-item-action list-group-item-dark p-3 px-3" title="Encerrar Acesso" href="<?= DIRPAGE?>login/sair"><i class="bi bi-box-arrow-right"></i> SAIR</a>
        </div>
    </div>
</div>