<footer class=" bg-light text-secondary py-2 mb-0 static-bottom">
    <!-- Core theme JS-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <div class="text-dark py-1 mt-auto position-relative">
        <div class="container px-4">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 ">Copyright &copy; LC-TECH | <?= date('Y') ?></div></div>
                <div class="col-auto text-right text-uppercase">
                    <?php if (isset($_SESSION['USU_NIVEL']) && $_SESSION['USU_NIVEL'] == 8) { ?>
                            <a href="<?= DIRPAGE ?>admin/painel" class="text-decoration-none fw-bold text-success"><i class="bi bi-house"></i> PAINEL ADMINISTRATIVO</a>
                    <?php }else { ?>
                        <a href="<?= DIRPAGE ?>financeiro/acesso" class="text-decoration-none fw-bold text-primary"><i class="bi bi-house"></i> TROCAR VENDEDOR/OPERADOR</a>
                    <?php } ?>
                    <?php if (isset($_SESSION['VDD_COD']) || isset($_SESSION['USU_COD'])){ ?>
                    <a class="col link-dark text-dark text-decoration-none small" title="Encerrar acesso ao sistema" href="<?= DIRPAGE ?>login/sair"><i class="bi bi-box-arrow-right"></i> Sair</a>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</footer>