<?php
use App\Models\Avisos as ModelsAviso;
$Avisos = new ModelsAviso;
$avisos = $Avisos->setCodEmpresa($_SESSION['EMP_COD'])->listarTodos(0);
$qtdAvisos = (is_array($avisos) ? count($avisos) : 0);
?>
<footer class=" bg-light text-secondary py-2 mb-0 static-bottom d-print-none">
    <!-- Core theme JS-->
    <?= $qtdAvisos >= 1 ? '<div class="py-2 bg-warning col-12">
        <div class="toast" role="alert" id="myToast" aria-live="polite" aria-atomic="true" data-bs-delay="10000">
        <div role="alert" aria-live="assertive" aria-atomic="true">...</div>
    </div>
    </div>' : ''?>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8/jquery.inputmask.min.js" integrity="sha512-efAcjYoYT0sXxQRtxGY37CKYmqsFVOIwMApaEbrxJr4RwqVVGw8o+Lfh/+59TU07+suZn1BWq4fDl5fdgyCNkw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="<?= DIRJS ?>painel_admin.js"></script>

    <div class="text-dark py-1 mt-auto position-relative">
        <div class="container px-4">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto"><div class="small m-0 ">Copyright &copy; LC-TEC | <?= date('Y') ?></div></div>
                <?php if (isset($_SESSION['VDD_COD']) || isset($_SESSION['USU_COD'])){ ?>
                <div class="col-auto text-uppercase fs-5">
                    <a class="col link-dark text-dark text-decoration-none small" title="Encerrar acesso ao sistema" href="<?= DIRPAGE ?>login/sair"><i class="bi bi-box-arrow-right"></i> Sair</a>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</footer>
<?php include_once 'app/Views/admin/inc/limite_acesso.phtml';?>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

    setInterval(async () => {
       
        
        window.addEventListener("offline", (event) => {
            const statusDisplay = document.getElementById("status_conexao");
            //statusDisplay.title  = "OFFline";
            $(statusDisplay).attr('data-bs-content','OFFline');
            console.log('OFFline');
        });

        window.addEventListener("online", (event) => {
            const statusDisplay = document.getElementById("status_conexao");
            //console.log(statusDisplay);
            $(statusDisplay).attr('data-bs-content','Online');
            //statusDisplay.getElementsByTagName('data-bs-content')[0].innerText  = 'Online';
            //statusDisplay.title  = "Online";
            console.log('Online');
        });
        
    }, 3000);
    setInterval(async () => {

        var EMP_COD = <?php echo $_SESSION['EMP_COD']; ?>;

        $.post('<?= DIRPAGE; ?>avisos/checarAvisos', {EMP_COD: EMP_COD}, function(retorno) {
            db = JSON.parse(retorno);
            //console.log(db);
            //$('#PRO_QUANTIDADE').html(db.PRO_QUANTIDADE);
        });
    }, 40000);
</script>